"""Query routing for the canonical Rx-volume KPIs WS3-BI-005..008 (canonical TRx lane).

The statements are registered by migration 143 (generated by
scripts/gen_canonical_volume_registry.py). Routing mirrors the event family's
brand / region / window grammar with one difference that is the point of the
lane: a PATIENT AXIS is refused, naming the patient-panel KPI that serves it —
business_metrics has no patient dimension, and silently answering a canonical id
with an event query would recreate the two-scales defect (#1640).
"""

from __future__ import annotations

from typing import Any, List, Mapping, Tuple

from src.kpi.synthetic_mode import region_query_id, windowed_query_id
from src.kpi.volume_family import CANONICAL_TO_PANEL, PATIENT_AXES

#: kpi id -> (base statement id, result key)
CANONICAL_VOLUME_STATEMENTS: Mapping[str, Tuple[str, str]] = {
    "WS3-BI-005": ("canonical_volume_trx", "trx"),
    "WS3-BI-006": ("canonical_volume_nrx", "nrx"),
    "WS3-BI-007": ("canonical_volume_nbrx", "nbrx"),
    "WS3-BI-008": ("canonical_volume_trx_share", "share"),
}
SHARE_KPI_ID = "WS3-BI-008"


def refuse_patient_axis(kpi_id: str, context: Mapping[str, Any]) -> None:
    """Raise when a patient axis is requested on a canonical volume KPI."""
    for axis in PATIENT_AXES:
        if context.get(axis) is not None:
            panel = CANONICAL_TO_PANEL[kpi_id]
            raise RuntimeError(
                f"KPI {kpi_id} does not support the {axis} breakdown: its canonical series is "
                f"brand x region x calendar month (business_metrics). Patient-axis splits exist "
                f"only for the patient-panel KPI {panel} (observed Rx events), which measures a "
                f"different, much smaller quantity."
            )


def canonical_query_call(kpi_id: str, context: dict[str, Any]) -> Tuple[str, List[Any], str]:
    """``(query_id, params, result_key)`` for one canonical volume calculation.

    Marks ``context["_region_routed"]`` at the exact point a region statement is
    chosen (#1538 provenance, same contract as ``_resolve_windowed_call``).
    """
    base, result_key = CANONICAL_VOLUME_STATEMENTS[kpi_id]
    refuse_patient_axis(kpi_id, context)
    brand = context.get("brand")
    region = context.get("region")
    window = context.get("window")
    if kpi_id == SHARE_KPI_ID and not brand:
        raise RuntimeError(
            "KPI WS3-BI-008 unavailable: no brand specified for TRx share (a portfolio "
            "share of the portfolio is undefined)"
        )
    if window is None:
        if region:
            context["_region_routed"] = True
            return region_query_id(base), [brand, region], result_key
        return base, [brand], result_key
    query_id = windowed_query_id(base, region=bool(region))
    if region:
        context["_region_routed"] = True
        return query_id, [brand, region, window["start"], window["end"]], result_key
    return query_id, [brand, window["start"], window["end"]], result_key
