#!/bin/bash

# Auto-Build Environment Setup for E2I Causal Analytics Frontend
# Generated by Planner Agent - Spec 002

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo "========================================"
echo "E2I Causal Analytics - Frontend Development"
echo "========================================"
echo ""

# Function to wait for a service to be ready
wait_for_service() {
    local port=$1
    local name=$2
    local max=60
    local count=0

    echo -e "${YELLOW}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
        printf "."
    done
    echo ""
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
}

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo -e "${BLUE}Running pre-flight checks...${NC}"

# Check Node.js
if ! command_exists node; then
    echo -e "${RED}✗ Node.js not found. Please install Node.js 20+${NC}"
    exit 1
fi
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}✗ Node.js version must be 20 or higher (found: $(node -v))${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check npm
if ! command_exists npm; then
    echo -e "${RED}✗ npm not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# Check if Docker is running (optional for backend)
if command_exists docker && docker info >/dev/null 2>&1; then
    echo -e "${GREEN}✓ Docker is running${NC}"
    DOCKER_AVAILABLE=true
else
    echo -e "${YELLOW}⚠ Docker not running (optional for backend services)${NC}"
    DOCKER_AVAILABLE=false
fi

# ============================================
# FRONTEND SETUP
# ============================================

echo ""
echo -e "${BLUE}Setting up frontend...${NC}"

cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
else
    echo -e "${GREEN}✓ Frontend dependencies already installed${NC}"
fi

# Create .env if it doesn't exist
if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Creating .env file from .env.example...${NC}"
    if [ -f ".env.example" ]; then
        cp .env.example .env
    else
        # Create basic .env
        cat > .env << 'EOF'
# Frontend Environment Variables
# All client-side vars must use VITE_ prefix

# Backend API URL (adjust if backend is on different port)
VITE_API_URL=http://localhost:8000

# Use API mocks (set to 'true' to enable MSW mocking)
VITE_USE_MOCKS=false

# Supabase (if needed for direct client access)
# VITE_SUPABASE_URL=
# VITE_SUPABASE_ANON_KEY=
EOF
    fi
    echo -e "${GREEN}✓ Created .env file${NC}"
fi

# ============================================
# BACKEND CHECK (OPTIONAL)
# ============================================

echo ""
echo -e "${BLUE}Checking backend services...${NC}"

cd ..

# Check if backend is running on port 8000
if nc -z localhost 8000 2>/dev/null; then
    echo -e "${GREEN}✓ Backend API detected on port 8000${NC}"
    BACKEND_RUNNING=true
else
    echo -e "${YELLOW}⚠ Backend API not running on port 8000${NC}"
    echo -e "${YELLOW}  Frontend will use mock data (MSW) if configured${NC}"
    echo -e "${YELLOW}  To start backend: make start-dev (in project root)${NC}"
    BACKEND_RUNNING=false
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${BLUE}Starting development servers...${NC}"

# Start frontend dev server
echo -e "${YELLOW}Starting frontend on port 5173...${NC}"
cd frontend
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 5173 "Frontend"

cd ..

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo -e "${BLUE}Services:${NC}"
echo "  Frontend:       http://localhost:5173"
if [ "$BACKEND_RUNNING" = true ]; then
    echo "  Backend API:    http://localhost:8000"
    echo "  API Docs:       http://localhost:8000/api/docs"
else
    echo "  Backend API:    ${YELLOW}NOT RUNNING (using mocks)${NC}"
fi
echo ""
echo -e "${BLUE}Development Commands:${NC}"
echo "  cd frontend && npm run dev       - Start frontend dev server"
echo "  cd frontend && npm run build     - Build for production"
echo "  cd frontend && npm run test      - Run tests"
echo "  cd frontend && npm run lint      - Run linter"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Open http://localhost:5173 in your browser"
echo "  2. Implementation will follow the 12-phase plan in implementation_plan.json"
echo "  3. Check build-progress.txt for detailed progress tracking"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop all services${NC}"
echo ""

# Keep script running and forward signals
trap 'echo ""; echo "Shutting down..."; kill $FRONTEND_PID 2>/dev/null; exit 0' INT TERM

# Wait for frontend process
wait $FRONTEND_PID
