#!/bin/bash

# Auto-Build Environment Setup for E2I React Dashboard Transformation
# Generated by Planner Agent for Spec 002

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "========================================"
echo "E2I React Dashboard - Development Setup"
echo "========================================"
echo ""

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -ne "${YELLOW}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e " ${RED}FAILED${NC}"
            echo -e "${RED}✗ $name failed to start within 30 seconds${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo -e " ${GREEN}OK${NC}"
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
    return 0
}

# Check if required commands exist
command -v node >/dev/null 2>&1 || { echo -e "${RED}✗ Node.js is required but not installed${NC}"; exit 1; }
command -v npm >/dev/null 2>&1 || { echo -e "${RED}✗ npm is required but not installed${NC}"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo -e "${RED}✗ Python 3 is required but not installed${NC}"; exit 1; }

echo -e "${GREEN}✓ All required commands found${NC}"
echo ""

# ============================================
# BACKEND API (FastAPI)
# ============================================
echo -e "${BLUE}Starting Backend API...${NC}"

if [ ! -f ".env" ]; then
    echo -e "${YELLOW}⚠ Warning: .env file not found. Backend may not have required configuration.${NC}"
fi

# Check if backend dependencies are installed
if [ ! -d "venv" ]; then
    echo -e "${YELLOW}⚠ Warning: Python venv not found. Backend may not be set up.${NC}"
fi

# Start backend in background
echo "Starting FastAPI backend on port 8000..."
if [ -d "venv" ]; then
    source venv/bin/activate && python -m uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8000 &
    BACKEND_PID=$!
    echo -e "${GREEN}✓ Backend started (PID: $BACKEND_PID)${NC}"
else
    echo -e "${YELLOW}⚠ Skipping backend startup (venv not found)${NC}"
    BACKEND_PID=""
fi

# Wait for backend to be ready
if [ -n "$BACKEND_PID" ]; then
    wait_for_service 8000 "Backend API" || {
        echo -e "${RED}✗ Backend failed to start${NC}"
        [ -n "$BACKEND_PID" ] && kill $BACKEND_PID 2>/dev/null || true
        exit 1
    }
fi

echo ""

# ============================================
# FRONTEND (React + Vite)
# ============================================
echo -e "${BLUE}Starting Frontend Development Server...${NC}"

cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}⚠ node_modules not found. Installing dependencies...${NC}"
    npm install
    echo -e "${GREEN}✓ Dependencies installed${NC}"
fi

# Start frontend dev server
echo "Starting Vite dev server on port 5173..."
npm run dev &
FRONTEND_PID=$!
echo -e "${GREEN}✓ Frontend started (PID: $FRONTEND_PID)${NC}"

cd ..

# Wait for frontend to be ready
wait_for_service 5173 "Frontend (Vite)" || {
    echo -e "${RED}✗ Frontend failed to start${NC}"
    [ -n "$FRONTEND_PID" ] && kill $FRONTEND_PID 2>/dev/null || true
    [ -n "$BACKEND_PID" ] && kill $BACKEND_PID 2>/dev/null || true
    exit 1
}

echo ""

# ============================================
# OPTIONAL SERVICES
# ============================================
echo -e "${BLUE}Checking Optional Services...${NC}"

# Check if Docker services are running (Redis, FalkorDB)
if command -v docker >/dev/null 2>&1; then
    if docker ps --format '{{.Names}}' | grep -q redis; then
        echo -e "${GREEN}✓ Redis is running${NC}"
    else
        echo -e "${YELLOW}⚠ Redis not detected (optional for some features)${NC}"
    fi

    if docker ps --format '{{.Names}}' | grep -q falkordb; then
        echo -e "${GREEN}✓ FalkorDB is running${NC}"
    else
        echo -e "${YELLOW}⚠ FalkorDB not detected (optional for graph features)${NC}"
    fi
else
    echo -e "${YELLOW}⚠ Docker not installed - optional services unavailable${NC}"
fi

echo ""

# ============================================
# SUMMARY
# ============================================
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  ${GREEN}✓${NC} Backend API:  http://localhost:8000"
echo -e "  ${GREEN}✓${NC} API Docs:     http://localhost:8000/api/docs"
echo -e "  ${GREEN}✓${NC} Frontend:     http://localhost:5173"
echo ""
echo "Process IDs:"
[ -n "$BACKEND_PID" ] && echo -e "  Backend:  $BACKEND_PID"
echo -e "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
[ -n "$BACKEND_PID" ] && echo -e "  kill $BACKEND_PID  # Backend"
echo -e "  kill $FRONTEND_PID  # Frontend"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop all services${NC}"
echo ""

# Trap SIGINT and SIGTERM to clean up background processes
cleanup() {
    echo ""
    echo -e "${YELLOW}Shutting down services...${NC}"
    [ -n "$FRONTEND_PID" ] && kill $FRONTEND_PID 2>/dev/null && echo -e "${GREEN}✓ Frontend stopped${NC}"
    [ -n "$BACKEND_PID" ] && kill $BACKEND_PID 2>/dev/null && echo -e "${GREEN}✓ Backend stopped${NC}"
    echo -e "${GREEN}✓ All services stopped${NC}"
    exit 0
}

trap cleanup SIGINT SIGTERM

# Wait for user interrupt
wait
