/**
 * Agent Insight Card Component
 * ============================
 *
 * Card component for displaying insights generated by E2I agents.
 * Shows agent source, confidence, and actionable recommendations.
 *
 * @module components/visualizations/agents/AgentInsightCard
 */

import * as React from 'react';
import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  CheckCircle2,
  ArrowRight,
  Copy,
  Share2,
  BookmarkPlus,
  ThumbsUp,
  ThumbsDown,
  MessageSquare,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { AgentTierBadge } from './AgentTierBadge';
import type { AgentTier } from './AgentTierBadge';

// =============================================================================
// TYPES
// =============================================================================

export type InsightType = 'opportunity' | 'warning' | 'success' | 'recommendation' | 'analysis';

export interface InsightEvidence {
  /** Evidence description */
  description: string;
  /** Evidence value */
  value?: string | number;
  /** Source of evidence */
  source?: string;
}

export interface InsightAction {
  /** Action label */
  label: string;
  /** Action callback */
  onClick: () => void;
  /** Whether this is the primary action */
  primary?: boolean;
}

export interface AgentInsightCardProps {
  /** Agent name that generated the insight */
  agentName: string;
  /** Agent tier */
  agentTier: AgentTier;
  /** Insight type */
  type: InsightType;
  /** Insight title */
  title: string;
  /** Insight summary/description */
  summary: string;
  /** Detailed explanation (optional) */
  details?: string;
  /** Confidence score (0-1) */
  confidence?: number;
  /** Impact estimate */
  impact?: {
    metric: string;
    value: string | number;
    direction: 'up' | 'down' | 'neutral';
  };
  /** Supporting evidence */
  evidence?: InsightEvidence[];
  /** Available actions */
  actions?: InsightAction[];
  /** Timestamp of the insight */
  timestamp?: Date | string;
  /** Whether the insight is bookmarked */
  isBookmarked?: boolean;
  /** Whether data is loading */
  isLoading?: boolean;
  /** Additional CSS classes */
  className?: string;
  /** Callback for feedback */
  onFeedback?: (helpful: boolean) => void;
  /** Callback for copy */
  onCopy?: () => void;
  /** Callback for share */
  onShare?: () => void;
  /** Callback for bookmark */
  onBookmark?: () => void;
  /** Callback for viewing conversation */
  onViewConversation?: () => void;
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

interface TypeConfig {
  icon: React.ElementType;
  color: string;
  bgColor: string;
  label: string;
}

function getTypeConfig(type: InsightType): TypeConfig {
  switch (type) {
    case 'opportunity':
      return {
        icon: TrendingUp,
        color: 'text-emerald-600',
        bgColor: 'bg-emerald-100 dark:bg-emerald-900/30',
        label: 'Opportunity',
      };
    case 'warning':
      return {
        icon: AlertTriangle,
        color: 'text-amber-600',
        bgColor: 'bg-amber-100 dark:bg-amber-900/30',
        label: 'Warning',
      };
    case 'success':
      return {
        icon: CheckCircle2,
        color: 'text-blue-600',
        bgColor: 'bg-blue-100 dark:bg-blue-900/30',
        label: 'Success',
      };
    case 'recommendation':
      return {
        icon: Sparkles,
        color: 'text-violet-600',
        bgColor: 'bg-violet-100 dark:bg-violet-900/30',
        label: 'Recommendation',
      };
    case 'analysis':
    default:
      return {
        icon: Sparkles,
        color: 'text-slate-600',
        bgColor: 'bg-slate-100 dark:bg-slate-900/30',
        label: 'Analysis',
      };
  }
}

function formatTimestamp(timestamp: Date | string): string {
  const date = typeof timestamp === 'string' ? new Date(timestamp) : timestamp;
  return date.toLocaleString();
}

// =============================================================================
// COMPONENT
// =============================================================================

/**
 * AgentInsightCard displays an insight from an E2I agent.
 *
 * @example
 * ```tsx
 * <AgentInsightCard
 *   agentName="Gap Analyzer"
 *   agentTier={2}
 *   type="opportunity"
 *   title="High-Value HCPs Underserved in Northeast"
 *   summary="15 oncologists with high Rx potential have received less than 2 visits this quarter."
 *   confidence={0.87}
 *   impact={{ metric: 'Potential TRx', value: '+12%', direction: 'up' }}
 *   actions={[
 *     { label: 'View HCPs', onClick: handleViewHCPs, primary: true },
 *   ]}
 * />
 * ```
 */
export const AgentInsightCard = React.forwardRef<HTMLDivElement, AgentInsightCardProps>(
  (
    {
      agentName,
      agentTier,
      type,
      title,
      summary,
      details,
      confidence,
      impact,
      evidence,
      actions,
      timestamp,
      isBookmarked = false,
      isLoading = false,
      className,
      onFeedback,
      onCopy,
      onShare,
      onBookmark,
      onViewConversation,
    },
    ref
  ) => {
    const [showDetails, setShowDetails] = React.useState(false);
    const [feedbackGiven, setFeedbackGiven] = React.useState<boolean | null>(null);
    const typeConfig = getTypeConfig(type);
    const TypeIcon = typeConfig.icon;

    const handleFeedback = (helpful: boolean) => {
      setFeedbackGiven(helpful);
      onFeedback?.(helpful);
    };

    // Loading skeleton
    if (isLoading) {
      return (
        <div
          ref={ref}
          className={cn(
            'animate-pulse bg-[var(--color-card)] rounded-lg border border-[var(--color-border)] p-4',
            className
          )}
        >
          <div className="flex gap-3">
            <div className="w-10 h-10 bg-[var(--color-muted)] rounded-lg" />
            <div className="flex-1 space-y-2">
              <div className="h-4 w-32 bg-[var(--color-muted)] rounded" />
              <div className="h-6 w-3/4 bg-[var(--color-muted)] rounded" />
              <div className="h-4 w-full bg-[var(--color-muted)] rounded" />
            </div>
          </div>
        </div>
      );
    }

    return (
      <div
        ref={ref}
        className={cn(
          'bg-[var(--color-card)] rounded-lg border border-[var(--color-border)] overflow-hidden',
          className
        )}
      >
        {/* Header */}
        <div className="p-4 border-b border-[var(--color-border)]">
          <div className="flex items-start gap-3">
            {/* Type icon */}
            <div className={cn('p-2 rounded-lg', typeConfig.bgColor)}>
              <TypeIcon className={cn('h-5 w-5', typeConfig.color)} />
            </div>

            {/* Content */}
            <div className="flex-1 min-w-0">
              {/* Meta info */}
              <div className="flex items-center gap-2 flex-wrap mb-1">
                <AgentTierBadge tier={agentTier} size="sm" showLabel={false} />
                <span className="text-sm font-medium text-[var(--color-foreground)]">
                  {agentName}
                </span>
                <span className={cn('text-xs px-1.5 py-0.5 rounded', typeConfig.bgColor, typeConfig.color)}>
                  {typeConfig.label}
                </span>
                {confidence !== undefined && (
                  <span className="text-xs text-[var(--color-muted-foreground)]">
                    {Math.round(confidence * 100)}% confidence
                  </span>
                )}
              </div>

              {/* Title */}
              <h3 className="font-semibold text-[var(--color-foreground)]">
                {title}
              </h3>
            </div>

            {/* Actions menu */}
            <div className="flex items-center gap-1">
              {onViewConversation && (
                <Button variant="ghost" size="icon" onClick={onViewConversation} className="h-8 w-8">
                  <MessageSquare className="h-4 w-4" />
                </Button>
              )}
              {onCopy && (
                <Button variant="ghost" size="icon" onClick={onCopy} className="h-8 w-8">
                  <Copy className="h-4 w-4" />
                </Button>
              )}
              {onShare && (
                <Button variant="ghost" size="icon" onClick={onShare} className="h-8 w-8">
                  <Share2 className="h-4 w-4" />
                </Button>
              )}
              {onBookmark && (
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={onBookmark}
                  className={cn('h-8 w-8', isBookmarked && 'text-amber-500')}
                >
                  <BookmarkPlus className="h-4 w-4" />
                </Button>
              )}
            </div>
          </div>
        </div>

        {/* Body */}
        <div className="p-4">
          {/* Summary */}
          <p className="text-sm text-[var(--color-foreground)]">{summary}</p>

          {/* Impact */}
          {impact && (
            <div className="mt-3 flex items-center gap-2 p-2 rounded-lg bg-[var(--color-muted)]">
              <span className="text-sm text-[var(--color-muted-foreground)]">
                {impact.metric}:
              </span>
              <span className={cn(
                'font-semibold flex items-center gap-1',
                impact.direction === 'up' ? 'text-emerald-600' :
                impact.direction === 'down' ? 'text-rose-600' : ''
              )}>
                {impact.direction === 'up' && <TrendingUp className="h-4 w-4" />}
                {impact.direction === 'down' && <TrendingDown className="h-4 w-4" />}
                {impact.value}
              </span>
            </div>
          )}

          {/* Details toggle */}
          {(details || evidence) && (
            <button
              onClick={() => setShowDetails(!showDetails)}
              className="mt-3 text-sm text-[var(--color-primary)] hover:underline flex items-center gap-1"
            >
              {showDetails ? 'Hide details' : 'Show details'}
              <ArrowRight className={cn('h-3 w-3 transition-transform', showDetails && 'rotate-90')} />
            </button>
          )}

          {/* Expanded details */}
          {showDetails && (
            <div className="mt-3 space-y-3">
              {details && (
                <p className="text-sm text-[var(--color-muted-foreground)]">
                  {details}
                </p>
              )}

              {evidence && evidence.length > 0 && (
                <div className="space-y-2">
                  <h4 className="text-xs font-medium text-[var(--color-muted-foreground)] uppercase">
                    Supporting Evidence
                  </h4>
                  {evidence.map((item, index) => (
                    <div
                      key={index}
                      className="text-sm p-2 rounded bg-[var(--color-muted)]"
                    >
                      <p>{item.description}</p>
                      {item.value !== undefined && (
                        <span className="font-medium"> ({item.value})</span>
                      )}
                      {item.source && (
                        <span className="text-xs text-[var(--color-muted-foreground)] ml-1">
                          — {item.source}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-4 py-3 border-t border-[var(--color-border)] bg-[var(--color-muted)]/50">
          <div className="flex items-center justify-between">
            {/* Timestamp */}
            <div className="text-xs text-[var(--color-muted-foreground)]">
              {timestamp && formatTimestamp(timestamp)}
            </div>

            <div className="flex items-center gap-2">
              {/* Feedback */}
              {onFeedback && (
                <div className="flex items-center gap-1 mr-2">
                  <span className="text-xs text-[var(--color-muted-foreground)] mr-1">
                    Helpful?
                  </span>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => handleFeedback(true)}
                    className={cn(
                      'h-7 w-7',
                      feedbackGiven === true && 'text-emerald-500 bg-emerald-100 dark:bg-emerald-900/30'
                    )}
                    disabled={feedbackGiven !== null}
                  >
                    <ThumbsUp className="h-3.5 w-3.5" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => handleFeedback(false)}
                    className={cn(
                      'h-7 w-7',
                      feedbackGiven === false && 'text-rose-500 bg-rose-100 dark:bg-rose-900/30'
                    )}
                    disabled={feedbackGiven !== null}
                  >
                    <ThumbsDown className="h-3.5 w-3.5" />
                  </Button>
                </div>
              )}

              {/* Actions */}
              {actions && actions.map((action, index) => (
                <Button
                  key={index}
                  variant={action.primary ? 'default' : 'outline'}
                  size="sm"
                  onClick={action.onClick}
                >
                  {action.label}
                </Button>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }
);

AgentInsightCard.displayName = 'AgentInsightCard';

export default AgentInsightCard;
