"""Block 3B-M-4: Feast repository hygiene gates.

Lightweight non-execution-heavy checks that the Feast repository
checkout stays clean — no generated artefacts, no committed registries,
etc. These tests are deliberately separated from
``test_feast_apply_idempotent.py`` because they don't need the Feast
CLI, don't need Postgres/Redis, and don't need to run a feast subcommand
at all. Keeping them apart lets the heavier idempotency tests skip
cleanly when Feast is unavailable while these hygiene gates still run.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def test_registry_db_not_tracked_in_git() -> None:
    """The generated registry must not be tracked in git.

    Block 3B residual finding #4: ``feature_repo/data/registry.db`` is
    regenerated by ``feast apply`` and committing it would create churn
    and desync from the Python source of truth.

    Block 3B-M-1: the gitignore now globs ``feature_repo/data/registry.*``
    so this test should also stay green if the registry backend ever
    swaps from SQLite to a JSON / proto-encoded file.
    """
    result = subprocess.run(
        ["git", "ls-files", "feature_repo/data/registry.db"],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        check=False,
        timeout=10,
    )
    if result.returncode != 0:
        pytest.skip(f"`git ls-files` not usable here: {result.stderr.strip()[:200]}")
    assert result.stdout.strip() == "", (
        "feature_repo/data/registry.db is tracked in git. "
        "It must be regenerated by `feast apply`, not committed. "
        f"git ls-files output: {result.stdout!r}"
    )


def test_registry_glob_not_tracked_in_git() -> None:
    """3B-M-1 follow-on: ANY ``feature_repo/data/registry.*`` file
    matching the gitignore glob must not be tracked. This guards against
    a future registry-format swap that the explicit ``.db`` test would
    miss."""
    result = subprocess.run(
        ["git", "ls-files", "feature_repo/data/"],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        check=False,
        timeout=10,
    )
    if result.returncode != 0:
        pytest.skip(f"`git ls-files` not usable here: {result.stderr.strip()[:200]}")
    tracked_registry_files = [
        line for line in result.stdout.strip().splitlines() if "/registry." in line
    ]
    assert not tracked_registry_files, (
        "Found tracked feature_repo/data/registry.* files: "
        f"{tracked_registry_files}. The gitignore glob should keep these "
        f"out of version control."
    )
