-- ============================================================================
-- E2I Causal Analytics - Migration ml/037_tool_registry_schema_sync.sql
-- tool-registry-schema-sync (#2003)
-- ============================================================================
--
-- GENERATED by scripts/generate_tool_registry_sync_migration.py from the live tool
-- registry. Do not hand-edit: when a tool's declared inputs or output model change,
-- regenerate into the NEXT migration number (the drift test in
-- tests/unit/test_agents/test_tool_composer/test_registry_schema_drift_2003.py reads
-- the newest migration carrying the marker above).
--
-- The tool_registry input/output JSON Schemas and the tool_dependencies field
-- mappings seeded by ml/013 and ml/027 were written once and drifted from the
-- registered tools (e.g. sensitivity_analyzer declared causal_result/gamma_range in,
-- e_value/robustness_value out). This UPDATEs every seeded row to the registry's
-- description, input schema and output schema, and every seeded dependency to the
-- real producer output field / consumer input field. It raises if a seeded row is
-- missing, so a partial sync cannot pass silently. Idempotent: re-applying writes
-- the same values.
-- ============================================================================

DO $sync$
DECLARE
    v_expected integer;
    v_updated integer;
BEGIN
    WITH payload AS (
        SELECT *
        FROM jsonb_to_recordset($tool_registry_sync$
[
  {
    "name": "cate_analyzer",
    "description": "Estimate conditional average treatment effects (CATE) by segment using CausalML",
    "input_schema": {
      "type": "object",
      "properties": {
        "treatment": {
          "type": "string",
          "description": "Treatment variable"
        },
        "outcome": {
          "type": "string",
          "description": "Outcome variable"
        },
        "segments": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Segmentation variables"
        }
      },
      "required": [
        "treatment",
        "outcome",
        "segments"
      ]
    },
    "output_schema": {
      "description": "Output from CATE analysis.\n\n``segments`` and ``effect_by_segment`` carry ONLY the segments whose CATE was\nactually measured — every value in them is a finite float (#1610). A segment\nthat could not produce one moves to ``excluded_segments`` instead of entering\nthe numeric results as ``NaN``: a ``NaN`` there is not JSON-compliant for a\nstrict consumer (``json.dumps(allow_nan=False)`` raises) and renders as a\nplausible-looking blank in synthesis. Same reasoning as ``GapAnalysis``'s\nfinite ``entity_values`` (#1599).\n\nEach ``excluded_segments`` entry is ``{\"name\", \"n\", \"reason\", \"detail\"}``.\n``reason`` is one of the ``_CATE_EXCLUDED_*`` codes (stable, for consumers to\nbranch on), ``detail`` is the prose for synthesis to disclose, and ``name`` is\n``None`` for the null-key group — the rows whose segment value is missing name\nno segment, so there is no honest label to give them.",
      "properties": {
        "segments": {
          "items": {
            "additionalProperties": true,
            "type": "object"
          },
          "title": "Segments",
          "type": "array"
        },
        "high_responders": {
          "items": {
            "type": "string"
          },
          "title": "High Responders",
          "type": "array"
        },
        "effect_by_segment": {
          "additionalProperties": {
            "type": "number"
          },
          "title": "Effect By Segment",
          "type": "object"
        },
        "excluded_segments": {
          "items": {
            "additionalProperties": true,
            "type": "object"
          },
          "title": "Excluded Segments",
          "type": "array"
        }
      },
      "required": [
        "segments",
        "high_responders",
        "effect_by_segment"
      ],
      "title": "CATEResults",
      "type": "object"
    }
  },
  {
    "name": "causal_effect_estimator",
    "description": "Estimate average treatment effect (ATE/ATT) using DoWhy/EconML with confidence intervals",
    "input_schema": {
      "type": "object",
      "properties": {
        "treatment": {
          "type": "string",
          "description": "Treatment variable name"
        },
        "outcome": {
          "type": "string",
          "description": "Outcome variable name"
        },
        "confounders": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Confounder variables"
        },
        "method": {
          "type": "string",
          "description": "Estimation method"
        }
      },
      "required": [
        "treatment",
        "outcome"
      ]
    },
    "output_schema": {
      "description": "Output from causal effect estimation",
      "properties": {
        "ate": {
          "title": "Ate",
          "type": "number"
        },
        "ci_lower": {
          "title": "Ci Lower",
          "type": "number"
        },
        "ci_upper": {
          "title": "Ci Upper",
          "type": "number"
        },
        "p_value": {
          "title": "P Value",
          "type": "number"
        },
        "method": {
          "title": "Method",
          "type": "string"
        },
        "n_samples": {
          "title": "N Samples",
          "type": "integer"
        }
      },
      "required": [
        "ate",
        "ci_lower",
        "ci_upper",
        "p_value",
        "method",
        "n_samples"
      ],
      "title": "EffectEstimate",
      "type": "object"
    }
  },
  {
    "name": "counterfactual_simulator",
    "description": "Simulate intervention outcomes using the causal model",
    "input_schema": {
      "type": "object",
      "properties": {
        "intervention": {
          "type": "string",
          "description": "Intervention to simulate"
        },
        "target_entities": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Entities to apply intervention to"
        },
        "expected_effect": {
          "type": "number",
          "description": "Expected effect from prior analysis"
        }
      },
      "required": [
        "intervention",
        "target_entities",
        "expected_effect"
      ]
    },
    "output_schema": {
      "description": "Output from counterfactual simulation",
      "properties": {
        "predicted_lift": {
          "title": "Predicted Lift",
          "type": "number"
        },
        "confidence": {
          "title": "Confidence",
          "type": "string"
        },
        "uncertainty_range": {
          "items": {
            "type": "number"
          },
          "title": "Uncertainty Range",
          "type": "array"
        }
      },
      "required": [
        "predicted_lift",
        "confidence",
        "uncertainty_range"
      ],
      "title": "SimulationResults",
      "type": "object"
    }
  },
  {
    "name": "detect_structural_drift",
    "description": "Detect drift in causal DAG structure over time by comparing baseline and current period DAGs. Returns drift score, severity, added/removed edges, and recommendations for addressing structural changes.",
    "input_schema": {
      "type": "object",
      "properties": {
        "baseline_dag_adjacency": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "description": "Baseline DAG as binary adjacency matrix"
        },
        "current_dag_adjacency": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "description": "Current DAG as binary adjacency matrix"
        },
        "dag_nodes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Node names in adjacency matrix order"
        },
        "baseline_edge_types": {
          "type": "object",
          "description": "Edge types for baseline DAG (optional)"
        },
        "current_edge_types": {
          "type": "object",
          "description": "Edge types for current DAG (optional)"
        }
      },
      "required": [
        "baseline_dag_adjacency",
        "current_dag_adjacency",
        "dag_nodes"
      ]
    },
    "output_schema": {
      "$defs": {
        "EdgeTypeChange": {
          "description": "Details about an edge type change.",
          "properties": {
            "edge": {
              "description": "Edge as 'source->target'",
              "title": "Edge",
              "type": "string"
            },
            "baseline_type": {
              "description": "Edge type in baseline DAG",
              "title": "Baseline Type",
              "type": "string"
            },
            "current_type": {
              "description": "Edge type in current DAG",
              "title": "Current Type",
              "type": "string"
            }
          },
          "required": [
            "edge",
            "baseline_type",
            "current_type"
          ],
          "title": "EdgeTypeChange",
          "type": "object"
        }
      },
      "description": "Output schema for detect_structural_drift tool.",
      "properties": {
        "success": {
          "description": "Whether detection succeeded",
          "title": "Success",
          "type": "boolean"
        },
        "detected": {
          "default": false,
          "description": "Whether structural drift was detected",
          "title": "Detected",
          "type": "boolean"
        },
        "drift_score": {
          "default": 0.0,
          "description": "Proportion of edges changed (0-1)",
          "title": "Drift Score",
          "type": "number"
        },
        "severity": {
          "default": "none",
          "description": "Drift severity: 'critical', 'high', 'medium', 'low', 'none'",
          "title": "Severity",
          "type": "string"
        },
        "added_edges": {
          "description": "Edges added in current DAG (format: 'source->target')",
          "items": {
            "type": "string"
          },
          "title": "Added Edges",
          "type": "array"
        },
        "removed_edges": {
          "description": "Edges removed from baseline DAG",
          "items": {
            "type": "string"
          },
          "title": "Removed Edges",
          "type": "array"
        },
        "stable_edges": {
          "description": "Edges present in both DAGs",
          "items": {
            "type": "string"
          },
          "title": "Stable Edges",
          "type": "array"
        },
        "edge_type_changes": {
          "description": "Edges with changed types (e.g., DIRECTED->BIDIRECTED)",
          "items": {
            "$ref": "#/$defs/EdgeTypeChange"
          },
          "title": "Edge Type Changes",
          "type": "array"
        },
        "recommendation": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Recommendation based on drift analysis",
          "title": "Recommendation"
        },
        "critical_path_broken": {
          "default": false,
          "description": "Whether a critical causal path was broken",
          "title": "Critical Path Broken",
          "type": "boolean"
        },
        "timestamp": {
          "description": "Detection timestamp (ISO format)",
          "title": "Timestamp",
          "type": "string"
        },
        "trace_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Opik trace ID for this detection",
          "title": "Trace Id"
        },
        "errors": {
          "description": "Any errors encountered during detection",
          "items": {
            "type": "string"
          },
          "title": "Errors",
          "type": "array"
        }
      },
      "required": [
        "success",
        "timestamp"
      ],
      "title": "StructuralDriftOutput",
      "type": "object"
    }
  },
  {
    "name": "discover_dag",
    "description": "Discover causal DAG structure from observational data using ensemble algorithms (GES, PC, etc.). Returns edges with confidence scores and gate evaluation for determining result quality.",
    "input_schema": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object",
          "description": "Data as dict of column names to values (optional; the in-context DataFrame is used when omitted)"
        },
        "algorithms": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Algorithms: 'ges', 'pc', 'fci', 'lingam'",
          "default": [
            "ges",
            "pc"
          ]
        },
        "ensemble_threshold": {
          "type": "number",
          "description": "Min algorithm agreement (0-1)",
          "default": 0.5
        },
        "alpha": {
          "type": "number",
          "description": "Significance level for CI tests",
          "default": 0.05
        },
        "max_k": {
          "type": "integer",
          "description": "Maximum conditioning set size (-1 for unlimited)"
        },
        "node_names": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Custom node names (defaults to column names)"
        }
      },
      "required": []
    },
    "output_schema": {
      "description": "Output schema for discover_dag tool.",
      "properties": {
        "success": {
          "description": "Whether discovery succeeded",
          "title": "Success",
          "type": "boolean"
        },
        "n_edges": {
          "default": 0,
          "description": "Number of edges discovered",
          "title": "N Edges",
          "type": "integer"
        },
        "n_nodes": {
          "default": 0,
          "description": "Number of nodes in the DAG",
          "title": "N Nodes",
          "type": "integer"
        },
        "edge_list": {
          "description": "List of edges with source, target, confidence, type",
          "items": {
            "additionalProperties": true,
            "type": "object"
          },
          "title": "Edge List",
          "type": "array"
        },
        "algorithms_used": {
          "description": "Algorithms that were successfully run",
          "items": {
            "type": "string"
          },
          "title": "Algorithms Used",
          "type": "array"
        },
        "algorithm_results": {
          "additionalProperties": {
            "additionalProperties": true,
            "type": "object"
          },
          "description": "Per-algorithm results with n_edges, runtime_seconds, converged",
          "title": "Algorithm Results",
          "type": "object"
        },
        "ensemble_threshold": {
          "description": "Threshold used for ensemble",
          "title": "Ensemble Threshold",
          "type": "number"
        },
        "gate_decision": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Gate evaluation: 'accept', 'review', 'reject', 'augment'",
          "title": "Gate Decision"
        },
        "gate_confidence": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Gate confidence score (0-1)",
          "title": "Gate Confidence"
        },
        "gate_reasons": {
          "description": "Reasons for gate decision",
          "items": {
            "type": "string"
          },
          "title": "Gate Reasons",
          "type": "array"
        },
        "total_runtime_seconds": {
          "default": 0.0,
          "description": "Total discovery runtime",
          "title": "Total Runtime Seconds",
          "type": "number"
        },
        "timestamp": {
          "description": "Discovery timestamp (ISO format)",
          "title": "Timestamp",
          "type": "string"
        },
        "trace_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Opik trace ID for this discovery",
          "title": "Trace Id"
        },
        "errors": {
          "description": "Any errors encountered during discovery",
          "items": {
            "type": "string"
          },
          "title": "Errors",
          "type": "array"
        }
      },
      "required": [
        "success",
        "ensemble_threshold",
        "timestamp"
      ],
      "title": "DiscoverDagOutput",
      "type": "object"
    }
  },
  {
    "name": "distribution_comparator",
    "description": "Compare feature distributions between time periods",
    "input_schema": {
      "type": "object",
      "properties": {
        "features": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Features to compare"
        },
        "period_1": {
          "type": "string",
          "description": "First time period"
        },
        "period_2": {
          "type": "string",
          "description": "Second time period"
        },
        "period_column": {
          "type": "string",
          "description": "Column holding the period labels",
          "default": "period"
        }
      },
      "required": [
        "features",
        "period_1",
        "period_2"
      ]
    },
    "output_schema": {
      "description": "Output from ``distribution_comparator``: one KS comparison per feature.",
      "properties": {
        "comparisons": {
          "items": {
            "additionalProperties": true,
            "type": "object"
          },
          "title": "Comparisons",
          "type": "array"
        },
        "overall_drift": {
          "title": "Overall Drift",
          "type": "boolean"
        }
      },
      "required": [
        "comparisons",
        "overall_drift"
      ],
      "title": "DistributionComparison",
      "type": "object"
    }
  },
  {
    "name": "gap_calculator",
    "description": "Calculate performance gaps between entities (regions, territories, brands)",
    "input_schema": {
      "type": "object",
      "properties": {
        "metric": {
          "type": "string",
          "description": "Metric to compare"
        },
        "entity_type": {
          "type": "string",
          "description": "Type of entity (region, territory, brand)"
        },
        "entities": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Entities to compare"
        },
        "group_by": {
          "type": "string",
          "description": "Column to group entities by (optional; otherwise resolved from entity_type)"
        }
      },
      "required": [
        "metric",
        "entity_type",
        "entities"
      ]
    },
    "output_schema": {
      "description": "Output from gap analysis",
      "properties": {
        "gap": {
          "title": "Gap",
          "type": "number"
        },
        "entity_values": {
          "additionalProperties": {
            "type": "number"
          },
          "title": "Entity Values",
          "type": "object"
        },
        "top_performer": {
          "title": "Top Performer",
          "type": "string"
        },
        "bottom_performer": {
          "title": "Bottom Performer",
          "type": "string"
        }
      },
      "required": [
        "gap",
        "entity_values",
        "top_performer",
        "bottom_performer"
      ],
      "title": "GapAnalysis",
      "type": "object"
    }
  },
  {
    "name": "power_calculator",
    "description": "Calculate required sample size for statistical power in A/B tests",
    "input_schema": {
      "type": "object",
      "properties": {
        "effect_size": {
          "type": "number",
          "description": "Expected effect size"
        },
        "alpha": {
          "type": "number",
          "description": "Significance level",
          "default": 0.05
        },
        "power": {
          "type": "number",
          "description": "Desired power",
          "default": 0.8
        }
      },
      "required": [
        "effect_size"
      ]
    },
    "output_schema": {
      "description": "Output from power analysis",
      "properties": {
        "required_n": {
          "title": "Required N",
          "type": "integer"
        },
        "actual_power": {
          "title": "Actual Power",
          "type": "number"
        },
        "detectable_effect": {
          "title": "Detectable Effect",
          "type": "number"
        }
      },
      "required": [
        "required_n",
        "actual_power",
        "detectable_effect"
      ],
      "title": "PowerAnalysis",
      "type": "object"
    }
  },
  {
    "name": "propensity_estimator",
    "description": "Estimate propensity scores for treatment assignment analysis",
    "input_schema": {
      "type": "object",
      "properties": {
        "treatment": {
          "type": "string",
          "description": "Treatment variable"
        },
        "covariates": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Covariate variables"
        }
      },
      "required": [
        "treatment",
        "covariates"
      ]
    },
    "output_schema": {
      "description": "Output from propensity estimation (real fitted scores from a DataFrame).",
      "properties": {
        "mean_propensity": {
          "title": "Mean Propensity",
          "type": "number"
        },
        "propensity_distribution": {
          "additionalProperties": {
            "type": "number"
          },
          "title": "Propensity Distribution",
          "type": "object"
        },
        "overlap_assessment": {
          "title": "Overlap Assessment",
          "type": "string"
        },
        "common_support": {
          "title": "Common Support",
          "type": "number"
        }
      },
      "required": [
        "mean_propensity",
        "propensity_distribution",
        "overlap_assessment",
        "common_support"
      ],
      "title": "PropensityScores",
      "type": "object"
    }
  },
  {
    "name": "psi_calculator",
    "description": "Calculate Population Stability Index for drift detection",
    "input_schema": {
      "type": "object",
      "properties": {
        "feature": {
          "type": "string",
          "description": "Feature to analyze"
        },
        "baseline_period": {
          "type": "string",
          "description": "Baseline time period"
        },
        "current_period": {
          "type": "string",
          "description": "Current time period"
        },
        "period_column": {
          "type": "string",
          "description": "Column holding the period labels",
          "default": "period"
        }
      },
      "required": [
        "feature",
        "baseline_period",
        "current_period"
      ]
    },
    "output_schema": {
      "description": "Output from ``psi_calculator``.",
      "properties": {
        "psi": {
          "title": "Psi",
          "type": "number"
        },
        "interpretation": {
          "title": "Interpretation",
          "type": "string"
        },
        "threshold": {
          "title": "Threshold",
          "type": "number"
        },
        "buckets": {
          "items": {
            "additionalProperties": true,
            "type": "object"
          },
          "title": "Buckets",
          "type": "array"
        }
      },
      "required": [
        "psi",
        "interpretation",
        "threshold",
        "buckets"
      ],
      "title": "DriftMetrics",
      "type": "object"
    }
  },
  {
    "name": "rank_drivers",
    "description": "Compare causal vs predictive feature importance. Uses DAG structure for causal importance and SHAP values for predictive importance. Identifies features that are causally important vs just correlated.",
    "input_schema": {
      "type": "object",
      "properties": {
        "dag_edge_list": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "DAG as list of {source, target} edges"
        },
        "target": {
          "type": "string",
          "description": "Target variable name"
        },
        "shap_values": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "description": "SHAP values matrix (n_samples x n_features; optional, derived from the in-context DataFrame unless given together with feature_names)"
        },
        "feature_names": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Feature names (optional; without shap_values, limits the features SHAP is derived for)"
        },
        "concordance_threshold": {
          "type": "integer",
          "description": "Max rank diff for concordant features",
          "default": 2
        },
        "importance_percentile": {
          "type": "number",
          "description": "Top percentile of features counted as important (0-1)",
          "default": 0.25
        }
      },
      "required": [
        "dag_edge_list",
        "target"
      ]
    },
    "output_schema": {
      "$defs": {
        "FeatureRankingItem": {
          "description": "Single feature ranking information.\n\nThe causal fields (``causal_rank``, ``rank_difference``, ``causal_score``) are\n``Optional``: they are ``None`` — not ``0`` — when no causal estimate exists\n(e.g. the predictive-only fallback when the DAG has no edges), so a missing\ncausal estimate is never mistaken for a real zero-effect value.",
          "properties": {
            "feature_name": {
              "title": "Feature Name",
              "type": "string"
            },
            "causal_rank": {
              "anyOf": [
                {
                  "type": "integer"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Causal Rank"
            },
            "predictive_rank": {
              "title": "Predictive Rank",
              "type": "integer"
            },
            "rank_difference": {
              "anyOf": [
                {
                  "type": "integer"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Rank Difference"
            },
            "causal_score": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Causal Score"
            },
            "predictive_score": {
              "title": "Predictive Score",
              "type": "number"
            },
            "is_direct_cause": {
              "title": "Is Direct Cause",
              "type": "boolean"
            },
            "path_length": {
              "anyOf": [
                {
                  "type": "integer"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Path Length"
            }
          },
          "required": [
            "feature_name",
            "predictive_rank",
            "predictive_score",
            "is_direct_cause",
            "path_length"
          ],
          "title": "FeatureRankingItem",
          "type": "object"
        }
      },
      "description": "Output schema for rank_drivers tool.",
      "properties": {
        "success": {
          "description": "Whether ranking succeeded",
          "title": "Success",
          "type": "boolean"
        },
        "target_variable": {
          "description": "Target variable used",
          "title": "Target Variable",
          "type": "string"
        },
        "rankings": {
          "description": "Feature rankings sorted by causal importance",
          "items": {
            "$ref": "#/$defs/FeatureRankingItem"
          },
          "title": "Rankings",
          "type": "array"
        },
        "n_features": {
          "default": 0,
          "description": "Number of features ranked",
          "title": "N Features",
          "type": "integer"
        },
        "rank_correlation": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Spearman correlation between causal and predictive ranks; None when no causal ranking exists (e.g. predictive-only fallback)",
          "title": "Rank Correlation"
        },
        "causal_only_features": {
          "description": "Features important causally but not predictively",
          "items": {
            "type": "string"
          },
          "title": "Causal Only Features",
          "type": "array"
        },
        "predictive_only_features": {
          "description": "Features important predictively but not causally",
          "items": {
            "type": "string"
          },
          "title": "Predictive Only Features",
          "type": "array"
        },
        "concordant_features": {
          "description": "Features with similar causal and predictive rankings",
          "items": {
            "type": "string"
          },
          "title": "Concordant Features",
          "type": "array"
        },
        "timestamp": {
          "description": "Ranking timestamp (ISO format)",
          "title": "Timestamp",
          "type": "string"
        },
        "trace_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Opik trace ID for this ranking",
          "title": "Trace Id"
        },
        "errors": {
          "description": "Any errors encountered during ranking",
          "items": {
            "type": "string"
          },
          "title": "Errors",
          "type": "array"
        }
      },
      "required": [
        "success",
        "target_variable",
        "timestamp"
      ],
      "title": "RankDriversOutput",
      "type": "object"
    }
  },
  {
    "name": "refutation_runner",
    "description": "Run DoWhy refutation test suite (placebo, random cause, subset, bootstrap, sensitivity)",
    "input_schema": {
      "type": "object",
      "properties": {
        "estimate_id": {
          "type": "string",
          "description": "ID of the causal estimate to refute (echoed back for provenance)"
        },
        "treatment": {
          "type": "string",
          "description": "Treatment column the refutation suite re-estimates on"
        },
        "outcome": {
          "type": "string",
          "description": "Outcome column the refutation suite re-estimates on"
        },
        "confounders": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Confounder columns (use the ones the estimate adjusted for)"
        }
      },
      "required": [
        "estimate_id",
        "treatment",
        "outcome"
      ]
    },
    "output_schema": {
      "description": "Output from ``refutation_runner``: the DoWhy refutation suite and its summary.\n\nThe summary fields are read from the suite with ``.get`` and stay optional.",
      "properties": {
        "estimate_id": {
          "title": "Estimate Id",
          "type": "string"
        },
        "treatment": {
          "title": "Treatment",
          "type": "string"
        },
        "outcome": {
          "title": "Outcome",
          "type": "string"
        },
        "n_samples": {
          "title": "N Samples",
          "type": "integer"
        },
        "refutation_results": {
          "additionalProperties": true,
          "title": "Refutation Results",
          "type": "object"
        },
        "gate_decision": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Gate Decision"
        },
        "overall_robust": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ],
          "title": "Overall Robust"
        },
        "tests_passed": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "title": "Tests Passed"
        },
        "tests_failed": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "title": "Tests Failed"
        },
        "total_tests": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "title": "Total Tests"
        },
        "needs_review": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ],
          "title": "Needs Review"
        }
      },
      "required": [
        "estimate_id",
        "treatment",
        "outcome",
        "n_samples",
        "refutation_results",
        "gate_decision",
        "overall_robust",
        "tests_passed",
        "tests_failed",
        "total_tests",
        "needs_review"
      ],
      "title": "RefutationResults",
      "type": "object"
    }
  },
  {
    "name": "risk_scorer",
    "description": "Score entities by risk/propensity using ensemble ML models",
    "input_schema": {
      "type": "object",
      "properties": {
        "entity_type": {
          "type": "string",
          "description": "Type of entity to score"
        },
        "risk_type": {
          "type": "string",
          "description": "Type of risk (churn, discontinuation, etc.)"
        },
        "entity_ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Entity IDs to score"
        },
        "id_column": {
          "type": "string",
          "description": "Column holding the entity IDs",
          "default": "patient_id"
        },
        "outcome": {
          "type": "string",
          "description": "Binary outcome column the risk model predicts (the risk event)",
          "default": "discontinuation_flag"
        }
      },
      "required": [
        "entity_type",
        "risk_type"
      ]
    },
    "output_schema": {
      "description": "Output from risk scoring (real per-entity scores from a DataFrame).",
      "properties": {
        "scores": {
          "items": {
            "additionalProperties": true,
            "type": "object"
          },
          "title": "Scores",
          "type": "array"
        },
        "model_version": {
          "title": "Model Version",
          "type": "string"
        },
        "scored_at": {
          "title": "Scored At",
          "type": "string"
        }
      },
      "required": [
        "scores",
        "model_version",
        "scored_at"
      ],
      "title": "RiskScores",
      "type": "object"
    }
  },
  {
    "name": "roi_estimator",
    "description": "Estimate ROI of closing identified performance gaps",
    "input_schema": {
      "type": "object",
      "properties": {
        "gap_analysis": {
          "type": "object",
          "description": "Gap analysis results"
        },
        "investment": {
          "type": "number",
          "description": "Proposed investment amount"
        },
        "value_per_unit": {
          "type": "number",
          "description": "Value of one unit of the gap metric (optional; default 1.0)",
          "default": 1.0
        }
      },
      "required": [
        "gap_analysis",
        "investment"
      ]
    },
    "output_schema": {
      "description": "Output from ROI estimation (consumes a gap-analysis result).\n\n``sensitivity_band`` is a leave-one-out sensitivity band over the entity\nvalues the gap was derived from -- NOT a sampling confidence interval\n(renamed from ``confidence_interval`` in issue #1526; the identically named\nfield on ``gap_analyzer``'s ``ROIEstimate`` genuinely is a bootstrap CI).",
      "properties": {
        "estimated_roi": {
          "title": "Estimated Roi",
          "type": "number"
        },
        "payback_months": {
          "title": "Payback Months",
          "type": "number"
        },
        "sensitivity_band": {
          "items": {
            "type": "number"
          },
          "title": "Sensitivity Band",
          "type": "array"
        },
        "assumptions": {
          "items": {
            "type": "string"
          },
          "title": "Assumptions",
          "type": "array"
        }
      },
      "required": [
        "estimated_roi",
        "payback_months",
        "sensitivity_band",
        "assumptions"
      ],
      "title": "ROIEstimate",
      "type": "object"
    }
  },
  {
    "name": "segment_ranker",
    "description": "Rank segments by treatment effect magnitude and ROI potential",
    "input_schema": {
      "type": "object",
      "properties": {
        "cate_results": {
          "type": "object",
          "description": "Results from CATE analysis"
        }
      },
      "required": [
        "cate_results"
      ]
    },
    "output_schema": {
      "description": "Output from segment ranking (consumes a CATE / gap result).",
      "properties": {
        "ranking": {
          "items": {
            "additionalProperties": true,
            "type": "object"
          },
          "title": "Ranking",
          "type": "array"
        },
        "recommended_targets": {
          "items": {
            "type": "string"
          },
          "title": "Recommended Targets",
          "type": "array"
        }
      },
      "required": [
        "ranking",
        "recommended_targets"
      ],
      "title": "SegmentRanking",
      "type": "object"
    }
  },
  {
    "name": "sensitivity_analyzer",
    "description": "Compute VanderWeele-Ding E-values and, when a naive contrast is given, the measured-confounding reading (beyond / within / null finding) the refutation gate uses",
    "input_schema": {
      "type": "object",
      "properties": {
        "ate": {
          "type": "number",
          "description": "Estimated average treatment effect"
        },
        "ci_lower": {
          "type": "number",
          "description": "Lower confidence bound"
        },
        "ci_upper": {
          "type": "number",
          "description": "Upper confidence bound (optional; defaults to ate + (ate - ci_lower))"
        },
        "baseline_risk": {
          "type": "number",
          "description": "Control-arm outcome rate for a binary outcome (optional; enables the risk-ratio path)"
        },
        "naive_ate": {
          "type": "number",
          "description": "Unadjusted difference in means (optional; enables the measured-confounding benchmark)"
        }
      },
      "required": [
        "ate",
        "ci_lower"
      ]
    },
    "output_schema": {
      "description": "Output from ``sensitivity_analyzer``: E-values and the shared ``evalue`` reading.",
      "properties": {
        "e_value_point": {
          "title": "E Value Point",
          "type": "number"
        },
        "e_value_ci": {
          "title": "E Value Ci",
          "type": "number"
        },
        "reading": {
          "title": "Reading",
          "type": "string"
        },
        "headline": {
          "title": "Headline",
          "type": "string"
        },
        "benchmark": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "title": "Benchmark"
        },
        "benchmark_basis": {
          "title": "Benchmark Basis",
          "type": "string"
        },
        "conversion": {
          "title": "Conversion",
          "type": "string"
        },
        "interpretation": {
          "title": "Interpretation",
          "type": "string"
        }
      },
      "required": [
        "e_value_point",
        "e_value_ci",
        "reading",
        "headline",
        "benchmark",
        "benchmark_basis",
        "conversion",
        "interpretation"
      ],
      "title": "SensitivityReport",
      "type": "object"
    }
  }
]
$tool_registry_sync$::jsonb)
            AS t(name text, description text, input_schema jsonb, output_schema jsonb)
    )
    UPDATE tool_registry tr
    SET description = p.description,
        input_schema = p.input_schema,
        output_schema = p.output_schema
    FROM payload p
    WHERE tr.name = p.name;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_expected := 16;
    IF v_updated <> v_expected THEN
        RAISE EXCEPTION 'tool_registry sync updated % of % seeded rows', v_updated, v_expected;
    END IF;

    WITH mapping AS (
        SELECT c.tool_id AS consumer_tool_id,
               p.tool_id AS producer_tool_id,
               m.output_field,
               m.input_field
        FROM jsonb_to_recordset($tool_dependencies_sync$
[
  {
    "consumer": "cate_analyzer",
    "producer": "causal_effect_estimator",
    "output_field": null,
    "input_field": null
  },
  {
    "consumer": "counterfactual_simulator",
    "producer": "cate_analyzer",
    "output_field": "high_responders",
    "input_field": "target_entities"
  },
  {
    "consumer": "counterfactual_simulator",
    "producer": "causal_effect_estimator",
    "output_field": "ate",
    "input_field": "expected_effect"
  },
  {
    "consumer": "counterfactual_simulator",
    "producer": "gap_calculator",
    "output_field": null,
    "input_field": null
  },
  {
    "consumer": "power_calculator",
    "producer": "cate_analyzer",
    "output_field": null,
    "input_field": null
  },
  {
    "consumer": "power_calculator",
    "producer": "causal_effect_estimator",
    "output_field": "ate",
    "input_field": "effect_size"
  },
  {
    "consumer": "rank_drivers",
    "producer": "discover_dag",
    "output_field": "edge_list",
    "input_field": "dag_edge_list"
  },
  {
    "consumer": "refutation_runner",
    "producer": "causal_effect_estimator",
    "output_field": null,
    "input_field": null
  },
  {
    "consumer": "roi_estimator",
    "producer": "gap_calculator",
    "output_field": null,
    "input_field": "gap_analysis"
  },
  {
    "consumer": "segment_ranker",
    "producer": "cate_analyzer",
    "output_field": null,
    "input_field": "cate_results"
  },
  {
    "consumer": "sensitivity_analyzer",
    "producer": "causal_effect_estimator",
    "output_field": null,
    "input_field": null
  }
]
$tool_dependencies_sync$::jsonb)
            AS m(consumer text, producer text, output_field text, input_field text)
        JOIN tool_registry c ON c.name = m.consumer
        JOIN tool_registry p ON p.name = m.producer
    )
    UPDATE tool_dependencies d
    SET output_field = mapping.output_field,
        input_field = mapping.input_field
    FROM mapping
    WHERE d.consumer_tool_id = mapping.consumer_tool_id
      AND d.producer_tool_id = mapping.producer_tool_id;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_expected := 11;
    IF v_updated <> v_expected THEN
        RAISE EXCEPTION 'tool_dependencies sync updated % of % seeded rows', v_updated, v_expected;
    END IF;
END $sync$;
