-- ============================================================================
-- Migration 066 (M4): default-exclude synthetic rows from the kpi_query RPC
-- (synthetic-causal-validation). Clients pass only query_id -> the predicate
-- MUST live in the server-side statement. Each taggable FROM/JOIN <t> is
-- wrapped as (SELECT * FROM <t> WHERE is_synthetic = false) <alias> (alias-
-- preserving, so qualified/unqualified column refs keep resolving). A parallel
-- *_include_synthetic family (verbatim originals) is added for validation runs.
-- Auto-generated from the live registry; 36 taggable statements.
-- Idempotent (ON CONFLICT DO UPDATE). Depends on: 063 (M1 is_synthetic cols).
-- ----------------------------------------------------------------------------
INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    ('brand_specific_fabhalta_pnh_tested', $kpi$WITH eligible AS (SELECT DISTINCT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE brand::text = 'Fabhalta' AND primary_diagnosis_code = 'D59.5') SELECT COUNT(*) FILTER (WHERE EXISTS (SELECT 1 FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) te WHERE te.patient_id = e.patient_id AND te.event_subtype = 'pnh_flow_cytometry' AND te.loinc_codes && ARRAY['55164-8','35468-8','90735-2','44007-3']))::float / NULLIF(COUNT(*), 0) AS tested_rate FROM eligible e$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('brand_specific_kisqali_dx_adoption', $kpi$WITH first_kisqali AS (SELECT te.patient_id, MIN(te.event_date) AS first_rx_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) te WHERE te.brand::text = 'Kisqali' AND te.event_type::text = 'prescription' GROUP BY te.patient_id) SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (fk.first_rx_date - pj.journey_start_date)) AS median_days FROM first_kisqali fk INNER JOIN (SELECT * FROM patient_journeys WHERE is_synthetic = false) pj ON pj.patient_id = fk.patient_id WHERE pj.journey_start_date IS NOT NULL AND fk.first_rx_date >= pj.journey_start_date$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('brand_specific_kisqali_oncologist_reach', $kpi$WITH oncologists AS (SELECT COUNT(DISTINCT hcp_id) AS total FROM (SELECT * FROM hcp_profiles WHERE is_synthetic = false) hcp_profiles WHERE specialty ILIKE '%oncolog%'), engaged AS (SELECT COUNT(DISTINCT t.hcp_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM hcp_profiles WHERE is_synthetic = false) hp ON hp.hcp_id = t.hcp_id WHERE hp.specialty ILIKE '%oncolog%' AND t.brand_id = 'Kisqali' AND t.trigger_timestamp >= NOW() - INTERVAL '90 days') SELECT engaged.total::float / NULLIF(oncologists.total, 0) AS reach FROM oncologists, engaged$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('brand_specific_remi_ah_uncontrolled', $kpi$WITH per_patient AS (SELECT patient_id, bool_or((lab_values->>'value')::numeric >= $1::numeric) AS uncontrolled FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE brand::text = 'Remibrutinib' AND event_subtype = 'baseline_antihistamine' AND drug_class = 'R06A' AND lab_values->>'assay' = 'UAS7' GROUP BY patient_id) SELECT COUNT(*) FILTER (WHERE uncontrolled)::float / NULLIF(COUNT(*), 0) AS uncontrolled_rate FROM per_patient$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('brand_specific_remi_intent_delta_fallback', $kpi$SELECT AVG(intent_to_prescribe_change) AS intent_delta FROM (SELECT * FROM hcp_intent_surveys WHERE is_synthetic = false) hcp_intent_surveys WHERE brand::text = 'Remibrutinib' AND survey_date >= NOW() - INTERVAL '90 days' AND intent_to_prescribe_change IS NOT NULL$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('business_impact_conversion_rate', $kpi$WITH triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= NOW() - INTERVAL '30 days' AND te.event_type::text = 'prescription' AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('business_impact_data_through', $kpi$SELECT max(event_date) AS data_through FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('business_impact_hcp_coverage', $kpi$SELECT COUNT(CASE WHEN coverage_status = true THEN 1 END)::float / NULLIF(COUNT(CASE WHEN priority_tier <= 2 THEN 1 END), 0) AS coverage FROM (SELECT * FROM hcp_profiles WHERE is_synthetic = false) hcp_profiles$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('business_impact_hcp_reach', $kpi$SELECT COUNT(DISTINCT hcp_id) AS hcp_reach FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1)$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('business_impact_mau_fallback', $kpi$SELECT COUNT(DISTINCT user_id) AS mau FROM (SELECT * FROM user_sessions WHERE is_synthetic = false) user_sessions WHERE session_start >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('business_impact_nbrx', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= NOW() - INTERVAL '30 days'$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('business_impact_nrx', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1)$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('business_impact_roi_agent_activities', $kpi$SELECT AVG(roi_estimate) AS avg_roi FROM (SELECT * FROM agent_activities WHERE is_synthetic = false) agent_activities WHERE activity_timestamp >= NOW() - INTERVAL '30 days' AND roi_estimate IS NOT NULL$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('business_impact_roi_business_metrics', $kpi$SELECT AVG(roi) AS avg_roi FROM (SELECT * FROM business_metrics WHERE is_synthetic = false) business_metrics WHERE metric_date >= NOW() - INTERVAL '30 days' AND roi IS NOT NULL$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('business_impact_trx', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1)$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('business_impact_trx_share', $kpi$WITH category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days'), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= NOW() - INTERVAL '30 days') SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('business_impact_wau_fallback', $kpi$SELECT COUNT(DISTINCT user_id) AS wau FROM (SELECT * FROM user_sessions WHERE is_synthetic = false) user_sessions WHERE session_start >= NOW() - INTERVAL '7 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('causal_metrics_ate', $kpi$SELECT AVG(treatment_effect_estimate) AS ate, STDDEV(treatment_effect_estimate) AS ate_std, COUNT(*) AS n_samples FROM (SELECT * FROM ml_predictions WHERE is_synthetic = false) ml_predictions WHERE treatment_effect_estimate IS NOT NULL AND prediction_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('causal_metrics_cate', $kpi$SELECT segment_assignment, AVG(heterogeneous_effect) AS cate, STDDEV(heterogeneous_effect) AS cate_std, COUNT(*) AS n_samples FROM (SELECT * FROM ml_predictions WHERE is_synthetic = false) ml_predictions WHERE heterogeneous_effect IS NOT NULL AND prediction_timestamp >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR segment_assignment = $1) GROUP BY segment_assignment ORDER BY AVG(heterogeneous_effect) DESC$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('causal_metrics_causal_impact', $kpi$SELECT start_node, AVG(causal_effect_size)::float AS effect, COUNT(*)::int AS n_paths, AVG(confidence_level)::float AS avg_confidence FROM (SELECT * FROM causal_paths WHERE is_synthetic = false) causal_paths WHERE causal_effect_size IS NOT NULL AND ($1 = '' OR validation_status::text = $1) GROUP BY start_node ORDER BY effect DESC$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('causal_metrics_counterfactual', $kpi$SELECT AVG(counterfactual_outcome)::float AS mean_counterfactual, AVG(prediction_value)::float AS mean_factual, AVG(prediction_value - counterfactual_outcome)::float AS mean_realized_contrast, AVG(treatment_effect_estimate)::float AS mean_effect, COUNT(*)::int AS n FROM (SELECT * FROM ml_predictions WHERE is_synthetic = false) ml_predictions WHERE counterfactual_outcome IS NOT NULL AND prediction_value IS NOT NULL AND treatment_effect_estimate IS NOT NULL AND ($1 = '' OR prediction_type::text = $1)$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('causal_metrics_mediation', $kpi$SELECT AVG(indirect_effect / NULLIF(causal_effect_size, 0))::float AS proportion_mediated, COUNT(*)::int AS n_paths, AVG(indirect_effect)::float AS mean_indirect, AVG(direct_effect)::float AS mean_direct FROM (SELECT * FROM causal_paths WHERE is_synthetic = false) causal_paths WHERE causal_effect_size > 0 AND indirect_effect IS NOT NULL AND direct_effect IS NOT NULL$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('data_quality_completeness_pass_rate', $kpi$SELECT AVG(CASE WHEN patient_id IS NOT NULL AND brand IS NOT NULL AND event_date IS NOT NULL THEN 1.0 ELSE 0.0 END) AS pass_rate FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE created_at >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('data_quality_geographic_consistency', $kpi$WITH src AS (SELECT geographic_region::text AS region, COUNT(*)::numeric AS n FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE geographic_region IS NOT NULL AND ($1::text IS NULL OR brand::text = $1) GROUP BY geographic_region), src_share AS (SELECT region, n / NULLIF(SUM(n) OVER (), 0) AS share FROM src), uni AS (SELECT region::text AS region, SUM(total_count)::numeric AS n FROM reference_universe WHERE universe_type = 'patient' AND ($1::text IS NULL OR brand::text = $1) GROUP BY region), uni_share AS (SELECT region, n / NULLIF(SUM(n) OVER (), 0) AS share FROM uni) SELECT MAX(ABS(COALESCE(s.share, 0) - COALESCE(u.share, 0))) AS max_gap FROM src_share s FULL OUTER JOIN uni_share u ON s.region = u.region$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('data_quality_source_coverage_hcps', $kpi$SELECT (SELECT COUNT(DISTINCT hcp_id) FROM (SELECT * FROM hcp_profiles WHERE is_synthetic = false) hcp_profiles WHERE coverage_status = true) AS covered, COALESCE((SELECT SUM(target_count) FROM reference_universe WHERE universe_type = 'hcp'), 0) AS total$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('data_quality_source_coverage_patients', $kpi$SELECT COUNT(DISTINCT pj.patient_id) AS covered, COALESCE((SELECT SUM(target_count) FROM reference_universe WHERE ($1::text IS NULL OR brand::text = $1)), 0) AS total FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) pj WHERE ($1::text IS NULL OR pj.brand::text = $1)$kpi$, 1, $note$M4: default-exclude synthetic$note$),
    ('model_performance_roc_auc', $kpi$SELECT AVG(model_auc)::float AS roc_auc FROM (SELECT * FROM ml_predictions WHERE is_synthetic = false) ml_predictions WHERE model_auc IS NOT NULL$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('model_performance_shap_coverage', $kpi$SELECT COUNT(CASE WHEN shap_values IS NOT NULL THEN 1 END)::float / NULLIF(COUNT(*), 0) AS coverage FROM (SELECT * FROM ml_predictions WHERE is_synthetic = false) ml_predictions WHERE created_at >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_acceptance_rate', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN acceptance_status IS NOT NULL THEN 1 END), 0) AS acceptance_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_action_rate_uplift', $kpi$WITH arms AS (SELECT control_group_flag, COUNT(*) FILTER (WHERE action_taken IS NOT NULL)::float / NULLIF(COUNT(*), 0) AS action_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE control_group_flag IS NOT NULL GROUP BY control_group_flag) SELECT (t.action_rate - c.action_rate) / NULLIF(c.action_rate, 0) AS action_rate_uplift, t.action_rate AS treatment_rate, c.action_rate AS control_rate FROM (SELECT action_rate FROM arms WHERE control_group_flag = false) t, (SELECT action_rate FROM arms WHERE control_group_flag = true) c$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_cfr', $kpi$SELECT COUNT(CASE WHEN change_failed THEN 1 END)::float / NULLIF(COUNT(CASE WHEN previous_trigger_id IS NOT NULL THEN 1 END), 0) AS cfr FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_false_alert_rate', $kpi$SELECT COUNT(CASE WHEN false_positive_flag THEN 1 END)::float / NULLIF(COUNT(*), 0) AS false_alert_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_lead_time', $kpi$SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_time_days) AS median_lead_time FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE lead_time_days IS NOT NULL AND trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_override_rate', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN acceptance_status IS NOT NULL THEN 1 END), 0) AS override_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_precision', $kpi$SELECT COUNT(CASE WHEN outcome_tracked AND outcome_value > 0 THEN 1 END)::float / NULLIF(COUNT(CASE WHEN outcome_tracked THEN 1 END), 0) AS precision FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4: default-exclude synthetic$note$),
    ('trigger_performance_recall', $kpi$WITH positive_outcomes AS (SELECT DISTINCT patient_id FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days'), trigger_preceded AS (SELECT DISTINCT po.patient_id FROM positive_outcomes po INNER JOIN (SELECT * FROM triggers WHERE is_synthetic = false) t ON t.patient_id = po.patient_id WHERE t.trigger_timestamp < (SELECT MIN(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) te WHERE te.patient_id = po.patient_id AND te.event_type::text = 'prescription')) SELECT COUNT(DISTINCT tp.patient_id)::float / NULLIF(COUNT(DISTINCT po.patient_id), 0) AS recall FROM positive_outcomes po LEFT JOIN trigger_preceded tp ON tp.patient_id = po.patient_id$kpi$, 0, $note$M4: default-exclude synthetic$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    ('brand_specific_fabhalta_pnh_tested_include_synthetic', $kpi$WITH eligible AS (SELECT DISTINCT patient_id FROM patient_journeys WHERE brand::text = 'Fabhalta' AND primary_diagnosis_code = 'D59.5') SELECT COUNT(*) FILTER (WHERE EXISTS (SELECT 1 FROM treatment_events te WHERE te.patient_id = e.patient_id AND te.event_subtype = 'pnh_flow_cytometry' AND te.loinc_codes && ARRAY['55164-8','35468-8','90735-2','44007-3']))::float / NULLIF(COUNT(*), 0) AS tested_rate FROM eligible e$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('brand_specific_kisqali_dx_adoption_include_synthetic', $kpi$WITH first_kisqali AS (SELECT te.patient_id, MIN(te.event_date) AS first_rx_date FROM treatment_events te WHERE te.brand::text = 'Kisqali' AND te.event_type::text = 'prescription' GROUP BY te.patient_id) SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (fk.first_rx_date - pj.journey_start_date)) AS median_days FROM first_kisqali fk INNER JOIN patient_journeys pj ON pj.patient_id = fk.patient_id WHERE pj.journey_start_date IS NOT NULL AND fk.first_rx_date >= pj.journey_start_date$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('brand_specific_kisqali_oncologist_reach_include_synthetic', $kpi$WITH oncologists AS (SELECT COUNT(DISTINCT hcp_id) AS total FROM hcp_profiles WHERE specialty ILIKE '%oncolog%'), engaged AS (SELECT COUNT(DISTINCT t.hcp_id) AS total FROM triggers t INNER JOIN hcp_profiles hp ON hp.hcp_id = t.hcp_id WHERE hp.specialty ILIKE '%oncolog%' AND t.brand_id = 'Kisqali' AND t.trigger_timestamp >= NOW() - INTERVAL '90 days') SELECT engaged.total::float / NULLIF(oncologists.total, 0) AS reach FROM oncologists, engaged$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('brand_specific_remi_ah_uncontrolled_include_synthetic', $kpi$WITH per_patient AS (SELECT patient_id, bool_or((lab_values->>'value')::numeric >= $1::numeric) AS uncontrolled FROM treatment_events WHERE brand::text = 'Remibrutinib' AND event_subtype = 'baseline_antihistamine' AND drug_class = 'R06A' AND lab_values->>'assay' = 'UAS7' GROUP BY patient_id) SELECT COUNT(*) FILTER (WHERE uncontrolled)::float / NULLIF(COUNT(*), 0) AS uncontrolled_rate FROM per_patient$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('brand_specific_remi_intent_delta_fallback_include_synthetic', $kpi$SELECT AVG(intent_to_prescribe_change) AS intent_delta FROM hcp_intent_surveys WHERE brand::text = 'Remibrutinib' AND survey_date >= NOW() - INTERVAL '90 days' AND intent_to_prescribe_change IS NOT NULL$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_conversion_rate_include_synthetic', $kpi$WITH triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= NOW() - INTERVAL '30 days' AND te.event_type::text = 'prescription' AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_data_through_include_synthetic', $kpi$SELECT max(event_date) AS data_through FROM treatment_events WHERE event_type::text = 'prescription'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_hcp_coverage_include_synthetic', $kpi$SELECT COUNT(CASE WHEN coverage_status = true THEN 1 END)::float / NULLIF(COUNT(CASE WHEN priority_tier <= 2 THEN 1 END), 0) AS coverage FROM hcp_profiles$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_hcp_reach_include_synthetic', $kpi$SELECT COUNT(DISTINCT hcp_id) AS hcp_reach FROM treatment_events WHERE event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1)$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_mau_fallback_include_synthetic', $kpi$SELECT COUNT(DISTINCT user_id) AS mau FROM user_sessions WHERE session_start >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_nbrx_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= NOW() - INTERVAL '30 days'$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_nrx_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1)$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_roi_agent_activities_include_synthetic', $kpi$SELECT AVG(roi_estimate) AS avg_roi FROM agent_activities WHERE activity_timestamp >= NOW() - INTERVAL '30 days' AND roi_estimate IS NOT NULL$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_roi_business_metrics_include_synthetic', $kpi$SELECT AVG(roi) AS avg_roi FROM business_metrics WHERE metric_date >= NOW() - INTERVAL '30 days' AND roi IS NOT NULL$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_trx_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1)$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_trx_share_include_synthetic', $kpi$WITH category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days'), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= NOW() - INTERVAL '30 days') SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('business_impact_wau_fallback_include_synthetic', $kpi$SELECT COUNT(DISTINCT user_id) AS wau FROM user_sessions WHERE session_start >= NOW() - INTERVAL '7 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('causal_metrics_ate_include_synthetic', $kpi$SELECT AVG(treatment_effect_estimate) AS ate, STDDEV(treatment_effect_estimate) AS ate_std, COUNT(*) AS n_samples FROM ml_predictions WHERE treatment_effect_estimate IS NOT NULL AND prediction_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('causal_metrics_cate_include_synthetic', $kpi$SELECT segment_assignment, AVG(heterogeneous_effect) AS cate, STDDEV(heterogeneous_effect) AS cate_std, COUNT(*) AS n_samples FROM ml_predictions WHERE heterogeneous_effect IS NOT NULL AND prediction_timestamp >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR segment_assignment = $1) GROUP BY segment_assignment ORDER BY AVG(heterogeneous_effect) DESC$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('causal_metrics_causal_impact_include_synthetic', $kpi$SELECT start_node, AVG(causal_effect_size)::float AS effect, COUNT(*)::int AS n_paths, AVG(confidence_level)::float AS avg_confidence FROM causal_paths WHERE causal_effect_size IS NOT NULL AND ($1 = '' OR validation_status::text = $1) GROUP BY start_node ORDER BY effect DESC$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('causal_metrics_counterfactual_include_synthetic', $kpi$SELECT AVG(counterfactual_outcome)::float AS mean_counterfactual, AVG(prediction_value)::float AS mean_factual, AVG(prediction_value - counterfactual_outcome)::float AS mean_realized_contrast, AVG(treatment_effect_estimate)::float AS mean_effect, COUNT(*)::int AS n FROM ml_predictions WHERE counterfactual_outcome IS NOT NULL AND prediction_value IS NOT NULL AND treatment_effect_estimate IS NOT NULL AND ($1 = '' OR prediction_type::text = $1)$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('causal_metrics_mediation_include_synthetic', $kpi$SELECT AVG(indirect_effect / NULLIF(causal_effect_size, 0))::float AS proportion_mediated, COUNT(*)::int AS n_paths, AVG(indirect_effect)::float AS mean_indirect, AVG(direct_effect)::float AS mean_direct FROM causal_paths WHERE causal_effect_size > 0 AND indirect_effect IS NOT NULL AND direct_effect IS NOT NULL$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('data_quality_completeness_pass_rate_include_synthetic', $kpi$SELECT AVG(CASE WHEN patient_id IS NOT NULL AND brand IS NOT NULL AND event_date IS NOT NULL THEN 1.0 ELSE 0.0 END) AS pass_rate FROM patient_journeys WHERE created_at >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('data_quality_geographic_consistency_include_synthetic', $kpi$WITH src AS (SELECT geographic_region::text AS region, COUNT(*)::numeric AS n FROM patient_journeys WHERE geographic_region IS NOT NULL AND ($1::text IS NULL OR brand::text = $1) GROUP BY geographic_region), src_share AS (SELECT region, n / NULLIF(SUM(n) OVER (), 0) AS share FROM src), uni AS (SELECT region::text AS region, SUM(total_count)::numeric AS n FROM reference_universe WHERE universe_type = 'patient' AND ($1::text IS NULL OR brand::text = $1) GROUP BY region), uni_share AS (SELECT region, n / NULLIF(SUM(n) OVER (), 0) AS share FROM uni) SELECT MAX(ABS(COALESCE(s.share, 0) - COALESCE(u.share, 0))) AS max_gap FROM src_share s FULL OUTER JOIN uni_share u ON s.region = u.region$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('data_quality_source_coverage_hcps_include_synthetic', $kpi$SELECT (SELECT COUNT(DISTINCT hcp_id) FROM hcp_profiles WHERE coverage_status = true) AS covered, COALESCE((SELECT SUM(target_count) FROM reference_universe WHERE universe_type = 'hcp'), 0) AS total$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('data_quality_source_coverage_patients_include_synthetic', $kpi$SELECT COUNT(DISTINCT pj.patient_id) AS covered, COALESCE((SELECT SUM(target_count) FROM reference_universe WHERE ($1::text IS NULL OR brand::text = $1)), 0) AS total FROM patient_journeys pj WHERE ($1::text IS NULL OR pj.brand::text = $1)$kpi$, 1, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('model_performance_roc_auc_include_synthetic', $kpi$SELECT AVG(model_auc)::float AS roc_auc FROM ml_predictions WHERE model_auc IS NOT NULL$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('model_performance_shap_coverage_include_synthetic', $kpi$SELECT COUNT(CASE WHEN shap_values IS NOT NULL THEN 1 END)::float / NULLIF(COUNT(*), 0) AS coverage FROM ml_predictions WHERE created_at >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_acceptance_rate_include_synthetic', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN acceptance_status IS NOT NULL THEN 1 END), 0) AS acceptance_rate FROM triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_action_rate_uplift_include_synthetic', $kpi$WITH arms AS (SELECT control_group_flag, COUNT(*) FILTER (WHERE action_taken IS NOT NULL)::float / NULLIF(COUNT(*), 0) AS action_rate FROM triggers WHERE control_group_flag IS NOT NULL GROUP BY control_group_flag) SELECT (t.action_rate - c.action_rate) / NULLIF(c.action_rate, 0) AS action_rate_uplift, t.action_rate AS treatment_rate, c.action_rate AS control_rate FROM (SELECT action_rate FROM arms WHERE control_group_flag = false) t, (SELECT action_rate FROM arms WHERE control_group_flag = true) c$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_cfr_include_synthetic', $kpi$SELECT COUNT(CASE WHEN change_failed THEN 1 END)::float / NULLIF(COUNT(CASE WHEN previous_trigger_id IS NOT NULL THEN 1 END), 0) AS cfr FROM triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_false_alert_rate_include_synthetic', $kpi$SELECT COUNT(CASE WHEN false_positive_flag THEN 1 END)::float / NULLIF(COUNT(*), 0) AS false_alert_rate FROM triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_lead_time_include_synthetic', $kpi$SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_time_days) AS median_lead_time FROM triggers WHERE lead_time_days IS NOT NULL AND trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_override_rate_include_synthetic', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN acceptance_status IS NOT NULL THEN 1 END), 0) AS override_rate FROM triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_precision_include_synthetic', $kpi$SELECT COUNT(CASE WHEN outcome_tracked AND outcome_value > 0 THEN 1 END)::float / NULLIF(COUNT(CASE WHEN outcome_tracked THEN 1 END), 0) AS precision FROM triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days'$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$),
    ('trigger_performance_recall_include_synthetic', $kpi$WITH positive_outcomes AS (SELECT DISTINCT patient_id FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days'), trigger_preceded AS (SELECT DISTINCT po.patient_id FROM positive_outcomes po INNER JOIN triggers t ON t.patient_id = po.patient_id WHERE t.trigger_timestamp < (SELECT MIN(event_date) FROM treatment_events te WHERE te.patient_id = po.patient_id AND te.event_type::text = 'prescription')) SELECT COUNT(DISTINCT tp.patient_id)::float / NULLIF(COUNT(DISTINCT po.patient_id), 0) AS recall FROM positive_outcomes po LEFT JOIN trigger_preceded tp ON tp.patient_id = po.patient_id$kpi$, 0, $note$M4 opt-in: INCLUDES synthetic (validation runs only)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;

NOTIFY pgrst, 'reload schema';
