-- ============================================================================
-- 077_kpi_region_variants.sql
-- Region-scoped variants of the business_impact KPI queries (Increment 1).
--
-- WHY ADDITIVE (not in-place): the kpi_query RPC strictly enforces
-- param_count == max_params, and these base queries feed the certified KPI
-- gates. Modifying them in-place (bumping max_params) would (a) risk a
-- transient RPC failure during deploy (old 1-param callers vs new 2-param
-- registry) and (b) touch vetted SQL. Instead we ADD parallel `*_region`
-- query ids that the calculator routes to ONLY when a region is selected;
-- the original queries stay byte-for-byte unchanged, so region=None behaves
-- exactly as today and the gates are unaffected.
--
-- Region source: treatment_events.patient_journey_id -> patient_journeys
-- .geographic_region (lowercase: 'northeast'/'south'/...); triggers.patient_id
-- -> patient_journeys for the conversion KPI. Region match is case-insensitive.
-- The synthetic-EXCLUDING variants wrap base tables in
-- (SELECT * ... WHERE is_synthetic=false); the *_include_synthetic variants
-- (used on the synthetic-gold showcase via resolve_kpi_query_id) do not.
--
-- Idempotent (ON CONFLICT DO UPDATE). Depends on: 044 (registry+RPC), 066 (twins).
-- ============================================================================

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    -- ---- TRx (brand=$1 optional, region=$2 required) ----
    ('business_impact_trx_region', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 2, $note$region-scoped TRx; region via patient_journeys.geographic_region$note$),
    ('business_impact_trx_region_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 2, $note$region-scoped TRx (includes synthetic)$note$),

    -- ---- NRx (brand=$1 optional, region=$2 required) ----
    ('business_impact_nrx_region', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 2, $note$region-scoped NRx$note$),
    ('business_impact_nrx_region_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 2, $note$region-scoped NRx (includes synthetic)$note$),

    -- ---- NBRx (brand=$1 optional, region=$2 required) ----
    ('business_impact_nbrx_region', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= NOW() - INTERVAL '30 days'$kpi$, 2, $note$region-scoped NBRx$note$),
    ('business_impact_nbrx_region_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= NOW() - INTERVAL '30 days'$kpi$, 2, $note$region-scoped NBRx (includes synthetic)$note$),

    -- ---- TRx Share (brand=$1 required, region=$2 required) — share within region ----
    ('business_impact_trx_share_region', $kpi$WITH region_patients AS (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)), category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days' AND patient_journey_id IN (SELECT patient_journey_id FROM region_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= NOW() - INTERVAL '30 days' AND patient_journey_id IN (SELECT patient_journey_id FROM region_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 2, $note$region-scoped TRx share$note$),
    ('business_impact_trx_share_region_include_synthetic', $kpi$WITH region_patients AS (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)), category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= NOW() - INTERVAL '30 days' AND patient_journey_id IN (SELECT patient_journey_id FROM region_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= NOW() - INTERVAL '30 days' AND patient_journey_id IN (SELECT patient_journey_id FROM region_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 2, $note$region-scoped TRx share (includes synthetic)$note$),

    -- ---- Conversion Rate (region=$1 required; no brand) — triggers->patient_journeys ----
    ('business_impact_conversion_rate_region', $kpi$WITH region_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($1)), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM region_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= NOW() - INTERVAL '30 days' AND t.patient_id IN (SELECT patient_id FROM region_patients) AND te.event_type::text = 'prescription' AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 1, $note$region-scoped conversion rate$note$),
    ('business_impact_conversion_rate_region_include_synthetic', $kpi$WITH region_patients AS (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($1)), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= NOW() - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM region_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= NOW() - INTERVAL '30 days' AND t.patient_id IN (SELECT patient_id FROM region_patients) AND te.event_type::text = 'prescription' AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 1, $note$region-scoped conversion rate (includes synthetic)$note$),

    -- ---- HCP Reach (brand=$1 optional, region=$2 required) — distinct HCPs in region ----
    ('business_impact_hcp_reach_region', $kpi$SELECT COUNT(DISTINCT hcp_id) AS hcp_reach FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 2, $note$region-scoped HCP reach$note$),
    ('business_impact_hcp_reach_region_include_synthetic', $kpi$SELECT COUNT(DISTINCT hcp_id) AS hcp_reach FROM treatment_events WHERE event_date >= NOW() - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 2, $note$region-scoped HCP reach (includes synthetic)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;
