-- ============================================================================
-- 084_kpi_windowed_variants.sql
-- Windowed variants of the clean event_date VOLUME KPI queries (NRx/TRx/NBRx),
-- for the "arbitrary KPI time window" feature.
--
-- WHY ADDITIVE (not in-place): the kpi_query RPC strictly enforces
-- param_count == max_params, and the base queries feed the certified KPI gates.
-- These ADD parallel `*_windowed[_region][_include_synthetic]` query ids that
-- the calculator routes to ONLY when a window is selected (see
-- BusinessImpactCalculator._resolve_windowed_call / windowed_query_id). The
-- original queries stay byte-for-byte unchanged, so the un-windowed path and
-- the gates are unaffected.
--
-- TRANSFORM: each variant is the corresponding base / region / synthetic
-- statement with its rolling `<col> >= NOW() - INTERVAL '30 days'` filter
-- replaced by an explicit positional window
-- `<col> >= $K::timestamptz AND <col> < $(K+1)::timestamptz`
-- (K = 2 no-region, 3 region). Param order:
--   no region:  [brand=$1, start=$2, end=$3]            (max_params 3)
--   region:     [brand=$1, region=$2, start=$3, end=$4] (max_params 4)
-- NBRx windows on the OUTER derived `first_date` (MIN(event_date) per patient),
-- the SAME column the base 30-day filter used, preserving "new-to-brand in
-- window" semantics. Region uses the patient_journeys.geographic_region join
-- (LOWER-case-insensitive), identical to migration 077. Synthetic-EXCLUDING
-- variants keep the `(SELECT * ... WHERE is_synthetic=false)` wrappers; the
-- `_include_synthetic` variants do not.
--
-- AUTO-GENERATED by scripts/gen_kpi_windowed_variants.py (do not hand-edit;
-- regenerate). The NRx `_windowed_include_synthetic` form was validated against
-- the live RPC (returned 3394 for a 90-day Kisqali read).
--
-- ROI (WS3-BI-010) is intentionally NOT windowed here: it is a two-source
-- fallback probe (business_metrics.metric_date / agent_activities
-- .activity_timestamp) with divergent timestamp columns and no single clean
-- windowed SQL -- deferred to a follow-up.
--
-- Idempotent (ON CONFLICT DO UPDATE). Depends on: 044 (registry+RPC), 066
-- (synthetic twins), 077 (region join pattern).
-- ============================================================================

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    ('business_impact_nrx_windowed', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $2::timestamptz AND event_date < $3::timestamptz AND ($1::text IS NULL OR brand::text = $1)$kpi$, 3, $note$windowed [brand, start, end]$note$),
    ('business_impact_nrx_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $2::timestamptz AND event_date < $3::timestamptz AND ($1::text IS NULL OR brand::text = $1)$kpi$, 3, $note$windowed [brand, start, end] (includes synthetic)$note$),
    ('business_impact_nrx_windowed_region', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 4, $note$windowed [brand, region, start, end]$note$),
    ('business_impact_nrx_windowed_region_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 4, $note$windowed [brand, region, start, end] (includes synthetic)$note$),
    ('business_impact_trx_windowed', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $2::timestamptz AND event_date < $3::timestamptz AND ($1::text IS NULL OR brand::text = $1)$kpi$, 3, $note$windowed [brand, start, end]$note$),
    ('business_impact_trx_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $2::timestamptz AND event_date < $3::timestamptz AND ($1::text IS NULL OR brand::text = $1)$kpi$, 3, $note$windowed [brand, start, end] (includes synthetic)$note$),
    ('business_impact_trx_windowed_region', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 4, $note$windowed [brand, region, start, end]$note$),
    ('business_impact_trx_windowed_region_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))$kpi$, 4, $note$windowed [brand, region, start, end] (includes synthetic)$note$),
    ('business_impact_nbrx_windowed', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $2::timestamptz AND first_date < $3::timestamptz$kpi$, 3, $note$windowed [brand, start, end]$note$),
    ('business_impact_nbrx_windowed_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $2::timestamptz AND first_date < $3::timestamptz$kpi$, 3, $note$windowed [brand, start, end] (includes synthetic)$note$),
    ('business_impact_nbrx_windowed_region', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$windowed [brand, region, start, end]$note$),
    ('business_impact_nbrx_windowed_region_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_journey_id IN (SELECT patient_journey_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$windowed [brand, region, start, end] (includes synthetic)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;

-- PostgREST caches the schema; reload so the new ids are visible.
NOTIFY pgrst, 'reload schema';
