-- ============================================================================
-- 105_kpi_segment_variants.sql
-- Patient-segment-scoped variants of the business_impact KPI queries:
--   severity tier (patient_journeys.segment_assignment) and
--   line-of-therapy (patient_journeys.prior_therapy_lines).
--
-- WHY ADDITIVE (not in-place): the kpi_query RPC strictly enforces
-- param_count == max_params, and these base queries feed the certified KPI
-- gates. Modifying them in-place (bumping max_params) would (a) risk a
-- transient RPC failure during deploy (old N-param callers vs new N+1-param
-- registry) and (b) touch vetted SQL. Instead we ADD parallel `*_segment` /
-- `*_line` query ids that the calculator routes to ONLY when a severity tier
-- or line-of-therapy is selected; the original queries stay byte-for-byte
-- unchanged, so the un-scoped path and the certified gates are unaffected.
-- Mirrors migration 077's region-variant pattern exactly (additive twin
-- families, same rationale).
--
-- SOURCE OF TRUTH: mirrored verbatim from the LIVE kpi_query_registry rows
-- (migration 089 rewrote the base queries to frontier-anchor + add a
-- `data_through` column + wrap tables in
-- `(SELECT * ... WHERE is_synthetic=false)`, so 044/077's on-disk SQL is
-- stale) -- not from any single migration file on disk. Each statement below
-- is the live source statement with ONE addition: an
-- `AND patient_id IN (SELECT patient_id FROM <PJ> WHERE
-- <axis_pred>)` clause spliced into the innermost WHERE that already filters
-- by brand (or, for TRx Share, into BOTH the `category` and `brand_rx` CTEs,
-- mirroring how `business_impact_trx_share_region` scopes both).
--
-- JOIN KEY = patient_id (NOT patient_journey_id). The region variants (mig
-- 077) join on treatment_events.patient_journey_id, but that FK is NULL on a
-- large share of prescription events -- ~17% of all prescriptions and ~45% of
-- NRx (sequence_number=1) events -- so a patient_journey_id join would
-- silently DROP ~44% of a brand's recent NRx and the severity/line buckets
-- would NOT sum to the head-line NRx (a coherence/honesty defect, verified
-- 2026-07-12). treatment_events.patient_id, by contrast, links 100% of
-- prescriptions to patient_journeys, and patient_journeys is 1:1 on patient_id
-- (25,018 rows / 25,018 distinct patient_id; zero patients carry >1
-- segment_assignment or >1 prior_therapy_lines), so a patient_id join is both
-- COMPLETE and UNAMBIGUOUS. (The NULL patient_journey_id on treatment_events
-- is a separate DGP linkage gap -- flagged for the Phase 2 generator PR, not
-- fixed here; the same latent gap makes the existing 077 region variants
-- under-count and should be reconciled there too.)
--
-- Segment source: patient_journeys.segment_assignment ('low_severity' /
-- 'medium_severity' / 'high_severity'), matched case-insensitively via
-- LOWER(...) = LOWER($2) (mirrors the region join's LOWER-case-insensitive
-- match). Line-of-therapy source: patient_journeys.prior_therapy_lines
-- (integer 0-3), matched via `prior_therapy_lines = $2::int`. The
-- synthetic-EXCLUDING variants wrap `patient_journeys` in
-- `(SELECT * ... WHERE is_synthetic=false)`; the `_include_synthetic` twins
-- (used on the synthetic-gold showcase via resolve_kpi_query_id /
-- segment_query_id / line_query_id) do not.
--
-- Param order (mirrors the existing `_region` / `_windowed_region`
-- ordering [brand, region, start, end]):
--   base:     [brand, axis_value]                    max_params = 2
--   windowed: [brand, axis_value, start, end]         max_params = 4
-- TRx Share has NO windowed variant (mirrors business_impact_trx_share,
-- which has never had a `_windowed` sibling).
--
-- An axis (segment/line) and a region are mutually exclusive in the
-- calculator (BusinessImpactCalculator._resolve_windowed_call): the 4-param
-- cap means we cannot combine axis + region in one statement. Segment takes
-- precedence over line-of-therapy when both are somehow supplied.
--
-- Exactly 28 new query ids:
--   severity base (max_params=2):     8  (trx/nrx/nbrx/trx_share x {plain, _include_synthetic})
--   severity windowed (max_params=4): 6  (trx/nrx/nbrx x {plain, _include_synthetic})
--   line base (max_params=2):         8  (trx/nrx/nbrx/trx_share x {plain, _include_synthetic})
--   line windowed (max_params=4):     6  (trx/nrx/nbrx x {plain, _include_synthetic})
--
-- VALIDATED (read-only, against the live DB, Remibrutinib, last-30d-from-
-- frontier, include_synthetic): with the patient_id join the severity buckets
-- PARTITION the head-line NRx exactly -- low 855 + medium 1752 + high 649 =
-- 3256 == unmodified business_impact_nrx_include_synthetic total, with ZERO
-- unmatched patients. This reproduces the plan's original POC split
-- (855/1752/649) exactly. Line-of-therapy likewise partitions with zero
-- residual. (An earlier draft joined on patient_journey_id and covered only
-- 1818/3256 = 56% of NRx -- the ~44% NULL-journey residual is what forced the
-- patient_id join documented above.)
--
-- Idempotent (ON CONFLICT DO UPDATE). Depends on: 044 (registry+RPC), 066
-- (synthetic twins), 077 (region/CTE-scoping pattern), 084 (windowed
-- pattern), 089 (frontier-anchored base statements this migration mirrors).
-- ============================================================================

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    -- ---- Severity tier (base) ----
    ('business_impact_trx_segment', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))) base$kpi$, 2, $note$severity-tier-scoped TRx$note$),
    ('business_impact_trx_segment_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))) base$kpi$, 2, $note$severity-tier-scoped TRx (includes synthetic)$note$),
    ('business_impact_nrx_segment', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))) base$kpi$, 2, $note$severity-tier-scoped NRx$note$),
    ('business_impact_nrx_segment_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))) base$kpi$, 2, $note$severity-tier-scoped NRx (includes synthetic)$note$),
    ('business_impact_nbrx_segment', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$severity-tier-scoped NBRx$note$),
    ('business_impact_nbrx_segment_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$severity-tier-scoped NBRx (includes synthetic)$note$),
    ('business_impact_trx_share_segment', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$severity-tier-scoped TRx share$note$),
    ('business_impact_trx_share_segment_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$severity-tier-scoped TRx share (includes synthetic)$note$),
    -- ---- Severity tier (windowed) ----
    ('business_impact_trx_segment_windowed', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))$kpi$, 4, $note$severity-tier-scoped TRx (windowed)$note$),
    ('business_impact_trx_segment_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))$kpi$, 4, $note$severity-tier-scoped TRx (windowed) (includes synthetic)$note$),
    ('business_impact_nrx_segment_windowed', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))$kpi$, 4, $note$severity-tier-scoped NRx (windowed)$note$),
    ('business_impact_nrx_segment_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2))$kpi$, 4, $note$severity-tier-scoped NRx (windowed) (includes synthetic)$note$),
    ('business_impact_nbrx_segment_windowed', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$severity-tier-scoped NBRx (windowed)$note$),
    ('business_impact_nbrx_segment_windowed_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$severity-tier-scoped NBRx (windowed) (includes synthetic)$note$),
    -- ---- Line-of-therapy (base) ----
    ('business_impact_trx_line', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int)) base$kpi$, 2, $note$line-of-therapy-scoped TRx$note$),
    ('business_impact_trx_line_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int)) base$kpi$, 2, $note$line-of-therapy-scoped TRx (includes synthetic)$note$),
    ('business_impact_nrx_line', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int)) base$kpi$, 2, $note$line-of-therapy-scoped NRx$note$),
    ('business_impact_nrx_line_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int)) base$kpi$, 2, $note$line-of-therapy-scoped NRx (includes synthetic)$note$),
    ('business_impact_nbrx_line', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$line-of-therapy-scoped NBRx$note$),
    ('business_impact_nbrx_line_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$line-of-therapy-scoped NBRx (includes synthetic)$note$),
    ('business_impact_trx_share_line', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int), category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$line-of-therapy-scoped TRx share$note$),
    ('business_impact_trx_share_line_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int), category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$line-of-therapy-scoped TRx share (includes synthetic)$note$),
    -- ---- Line-of-therapy (windowed) ----
    ('business_impact_trx_line_windowed', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int)$kpi$, 4, $note$line-of-therapy-scoped TRx (windowed)$note$),
    ('business_impact_trx_line_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int)$kpi$, 4, $note$line-of-therapy-scoped TRx (windowed) (includes synthetic)$note$),
    ('business_impact_nrx_line_windowed', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int)$kpi$, 4, $note$line-of-therapy-scoped NRx (windowed)$note$),
    ('business_impact_nrx_line_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int)$kpi$, 4, $note$line-of-therapy-scoped NRx (windowed) (includes synthetic)$note$),
    ('business_impact_nbrx_line_windowed', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$line-of-therapy-scoped NBRx (windowed)$note$),
    ('business_impact_nbrx_line_windowed_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$line-of-therapy-scoped NBRx (windowed) (includes synthetic)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;

-- PostgREST caches the schema; reload so the new ids are visible.
NOTIFY pgrst, 'reload schema';
