-- ============================================================================
-- Migration 108: biologic-status + IgE-tertile KPI query variants (Phase 2.5)
-- ============================================================================
-- Additive `kpi_query_registry` variants that break NRx/TRx/NBRx/TRx-share down
-- by two NEW patient axes made real in Phase 2 (migration 107 + backfill):
--   * biologic status  (patient_journeys.biologic_experienced -> 'naive'/'experienced')
--   * IgE tertile       (patient_journeys.ige_level -> data-driven low/medium/high)
--
-- FAITHFULNESS: both columns are populated ONLY for Remibrutinib rows (CSU); for
-- Kisqali/Fabhalta they are 100% NULL by design (clinical_codes.BRAND_ELIGIBILITY_FIELDS).
-- The `... IS NOT NULL AND ...` guard means an off-brand query matches zero
-- patients (honest empty); the calculator ALSO fails closed with an explicit
-- 'not available for <brand>' before it ever runs (business_impact
-- _guard_brand_scoped_axis), so a NULL brand never reads as a fabricated split.
--
-- IgE tertile cutpoints (105.21 / 208.50 IU/mL) are the EMPIRICAL p33/p66 of the
-- Remibrutinib ige_level distribution (n=8387, measured 2026-07-13) -- a
-- data-driven split, NOT a clinical threshold (Remibrutinib is a BTK inhibitor,
-- not anti-IgE, so IgE tiers are descriptive of the population, not drug-response).
--
-- Mechanically mirrors the migration-105 `_segment` family: same frontier-anchored
-- windows (MAX(event_date) - 30d, NOT NOW()), same patient_id join (NRx has NULL
-- patient_journey_id on ~45% of rows -- joining on patient_id links 100%), same
-- {real, _include_synthetic-twin} pairing, same 4-param cap. Only the predicate,
-- the query_id suffix (`_biologic` / `_ige_tier`), and the note differ.
--
-- Axis values: biologic in {'naive','experienced'}; ige_tier in {'low','medium','high'}.
-- An axis is mutually exclusive with region and the other axes (RPC 4-param cap).
--
-- Idempotent (ON CONFLICT DO UPDATE). Depends on: 044 (registry+RPC), 066
-- (synthetic twins), 077 (region pattern), 089 (frontier anchoring), 105 (the
-- `_segment`/`_line` family this mirrors), 107 (the biologic_experienced/ige_level
-- columns this reads).
-- ============================================================================

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    -- ---- Biologic status (base) ----
    ('business_impact_trx_biologic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)) base$kpi$, 2, $note$biologic-status-scoped TRx$note$),
    ('business_impact_trx_biologic_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)) base$kpi$, 2, $note$biologic-status-scoped TRx (includes synthetic)$note$),
    ('business_impact_nrx_biologic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)) base$kpi$, 2, $note$biologic-status-scoped NRx$note$),
    ('business_impact_nrx_biologic_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)) base$kpi$, 2, $note$biologic-status-scoped NRx (includes synthetic)$note$),
    ('business_impact_nbrx_biologic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$biologic-status-scoped NBRx$note$),
    ('business_impact_nbrx_biologic_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$biologic-status-scoped NBRx (includes synthetic)$note$),
    ('business_impact_trx_share_biologic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2), category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$biologic-status-scoped TRx share$note$),
    ('business_impact_trx_share_biologic_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2), category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$biologic-status-scoped TRx share (includes synthetic)$note$),
    -- ---- Biologic status (windowed) ----
    ('business_impact_trx_biologic_windowed', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)$kpi$, 4, $note$biologic-status-scoped TRx (windowed)$note$),
    ('business_impact_trx_biologic_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)$kpi$, 4, $note$biologic-status-scoped TRx (windowed) (includes synthetic)$note$),
    ('business_impact_nrx_biologic_windowed', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)$kpi$, 4, $note$biologic-status-scoped NRx (windowed)$note$),
    ('business_impact_nrx_biologic_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2)$kpi$, 4, $note$biologic-status-scoped NRx (windowed) (includes synthetic)$note$),
    ('business_impact_nbrx_biologic_windowed', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$biologic-status-scoped NBRx (windowed)$note$),
    ('business_impact_nbrx_biologic_windowed_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE biologic_experienced IS NOT NULL AND CASE WHEN biologic_experienced = 1 THEN 'experienced' ELSE 'naive' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$biologic-status-scoped NBRx (windowed) (includes synthetic)$note$),
    -- ---- IgE tertile (base) ----
    ('business_impact_trx_ige_tier', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)) base$kpi$, 2, $note$IgE-tier-scoped TRx$note$),
    ('business_impact_trx_ige_tier_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)) base$kpi$, 2, $note$IgE-tier-scoped TRx (includes synthetic)$note$),
    ('business_impact_nrx_ige_tier', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)) base$kpi$, 2, $note$IgE-tier-scoped NRx$note$),
    ('business_impact_nrx_ige_tier_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)) base$kpi$, 2, $note$IgE-tier-scoped NRx (includes synthetic)$note$),
    ('business_impact_nbrx_ige_tier', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$IgE-tier-scoped NBRx$note$),
    ('business_impact_nbrx_ige_tier_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days') base$kpi$, 2, $note$IgE-tier-scoped NBRx (includes synthetic)$note$),
    ('business_impact_trx_share_ige_tier', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2), category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$IgE-tier-scoped TRx share$note$),
    ('business_impact_trx_share_ige_tier_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription')::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2), category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx) base$kpi$, 2, $note$IgE-tier-scoped TRx share (includes synthetic)$note$),
    -- ---- IgE tertile (windowed) ----
    ('business_impact_trx_ige_tier_windowed', $kpi$SELECT COUNT(*) AS trx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)$kpi$, 4, $note$IgE-tier-scoped TRx (windowed)$note$),
    ('business_impact_trx_ige_tier_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS trx FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)$kpi$, 4, $note$IgE-tier-scoped TRx (windowed) (includes synthetic)$note$),
    ('business_impact_nrx_ige_tier_windowed', $kpi$SELECT COUNT(*) AS nrx FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)$kpi$, 4, $note$IgE-tier-scoped NRx (windowed)$note$),
    ('business_impact_nrx_ige_tier_windowed_include_synthetic', $kpi$SELECT COUNT(*) AS nrx FROM treatment_events WHERE event_type::text = 'prescription' AND sequence_number = 1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2)$kpi$, 4, $note$IgE-tier-scoped NRx (windowed) (includes synthetic)$note$),
    ('business_impact_nbrx_ige_tier_windowed', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$IgE-tier-scoped NBRx (windowed)$note$),
    ('business_impact_nbrx_ige_tier_windowed_include_synthetic', $kpi$WITH first_brand AS (SELECT patient_id, MIN(event_date) AS first_date FROM treatment_events WHERE event_type::text = 'prescription' AND ($1::text IS NULL OR brand::text = $1) AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE ige_level IS NOT NULL AND CASE WHEN ige_level < 105.21 THEN 'low' WHEN ige_level < 208.50 THEN 'medium' ELSE 'high' END = $2) GROUP BY patient_id) SELECT COUNT(*) AS nbrx FROM first_brand WHERE first_date >= $3::timestamptz AND first_date < $4::timestamptz$kpi$, 4, $note$IgE-tier-scoped NBRx (windowed) (includes synthetic)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;

-- PostgREST caches the schema; reload so the new ids are visible.
NOTIFY pgrst, 'reload schema';
