-- ============================================================================
-- 111_kpi_conversion_share_axis_window.sql
-- Brand / patient-axis / windowed variants for Conversion Rate (WS3-BI-009)
-- and windowed variants for TRx Share (WS3-BI-008).
--
-- WHY (chat session_1784387374342_joi2cuf): asked for "conversion rates for
-- Remibrutinib in each severity segment over the last year", the chatbot's
-- kpi_calculate_tool returned the SAME overall figure for all three segment
-- calls — `_calc_conversion_rate` honors only `region`, silently dropping
-- brand/segment/therapy_line/window (the response still echoed
-- brand=Remibrutinib, so a brand-agnostic portfolio number was presented as a
-- brand figure). The registry had no variants to route to: conversion_rate
-- existed only as base [] + `_region` [region]. TRx Share likewise had axis
-- variants (105/108) but no windowed forms, so "over the last year" could not
-- be honored for share either.
--
-- CONVERSION SEMANTICS (brand-scoped): a trigger belongs to a brand via
-- `triggers.brand_id` (populated on 100% of rows, ~12.5k per brand); it
-- CONVERTS when the SAME patient has a prescription of the SAME brand within
-- 30 days of the trigger. With $1 (brand) NULL the variants reduce to the
-- certified base semantics: all triggers, converting on ANY prescription.
-- Premise validated read-only against the live substrate before this file was
-- written: Remibrutinib last-365d same-brand conversion by severity tier =
-- high 0.678 (1069/1577), medium 0.601 (2961/4923), low 0.542 (1508/2780) —
-- differentiated, coherent, joins clean via patient_id (the migration-105
-- join-key rationale: patient_journeys is 1:1 on patient_id).
--
-- The trigger→Rx conversion horizon stays 30 days in EVERY variant (that is
-- the KPI's definition, `prescriptions_after_trigger`); the window params
-- bound WHICH TRIGGERS are counted (trigger_timestamp in [start, end)),
-- mirroring how 084's windowed volume variants bound event_date.
--
-- Frontier-anchored variants (no window params) keep the base query's window
-- — the most recent 30 days of trigger data ending at MAX(trigger_timestamp)
-- (migration 089 rationale: the substrate is calendar-fixed; NOW()-anchored
-- windows silently decay to empty) — and report `data_through`. Windowed
-- variants carry explicit bounds, so no data_through column (084 parity).
--
-- ADDITIVE (077/084/105/110 pattern): new parallel query ids only; the
-- certified base statements stay byte-for-byte unchanged. Plain ids wrap
-- synthetic-taggable tables in `(SELECT * FROM t WHERE is_synthetic = false)`;
-- `_include_synthetic` twins are the unwrapped originals
-- (src/kpi/synthetic_mode.py appends the suffix under the showcase flag).
--
-- Exactly 18 new query ids:
--   conversion_rate x {_brand [brand], _segment [brand,segment],
--     _line [brand,line], _windowed [brand,start,end],
--     _segment_windowed [brand,segment,start,end],
--     _line_windowed [brand,line,start,end]} x {plain, _include_synthetic}
--   trx_share x {_windowed [brand,start,end],
--     _segment_windowed [brand,segment,start,end],
--     _line_windowed [brand,line,start,end]} x {plain, _include_synthetic}
--
-- Idempotent (ON CONFLICT DO UPDATE). Depends on: 044 (registry+RPC),
-- 084 (windowed shapes), 089 (frontier anchoring), 105 (axis predicates).
-- ============================================================================

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    -- ---- Conversion Rate: brand-scoped (frontier 30d) ----
    ('business_impact_conversion_rate_brand', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers)::date AS data_through FROM (WITH triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id = $1)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR t.brand_id = $1) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted) base$kpi$, 1, $note$brand-scoped conversion rate (same-brand trigger->Rx, frontier 30d)$note$),
    ('business_impact_conversion_rate_brand_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM triggers)::date AS data_through FROM (WITH triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id = $1)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR t.brand_id = $1) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted) base$kpi$, 1, $note$brand-scoped conversion rate (same-brand trigger->Rx, frontier 30d; includes synthetic)$note$),
    -- ---- Conversion Rate by severity tier (frontier 30d) ----
    ('business_impact_conversion_rate_segment', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers)::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted) base$kpi$, 2, $note$conversion rate by severity tier (frontier 30d)$note$),
    ('business_impact_conversion_rate_segment_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM triggers)::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted) base$kpi$, 2, $note$conversion rate by severity tier (frontier 30d; includes synthetic)$note$),
    -- ---- Conversion Rate by line-of-therapy (frontier 30d) ----
    ('business_impact_conversion_rate_line', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers)::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted) base$kpi$, 2, $note$conversion rate by line of therapy (frontier 30d)$note$),
    ('business_impact_conversion_rate_line_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM triggers)::date AS data_through FROM (WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted) base$kpi$, 2, $note$conversion rate by line of therapy (frontier 30d; includes synthetic)$note$),
    -- ---- Conversion Rate windowed [brand, start, end) over trigger_timestamp ----
    ('business_impact_conversion_rate_windowed', $kpi$WITH triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= $2::timestamptz AND trigger_timestamp < $3::timestamptz AND ($1::text IS NULL OR brand_id = $1)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= $2::timestamptz AND t.trigger_timestamp < $3::timestamptz AND ($1::text IS NULL OR t.brand_id = $1) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 3, $note$windowed conversion rate [brand, start, end)$note$),
    ('business_impact_conversion_rate_windowed_include_synthetic', $kpi$WITH triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= $2::timestamptz AND trigger_timestamp < $3::timestamptz AND ($1::text IS NULL OR brand_id = $1)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= $2::timestamptz AND t.trigger_timestamp < $3::timestamptz AND ($1::text IS NULL OR t.brand_id = $1) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 3, $note$windowed conversion rate [brand, start, end) (includes synthetic)$note$),
    -- ---- Conversion Rate by severity tier, windowed [brand, segment, start, end) ----
    ('business_impact_conversion_rate_segment_windowed', $kpi$WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= $3::timestamptz AND t.trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 4, $note$windowed conversion rate by severity tier$note$),
    ('business_impact_conversion_rate_segment_windowed_include_synthetic', $kpi$WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= $3::timestamptz AND t.trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 4, $note$windowed conversion rate by severity tier (includes synthetic)$note$),
    -- ---- Conversion Rate by line-of-therapy, windowed [brand, line, start, end) ----
    ('business_impact_conversion_rate_line_windowed', $kpi$WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM (SELECT * FROM triggers WHERE is_synthetic = false) t INNER JOIN (SELECT * FROM treatment_events WHERE is_synthetic = false) te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= $3::timestamptz AND t.trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 4, $note$windowed conversion rate by line of therapy$note$),
    ('business_impact_conversion_rate_line_windowed_include_synthetic', $kpi$WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int), triggered AS (SELECT COUNT(DISTINCT trigger_id) AS total FROM triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id = $1) AND patient_id IN (SELECT patient_id FROM axis_patients)), converted AS (SELECT COUNT(DISTINCT t.trigger_id) AS total FROM triggers t INNER JOIN treatment_events te ON te.patient_id = t.patient_id WHERE t.trigger_timestamp >= $3::timestamptz AND t.trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR t.brand_id = $1) AND t.patient_id IN (SELECT patient_id FROM axis_patients) AND te.event_type::text = 'prescription' AND ($1::text IS NULL OR te.brand::text = $1) AND te.event_date >= t.trigger_timestamp::date AND te.event_date <= (t.trigger_timestamp + INTERVAL '30 days')::date) SELECT converted.total::float / NULLIF(triggered.total, 0) AS conversion_rate FROM triggered, converted$kpi$, 4, $note$windowed conversion rate by line of therapy (includes synthetic)$note$),
    -- ---- TRx Share windowed [brand, start, end) over event_date ----
    ('business_impact_trx_share_windowed', $kpi$WITH category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $2::timestamptz AND event_date < $3::timestamptz), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= $2::timestamptz AND event_date < $3::timestamptz) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 3, $note$windowed TRx share [brand, start, end)$note$),
    ('business_impact_trx_share_windowed_include_synthetic', $kpi$WITH category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $2::timestamptz AND event_date < $3::timestamptz), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= $2::timestamptz AND event_date < $3::timestamptz) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 3, $note$windowed TRx share [brand, start, end) (includes synthetic)$note$),
    -- ---- TRx Share by severity tier, windowed [brand, segment, start, end) ----
    ('business_impact_trx_share_segment_windowed', $kpi$WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 4, $note$windowed TRx share by severity tier$note$),
    ('business_impact_trx_share_segment_windowed_include_synthetic', $kpi$WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE LOWER(segment_assignment::text) = LOWER($2)), category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 4, $note$windowed TRx share by severity tier (includes synthetic)$note$),
    -- ---- TRx Share by line-of-therapy, windowed [brand, line, start, end) ----
    ('business_impact_trx_share_line_windowed', $kpi$WITH axis_patients AS (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE prior_therapy_lines = $2::int), category AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 4, $note$windowed TRx share by line of therapy$note$),
    ('business_impact_trx_share_line_windowed_include_synthetic', $kpi$WITH axis_patients AS (SELECT patient_id FROM patient_journeys WHERE prior_therapy_lines = $2::int), category AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)), brand_rx AS (SELECT COUNT(*) AS total FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 AND event_date >= $3::timestamptz AND event_date < $4::timestamptz AND patient_id IN (SELECT patient_id FROM axis_patients)) SELECT brand_rx.total::float / NULLIF(category.total, 0) AS share FROM category, brand_rx$kpi$, 4, $note$windowed TRx share by line of therapy (includes synthetic)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;

-- PostgREST caches the schema; reload so the new ids are visible.
NOTIFY pgrst, 'reload schema';
