-- ============================================================================
-- 113_kpi_ws2_truth_metrics_brand_variants.sql
-- WS2 trigger KPIs aligned to the DECLARED truth definitions + brand variants
-- (plan .claude/plans/2026-07-20-ws2-truth-metrics.md, COMM-ARMS Phase 4).
--
-- 1. RECALL (WS2-TR-002) definition v2 — IN PLACE on all 4 existing variants:
--    denominator = NEW STARTS (patients whose FIRST-EVER prescription lands in
--    the matured 30d window [frontier-44d, frontier-14d]); numerator = new
--    starts with a trigger dated on/before the first Rx. Replaces the
--    migration-044 proxy (any-Rx-in-30d denominator) that structurally read
--    ~0.10; disproof-validated 2026-07-20: 0.1025 -> 0.6750 portfolio, per-brand
--    ~0.673-0.676. The historical 0.10 was a MEASUREMENT ARTIFACT, not model
--    performance — kpi_history shows a definition-driven step, not improvement.
-- 2. PRECISION (WS2-TR-001) definition v2 — IN PLACE on all 4 existing
--    variants: accepted-and-converted / accepted-and-tracked (the declared
--    "trigger accepted AND downstream outcome achieved" truth shape).
--    NOTE: reads DEGENERATE (1.0) until the COMM-ARMS Phase 4 reseed lands the
--    decoupled conversion substrate (same deploy batch); post-reseed level
--    ~0.62 (real: P(Rx in 30d window | accepted, tracked)).
-- 3. MATURATION DEFERRAL: MEASURED-OFF (cheapest-disproof 2026-07-20). The
--    plan's deferral clause (evaluate only once obs_window + declared max lag
--    has elapsed, i.e. windows ending 44d/14d before the frontier) was tested
--    against the live substrate and FALSIFIED as a no-op: the #853 anchor-cap
--    piles injected conversion Rx at the data frontier, so the shifted window
--    reads recall 0.1166 (false critical) vs the honest 0.6750. On a ~0-lag
--    synthetic substrate deferral measures the wrong window for no benefit;
--    TRIG-DECOMP re-activates it with per-brand completeness curves when real
--    lagged sources connect (template: set LAG=<max declared lag> in the
--    generator and re-emit). Vocabulary scalar lags (7-14d) remain optimistic
--    vs the validated real 1-3mo band — same TRIG-DECOMP deliverable.
-- 4. NEW _brand / _brand_region (+_include_synthetic) variants for ALL 8 WS2
--    KPIs (brand=$1, region=$2), mirroring the 078 region-variant + 111
--    brand-sibling idioms: ADDITIVE rows, base statements untouched (except
--    the recall/precision v2 redefinition above), calculator routes via
--    synthetic_mode helpers. Region variants of recall/precision are also
--    frontier-anchored now (078's used NOW(); 089 made frontier the contract).
--
-- Idempotent (ON CONFLICT DO UPDATE). Depends on: 044 (registry+RPC), 066
-- (twins), 078 (region idiom), 089 (frontier anchoring), 111 (brand idiom),
-- 112 + Phase 4 reseed (decoupled conversion substrate for precision's level).
-- ============================================================================

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    ('trigger_performance_recall', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days'), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN (SELECT * FROM triggers WHERE is_synthetic = false) t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 0, $note$recall v2 = new-starts (first-ever Rx in matured 30d window) preceded by a trigger; definition v2 (plan 2026-07-20-ws2-truth-metrics): aligned to domain_vocabulary truth_definitions.next_best_action_truth; frontier-anchored 30d window; lag-maturation deferral MEASURED-OFF on the synthetic substrate (would read 0.1166 false-critical via the #853 frontier pile-up) — TRIG-DECOMP re-activates it with per-source completeness curves$note$),
    ('trigger_performance_recall_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM treatment_events WHERE event_type::text = 'prescription' GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days'), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN triggers t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 0, $note$recall v2 (includes synthetic); see base note$note$),
    ('trigger_performance_recall_region', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days' AND fr.patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($1))), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN (SELECT * FROM triggers WHERE is_synthetic = false) t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 1, $note$region-scoped recall v2; see base note$note$),
    ('trigger_performance_recall_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM treatment_events WHERE event_type::text = 'prescription' GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days' AND fr.patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($1))), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN triggers t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 1, $note$region-scoped recall v2 (includes synthetic); see base note$note$),
    ('trigger_performance_precision', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days') base$kpi$, 0, $note$precision v2 = accepted-and-converted / accepted-and-tracked (truth shape; conversion_flag substrate decoupled by COMM-ARMS Phase 4 — reads DEGENERATE 1.0 until the Phase 4 reseed lands); definition v2 (plan 2026-07-20-ws2-truth-metrics): aligned to domain_vocabulary truth_definitions.next_best_action_truth; frontier-anchored 30d window; lag-maturation deferral MEASURED-OFF on the synthetic substrate (would read 0.1166 false-critical via the #853 frontier pile-up) — TRIG-DECOMP re-activates it with per-source completeness curves$note$),
    ('trigger_performance_precision_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days') base$kpi$, 0, $note$precision v2 (includes synthetic); see base note$note$),
    ('trigger_performance_precision_region', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($1))) base$kpi$, 1, $note$region-scoped precision v2; see base note$note$),
    ('trigger_performance_precision_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($1))) base$kpi$, 1, $note$region-scoped precision v2 (includes synthetic); see base note$note$),
    ('trigger_performance_recall_brand', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days'), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN (SELECT * FROM triggers WHERE is_synthetic = false) t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date AND t.brand_id::text = $1) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 1, $note$brand-scoped recall v2 (brand new-starts x same-brand triggers)$note$),
    ('trigger_performance_recall_brand_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days'), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN triggers t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date AND t.brand_id::text = $1) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 1, $note$brand-scoped recall v2 (includes synthetic)$note$),
    ('trigger_performance_recall_brand_region', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM (SELECT * FROM treatment_events WHERE is_synthetic = false) treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days' AND fr.patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN (SELECT * FROM triggers WHERE is_synthetic = false) t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date AND t.brand_id::text = $1) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 2, $note$brand+region-scoped recall v2$note$),
    ('trigger_performance_recall_brand_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription'))::date AS data_through FROM (WITH first_rx AS (SELECT patient_id, MIN(event_date) AS first_rx_date FROM treatment_events WHERE event_type::text = 'prescription' AND brand::text = $1 GROUP BY patient_id), new_starts AS (SELECT fr.patient_id, fr.first_rx_date FROM first_rx fr WHERE fr.first_rx_date > (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '30 days' AND fr.first_rx_date <= (SELECT MAX(event_date) FROM treatment_events WHERE event_type::text = 'prescription') - INTERVAL '0 days' AND fr.patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))), preceded AS (SELECT DISTINCT ns.patient_id FROM new_starts ns JOIN triggers t ON t.patient_id = ns.patient_id WHERE t.trigger_timestamp::date <= ns.first_rx_date AND t.brand_id::text = $1) SELECT COUNT(DISTINCT p.patient_id)::float / NULLIF(COUNT(DISTINCT ns.patient_id), 0) AS recall FROM new_starts ns LEFT JOIN preceded p ON p.patient_id = ns.patient_id) base$kpi$, 2, $note$brand+region-scoped recall v2 (includes synthetic)$note$),
    ('trigger_performance_precision_brand', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped precision v2$note$),
    ('trigger_performance_precision_brand_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped precision v2 (includes synthetic)$note$),
    ('trigger_performance_precision_brand_region', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped precision v2$note$),
    ('trigger_performance_precision_brand_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped precision v2 (includes synthetic)$note$),
    ('trigger_performance_acceptance_rate_brand', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped acceptance_rate (mirrors certified frontier-anchored base + brand_id = $1)$note$),
    ('trigger_performance_acceptance_rate_brand_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped acceptance_rate (includes synthetic)$note$),
    ('trigger_performance_acceptance_rate_brand_region', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped acceptance_rate$note$),
    ('trigger_performance_acceptance_rate_brand_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped acceptance_rate (includes synthetic)$note$),
    ('trigger_performance_override_rate_brand', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped override_rate (mirrors certified frontier-anchored base + brand_id = $1)$note$),
    ('trigger_performance_override_rate_brand_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped override_rate (includes synthetic)$note$),
    ('trigger_performance_override_rate_brand_region', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped override_rate$note$),
    ('trigger_performance_override_rate_brand_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped override_rate (includes synthetic)$note$),
    ('trigger_performance_false_alert_rate_brand', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN false_positive_flag THEN 1 END)::float / NULLIF(COUNT(*), 0) AS false_alert_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped false_alert_rate (mirrors certified frontier-anchored base + brand_id = $1)$note$),
    ('trigger_performance_false_alert_rate_brand_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN false_positive_flag THEN 1 END)::float / NULLIF(COUNT(*), 0) AS false_alert_rate FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped false_alert_rate (includes synthetic)$note$),
    ('trigger_performance_false_alert_rate_brand_region', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN false_positive_flag THEN 1 END)::float / NULLIF(COUNT(*), 0) AS false_alert_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped false_alert_rate$note$),
    ('trigger_performance_false_alert_rate_brand_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN false_positive_flag THEN 1 END)::float / NULLIF(COUNT(*), 0) AS false_alert_rate FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped false_alert_rate (includes synthetic)$note$),
    ('trigger_performance_cfr_brand', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN change_failed THEN 1 END)::float / NULLIF(COUNT(CASE WHEN previous_trigger_id IS NOT NULL THEN 1 END), 0) AS cfr FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped cfr (mirrors certified frontier-anchored base + brand_id = $1)$note$),
    ('trigger_performance_cfr_brand_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN change_failed THEN 1 END)::float / NULLIF(COUNT(CASE WHEN previous_trigger_id IS NOT NULL THEN 1 END), 0) AS cfr FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped cfr (includes synthetic)$note$),
    ('trigger_performance_cfr_brand_region', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN change_failed THEN 1 END)::float / NULLIF(COUNT(CASE WHEN previous_trigger_id IS NOT NULL THEN 1 END), 0) AS cfr FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped cfr$note$),
    ('trigger_performance_cfr_brand_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT COUNT(CASE WHEN change_failed THEN 1 END)::float / NULLIF(COUNT(CASE WHEN previous_trigger_id IS NOT NULL THEN 1 END), 0) AS cfr FROM triggers WHERE TRUE AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped cfr (includes synthetic)$note$),
    ('trigger_performance_lead_time_brand', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_time_days) AS median_lead_time FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND lead_time_days IS NOT NULL AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped lead_time (mirrors certified frontier-anchored base + brand_id = $1)$note$),
    ('trigger_performance_lead_time_brand_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_time_days) AS median_lead_time FROM triggers WHERE TRUE AND lead_time_days IS NOT NULL AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1) base$kpi$, 1, $note$brand-scoped lead_time (includes synthetic)$note$),
    ('trigger_performance_lead_time_brand_region', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers))::date AS data_through FROM (SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_time_days) AS median_lead_time FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE TRUE AND lead_time_days IS NOT NULL AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped lead_time$note$),
    ('trigger_performance_lead_time_brand_region_include_synthetic', $kpi$SELECT base.*, ((SELECT MAX(trigger_timestamp) FROM triggers))::date AS data_through FROM (SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_time_days) AS median_lead_time FROM triggers WHERE TRUE AND lead_time_days IS NOT NULL AND trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) base$kpi$, 2, $note$brand+region-scoped lead_time (includes synthetic)$note$),
    ('trigger_performance_action_rate_uplift_brand', $kpi$WITH arms AS (SELECT control_group_flag, COUNT(*) FILTER (WHERE action_taken IS NOT NULL)::float / NULLIF(COUNT(*), 0) AS action_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE control_group_flag IS NOT NULL AND brand_id::text = $1 GROUP BY control_group_flag) SELECT (t.action_rate - c.action_rate) / NULLIF(c.action_rate, 0) AS action_rate_uplift, t.action_rate AS treatment_rate, c.action_rate AS control_rate FROM (SELECT action_rate FROM arms WHERE control_group_flag = false) t, (SELECT action_rate FROM arms WHERE control_group_flag = true) c$kpi$, 1, $note$brand-scoped action rate uplift (RCT arms within brand)$note$),
    ('trigger_performance_action_rate_uplift_brand_include_synthetic', $kpi$WITH arms AS (SELECT control_group_flag, COUNT(*) FILTER (WHERE action_taken IS NOT NULL)::float / NULLIF(COUNT(*), 0) AS action_rate FROM triggers WHERE control_group_flag IS NOT NULL AND brand_id::text = $1 GROUP BY control_group_flag) SELECT (t.action_rate - c.action_rate) / NULLIF(c.action_rate, 0) AS action_rate_uplift, t.action_rate AS treatment_rate, c.action_rate AS control_rate FROM (SELECT action_rate FROM arms WHERE control_group_flag = false) t, (SELECT action_rate FROM arms WHERE control_group_flag = true) c$kpi$, 1, $note$brand-scoped action rate uplift (includes synthetic)$note$),
    ('trigger_performance_action_rate_uplift_brand_region', $kpi$WITH arms AS (SELECT control_group_flag, COUNT(*) FILTER (WHERE action_taken IS NOT NULL)::float / NULLIF(COUNT(*), 0) AS action_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE control_group_flag IS NOT NULL AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)) GROUP BY control_group_flag) SELECT (t.action_rate - c.action_rate) / NULLIF(c.action_rate, 0) AS action_rate_uplift, t.action_rate AS treatment_rate, c.action_rate AS control_rate FROM (SELECT action_rate FROM arms WHERE control_group_flag = false) t, (SELECT action_rate FROM arms WHERE control_group_flag = true) c$kpi$, 2, $note$brand+region-scoped action rate uplift$note$),
    ('trigger_performance_action_rate_uplift_brand_region_include_synthetic', $kpi$WITH arms AS (SELECT control_group_flag, COUNT(*) FILTER (WHERE action_taken IS NOT NULL)::float / NULLIF(COUNT(*), 0) AS action_rate FROM triggers WHERE control_group_flag IS NOT NULL AND brand_id::text = $1 AND patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2)) GROUP BY control_group_flag) SELECT (t.action_rate - c.action_rate) / NULLIF(c.action_rate, 0) AS action_rate_uplift, t.action_rate AS treatment_rate, c.action_rate AS control_rate FROM (SELECT action_rate FROM arms WHERE control_group_flag = false) t, (SELECT action_rate FROM arms WHERE control_group_flag = true) c$kpi$, 2, $note$brand+region-scoped action rate uplift (includes synthetic)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;
