-- ============================================================================
-- 118_trigger_effectiveness_kpis.sql
-- Ask-bound allowlist statements for the trigger-effectiveness KPIs (#1360,
-- owner-ruled 2026-07-30: chat-KPI-path, NOT health_score).
--
-- WHY: the #1337 gold triage (PR #1359) surfaced a contract-coverage gap —
-- trigger precision / acceptance rate / override rate / funnel conversion are
-- real, data-backed platform metrics (prod triggers table, ~37k rows) that no
-- agent contract owned; five benchmark rows landed on the explainer stopgap.
-- The ruling: these KPIs are served by the chat KPI path — registered here,
-- resolved by name in kpi_calculate_tool, computed by
-- TriggerPerformanceCalculator through the migration-044 kpi_query RPC
-- (never raw SQL from the agent).
--
-- The legacy trigger_performance_* families (044/066/078/089/090/092/113)
-- stay untouched and byte-identical for unscoped/brand/region asks. The NEW
-- families bind the axes the ruling names — brand, region, trigger_type,
-- time-window — that the legacy variants cannot:
--
--   * trigger_effectiveness_<metric>            3 params ($1 brand, $2 region,
--     $3 trigger_type — ALL nullable; NULL = no filter), frontier-anchored
--     default window (089 idiom; data_through provenance column rides along).
--   * trigger_effectiveness_<metric>_windowed   4 params ($1 brand,
--     $2 trigger_type — nullable; $3/$4 half-open [start, end) bound on
--     trigger_timestamp). Region can NOT also bind — the kpi_query RPC caps
--     at 4 positional params (the 117 precedent) — so the calculator FAILS
--     CLOSED on region+window instead of silently dropping the region.
--     No data_through column: the window is explicit (WS3 _windowed idiom).
--
-- Metric definitions MIRROR the live registry state (read READ-ONLY from the
-- prod kpi_query_registry, 2026-07-30):
--   * precision      = v2 truth shape (migration 113): accepted-and-converted /
--     accepted-and-tracked, over the LAGGED [frontier-60d, frontier-30d]
--     cohort in the base form so the 30-day conversion window has matured.
--     The windowed form binds the ask's window directly; recent windows
--     under-count conversions until they mature (disclosed via the KPI's
--     measurement_caveat / needs_care windowable class, never blocked).
--   * acceptance     = accepted / delivered (090/092 delivered denominator:
--     delivery_status IN ('delivered','viewed')).
--   * override       = overridden / delivered (090).
--   * funnel (NEW, WS2-TR-009) = delivered -> viewed -> accepted -> actioned
--     -> outcome stage counts + headline rate n_actioned/n_delivered. The
--     headline deliberately STOPS at actioned: extending to outcome would
--     conflate outcome-TRACKING coverage with effectiveness (the v1 precision
--     trap, see the 113 note). n_viewed is informational: delivery_status is
--     a progression state ('viewed' is not required before acceptance), so
--     viewed is NOT monotone with accepted on this substrate (verified
--     READ-ONLY 2026-07-30: 9,351 viewed vs 18,120 accepted).
--
-- Region binds via the patient_journeys join (triggers carries no region
-- column — the 078 idiom); brand filters triggers.brand_id directly;
-- trigger_type filters triggers.trigger_type (8 live values, e.g.
-- prescription_opportunity, engagement_gap, adherence_risk).
--
-- Synthetic gating follows the ADDITIVE-twin idiom (mig 066/105/116/117):
-- base statements wrap taggable tables in (SELECT * FROM t WHERE
-- is_synthetic = false); the `_include_synthetic` twins are the unwrapped
-- originals. On THIS substrate every trigger row is synthetic and prod sets
-- E2I_KPI_INCLUDE_SYNTHETIC=true, so the twins are the live path; the base
-- forms fail closed (NULL) until real (non-synthetic) trigger data lands.
-- These ids are deliberately ABSENT from SYNTHETIC_TWINNED_QUERY_IDS (locked
-- to 066/085/095 by CI) — trigger_effectiveness_query_id() self-suffixes
-- under the showcase flag, exactly like windowed_query_id.
-- ----------------------------------------------------------------------------

INSERT INTO public.kpi_query_registry (query_id, sql, max_params, note) VALUES
    -- ---- Trigger Precision (WS2-TR-001, v2 definition) ----
    ('trigger_effectiveness_precision', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers)::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 ask-bound precision (v2, matured lagged cohort): $1 brand, $2 region, $3 trigger_type — all nullable$note$),
    ('trigger_effectiveness_precision_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM triggers)::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM triggers WHERE trigger_timestamp > (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '60 days' AND trigger_timestamp <= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 ask-bound precision (includes synthetic — the live path on this substrate)$note$),
    ('trigger_effectiveness_precision_windowed', $kpi$SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)$kpi$, 4, $note$#1360 windowed precision: $1 brand, $2 trigger_type (nullable), $3/$4 half-open window; recent windows under-count until the conversion window matures$note$),
    ('trigger_effectiveness_precision_windowed_include_synthetic', $kpi$SELECT COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked AND outcome_value > 0)::float / NULLIF(COUNT(*) FILTER (WHERE acceptance_status = 'accepted' AND outcome_tracked), 0) AS precision FROM triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)$kpi$, 4, $note$#1360 windowed precision (includes synthetic)$note$),
    -- ---- Acceptance Rate (WS2-TR-004, delivered denominator 090/092) ----
    ('trigger_effectiveness_acceptance_rate', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers)::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 ask-bound acceptance rate: $1 brand, $2 region, $3 trigger_type — all nullable$note$),
    ('trigger_effectiveness_acceptance_rate_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM triggers)::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 ask-bound acceptance rate (includes synthetic — the live path on this substrate)$note$),
    ('trigger_effectiveness_acceptance_rate_windowed', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)$kpi$, 4, $note$#1360 windowed acceptance rate: $1 brand, $2 trigger_type (nullable), $3/$4 half-open window$note$),
    ('trigger_effectiveness_acceptance_rate_windowed_include_synthetic', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'accepted' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS acceptance_rate FROM triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)$kpi$, 4, $note$#1360 windowed acceptance rate (includes synthetic)$note$),
    -- ---- Override Rate (WS2-TR-006, delivered denominator 090) ----
    ('trigger_effectiveness_override_rate', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers)::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 ask-bound override rate: $1 brand, $2 region, $3 trigger_type — all nullable$note$),
    ('trigger_effectiveness_override_rate_include_synthetic', $kpi$SELECT base.*, (SELECT MAX(trigger_timestamp) FROM triggers)::date AS data_through FROM (SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 ask-bound override rate (includes synthetic — the live path on this substrate)$note$),
    ('trigger_effectiveness_override_rate_windowed', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)$kpi$, 4, $note$#1360 windowed override rate: $1 brand, $2 trigger_type (nullable), $3/$4 half-open window$note$),
    ('trigger_effectiveness_override_rate_windowed_include_synthetic', $kpi$SELECT COUNT(CASE WHEN acceptance_status = 'overridden' THEN 1 END)::float / NULLIF(COUNT(CASE WHEN delivery_status IN ('delivered', 'viewed') THEN 1 END), 0) AS override_rate FROM triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)$kpi$, 4, $note$#1360 windowed override rate (includes synthetic)$note$),
    -- ---- Trigger Funnel Conversion (WS2-TR-009, NEW) ----
    ('trigger_effectiveness_funnel_conversion', $kpi$SELECT base.*, base.n_actioned::float / NULLIF(base.n_delivered, 0) AS funnel_conversion, (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers)::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed')) AS n_delivered, COUNT(*) FILTER (WHERE delivery_status = 'viewed') AS n_viewed, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted') AS n_accepted, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL) AS n_actioned, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL AND outcome_tracked AND outcome_value > 0) AS n_outcome FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM (SELECT * FROM patient_journeys WHERE is_synthetic = false) patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 funnel: stage counts delivered->viewed->accepted->actioned->outcome + headline n_actioned/n_delivered; $1 brand, $2 region, $3 trigger_type — all nullable$note$),
    ('trigger_effectiveness_funnel_conversion_include_synthetic', $kpi$SELECT base.*, base.n_actioned::float / NULLIF(base.n_delivered, 0) AS funnel_conversion, (SELECT MAX(trigger_timestamp) FROM triggers)::date AS data_through FROM (SELECT COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed')) AS n_delivered, COUNT(*) FILTER (WHERE delivery_status = 'viewed') AS n_viewed, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted') AS n_accepted, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL) AS n_actioned, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL AND outcome_tracked AND outcome_value > 0) AS n_outcome FROM triggers WHERE trigger_timestamp >= (SELECT MAX(trigger_timestamp) FROM triggers) - INTERVAL '30 days' AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR patient_id IN (SELECT patient_id FROM patient_journeys WHERE LOWER(geographic_region::text) = LOWER($2))) AND ($3::text IS NULL OR trigger_type::text = $3)) base$kpi$, 3, $note$#1360 funnel (includes synthetic — the live path on this substrate)$note$),
    ('trigger_effectiveness_funnel_conversion_windowed', $kpi$SELECT base.*, base.n_actioned::float / NULLIF(base.n_delivered, 0) AS funnel_conversion FROM (SELECT COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed')) AS n_delivered, COUNT(*) FILTER (WHERE delivery_status = 'viewed') AS n_viewed, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted') AS n_accepted, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL) AS n_actioned, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL AND outcome_tracked AND outcome_value > 0) AS n_outcome FROM (SELECT * FROM triggers WHERE is_synthetic = false) triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)) base$kpi$, 4, $note$#1360 windowed funnel: $1 brand, $2 trigger_type (nullable), $3/$4 half-open window$note$),
    ('trigger_effectiveness_funnel_conversion_windowed_include_synthetic', $kpi$SELECT base.*, base.n_actioned::float / NULLIF(base.n_delivered, 0) AS funnel_conversion FROM (SELECT COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed')) AS n_delivered, COUNT(*) FILTER (WHERE delivery_status = 'viewed') AS n_viewed, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted') AS n_accepted, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL) AS n_actioned, COUNT(*) FILTER (WHERE delivery_status IN ('delivered', 'viewed') AND acceptance_status = 'accepted' AND action_taken IS NOT NULL AND outcome_tracked AND outcome_value > 0) AS n_outcome FROM triggers WHERE trigger_timestamp >= $3::timestamptz AND trigger_timestamp < $4::timestamptz AND ($1::text IS NULL OR brand_id::text = $1) AND ($2::text IS NULL OR trigger_type::text = $2)) base$kpi$, 4, $note$#1360 windowed funnel (includes synthetic)$note$)
ON CONFLICT (query_id) DO UPDATE SET sql = EXCLUDED.sql, max_params = EXCLUDED.max_params, note = EXCLUDED.note;

-- PostgREST caches the schema; reload so the new ids are visible.
NOTIFY pgrst, 'reload schema';
