-- Migration 151: cohort contracts for the 12 goldstd registry rows -- only what is
-- provable from the training code (#2207 follow-up, owner decision 2026-09-23, PR
-- "feat(retrain): table-route split contract honours data_split").
--
-- WHY: migration 150 added the per-model cohort contract (cohort_data_source /
-- cohort_target_outcome) and deliberately did NOT backfill it, because at the time a
-- Supabase-table data_source could not be reloaded exactly (the loader's table route
-- had no brand/provenance/column scoping and never passed the trainer's split_enforcer)
-- and cohort_target_outcome had no provable value. Both premises are now closed:
--   * data_loader (src/agents/ml_foundation/data_preparer/nodes/data_loader.py) accepts
--     a TABLE dict {"type":"table","table":...,"filters":{...},"columns":[...]} and
--     honours the table's data_split column verbatim (exactly as the file route does);
--   * the goldstd training code (src/mlops/gold_standard_eval/cohort_spec.py,
--     feature_builder.py) proves table + brand partition + provenance + covariates +
--     label for the 9 patient rows.
-- 150 is already applied (schema_migrations 2026-09-22) and is NOT edited; its "NO
-- backfill" note is superseded by this file for the rows below.
--
-- PROVABLE (measured 2026-09-23, read-only):
--   * 9 patient rows <cohort>_<brand>_goldstd_lr_v1 were trained by FeatureBuilder on
--     patient_journeys WHERE brand=<brand> AND is_synthetic=true, label
--     _PATIENT_LABELS[cohort] (treatment_initiated / persistent_180d /
--     discontinued_180d), covariates _PATIENT_COVARIATES[cohort] (initiation: the
--     10-column _BASE10_INITIATION; persistence/discontinuation: the 9-column
--     _BASE9_COMMERCIAL). Arithmetic proof of table + brand: each row's
--     training_samples == the live table's train+validation count for its brand
--     EXACTLY (Kisqali 5294+1791=7085, Fabhalta 5367+1834=7201, Remibrutinib
--     5418+1727=7145). The live table's per-brand data_split is 60/20/10/10 within
--     +-2 % with non-empty holdouts and both classes in every split.
--   * The contract MUST carry "columns": days_to_treatment is NULL on 100 % of
--     non-initiated rows and non-NULL on 100 % of initiated rows, and
--     discontinued_180d == 1 - persistent_180d -- a whole-table retrain would learn
--     its own label (feature_builder.LEAKAGE_DENYLIST names these).
--   * "is_synthetic": true is an explicit filter so the contract does not depend on
--     the deployment's E2I_INCLUDE_SYNTHETIC env (the loader forces
--     include_synthetic=True when the contract names the key).
--   * 3 HCP rows hcp_adoption_<brand>_goldstd_lr_v1: the label column is `adopted`
--     (hcp_brand_adoption.adopted) -> cohort_target_outcome is provable and harmless
--     (the sweep enqueues only when BOTH columns are set).
--
-- STAYS NULL, and why:
--   * cohort_data_source for the 3 HCP rows: the goldstd frame is hcp_brand_adoption
--     JOIN hcp_profiles (5 covariates live on hcp_profiles), hcp_brand_adoption is not
--     in MLDataLoader.ML_TABLES, and the scope_definer rewrites any target containing
--     "adopt" to `will_adopt` (problem_classifier._infer_target_variable), so a table
--     retrain would fail the loader's target guard. Known pre-existing limit.
--   * both columns for the 2 archived csu_treatment_initiation_lr_* rows: trained on
--     an in-process generated dataset (src/mlops/prediction_synthesizer_deploy.py),
--     not on any table.
--   * cohort_feature_manifest_source everywhere: no goldstd path resolves a Layer-5
--     manifest.
--
-- SAFETY: every UPDATE is a compare-and-set on NULL (never overwrites a contract a
-- training run or manual trigger has healed), scoped to is_synthetic = false, and
-- literal-exact: the JSON is encode_data_source() output (json.dumps(sort_keys=True))
-- generated by script, so decode/encode round-trips byte-identically. Idempotent:
-- a second application matches zero rows.
--
-- NOTE: no BEGIN/COMMIT here -- the migration runner wraps each file.

-- 9 patient-grain goldstd rows: data_source + target_outcome.
UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "rep_detailing_high", "sample_dropped", "trigger_accepted", "treatment_initiated"], "filters": {"brand": "Remibrutinib", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'treatment_initiated'
 WHERE model_name = 'initiation_remibrutinib_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "rep_detailing_high", "sample_dropped", "trigger_accepted", "treatment_initiated"], "filters": {"brand": "Fabhalta", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'treatment_initiated'
 WHERE model_name = 'initiation_fabhalta_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "rep_detailing_high", "sample_dropped", "trigger_accepted", "treatment_initiated"], "filters": {"brand": "Kisqali", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'treatment_initiated'
 WHERE model_name = 'initiation_kisqali_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "copay_support", "psp_enrolled", "persistent_180d"], "filters": {"brand": "Remibrutinib", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'persistent_180d'
 WHERE model_name = 'persistence_remibrutinib_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "copay_support", "psp_enrolled", "persistent_180d"], "filters": {"brand": "Fabhalta", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'persistent_180d'
 WHERE model_name = 'persistence_fabhalta_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "copay_support", "psp_enrolled", "persistent_180d"], "filters": {"brand": "Kisqali", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'persistent_180d'
 WHERE model_name = 'persistence_kisqali_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "copay_support", "psp_enrolled", "discontinued_180d"], "filters": {"brand": "Remibrutinib", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'discontinued_180d'
 WHERE model_name = 'discontinuation_remibrutinib_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "copay_support", "psp_enrolled", "discontinued_180d"], "filters": {"brand": "Fabhalta", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'discontinued_180d'
 WHERE model_name = 'discontinuation_fabhalta_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_data_source = '{"columns": ["disease_severity", "academic_hcp", "geographic_region", "insurance_type", "age_at_diagnosis", "comorbidity_burden", "prior_therapy_lines", "copay_support", "psp_enrolled", "discontinued_180d"], "filters": {"brand": "Kisqali", "is_synthetic": true}, "table": "patient_journeys", "type": "table"}',
       cohort_target_outcome = 'discontinued_180d'
 WHERE model_name = 'discontinuation_kisqali_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_data_source IS NULL
   AND cohort_target_outcome IS NULL;

-- 3 HCP-grain goldstd rows: label only (see STAYS NULL above).
UPDATE ml_model_registry
   SET cohort_target_outcome = 'adopted'
 WHERE model_name = 'hcp_adoption_remibrutinib_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_target_outcome = 'adopted'
 WHERE model_name = 'hcp_adoption_fabhalta_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_target_outcome IS NULL;

UPDATE ml_model_registry
   SET cohort_target_outcome = 'adopted'
 WHERE model_name = 'hcp_adoption_kisqali_goldstd_lr_v1'
   AND is_synthetic = false
   AND cohort_target_outcome IS NULL;
