-- ROLLBACK for migration 143 (canonical TRx lane). NOT a forward migration:
-- scripts/run_migrations.sh excludes rollback_* files. Apply by hand only in a
-- recovery procedure (plan Task 29 Step 6b), from the checksummed copy staged
-- outside the deploy's reset (Task 29 Step 5b).
-- GENERATED by scripts/gen_canonical_volume_registry.py.

-- Canonical history first, so a restored event row cannot collide with it.
DELETE FROM public.kpi_history WHERE kpi_id IN ('WS3-BI-005', 'WS3-BI-006', 'WS3-BI-007', 'WS3-BI-008') AND source = 'business_metrics.value';

DO $restore$
DECLARE
    conflicts integer;
BEGIN
    IF to_regclass('public.kpi_history_rekey_143') IS NULL THEN
        RAISE EXCEPTION 'rollback 143: % is missing, so what the migration moved is unknown; restore refused', 'public.kpi_history_rekey_143';
    END IF;
    SELECT count(*) INTO conflicts
      FROM public.kpi_history_rekey_143 a
      JOIN public.kpi_history t
        ON t.kpi_id = a.source_kpi_id AND t.brand = a.brand
       AND t.region = a.region AND t.metric_date = a.metric_date
     WHERE NOT (t.value IS NOT DISTINCT FROM a.value AND t.status IS NOT DISTINCT FROM a.status AND t.source IS NOT DISTINCT FROM a.source AND t.is_synthetic IS NOT DISTINCT FROM a.is_synthetic);
    IF conflicts > 0 THEN
        RAISE EXCEPTION 'rollback 143: % rows under the original keys differ from the recorded payload; restore refused', conflicts;
    END IF;
    INSERT INTO public.kpi_history (id, kpi_id, brand, region, metric_date, value, status, source, is_synthetic, computed_at)
    SELECT a.source_history_id, a.source_kpi_id, a.brand, a.region, a.metric_date,
           a.value, a.status, a.source, a.is_synthetic, a.computed_at
      FROM public.kpi_history_rekey_143 a
    ON CONFLICT (kpi_id, brand, region, metric_date) DO NOTHING;
    DELETE FROM public.kpi_history t
     USING public.kpi_history_rekey_143 a
     WHERE a.disposition = 'moved' AND t.id = a.dest_history_id;
    DROP TABLE public.kpi_history_rekey_143;
END
$restore$;

DELETE FROM public.kpi_query_registry WHERE query_id IN ('canonical_volume_trx', 'canonical_volume_trx_region', 'canonical_volume_trx_windowed', 'canonical_volume_trx_windowed_region', 'canonical_volume_nrx', 'canonical_volume_nrx_region', 'canonical_volume_nrx_windowed', 'canonical_volume_nrx_windowed_region', 'canonical_volume_nbrx', 'canonical_volume_nbrx_region', 'canonical_volume_nbrx_windowed', 'canonical_volume_nbrx_windowed_region', 'canonical_volume_trx_share', 'canonical_volume_trx_share_region', 'canonical_volume_trx_share_windowed', 'canonical_volume_trx_share_windowed_region', 'canonical_volume_monthly_series', 'canonical_volume_trx_include_synthetic', 'canonical_volume_trx_region_include_synthetic', 'canonical_volume_trx_windowed_include_synthetic', 'canonical_volume_trx_windowed_region_include_synthetic', 'canonical_volume_nrx_include_synthetic', 'canonical_volume_nrx_region_include_synthetic', 'canonical_volume_nrx_windowed_include_synthetic', 'canonical_volume_nrx_windowed_region_include_synthetic', 'canonical_volume_nbrx_include_synthetic', 'canonical_volume_nbrx_region_include_synthetic', 'canonical_volume_nbrx_windowed_include_synthetic', 'canonical_volume_nbrx_windowed_region_include_synthetic', 'canonical_volume_trx_share_include_synthetic', 'canonical_volume_trx_share_region_include_synthetic', 'canonical_volume_trx_share_windowed_include_synthetic', 'canonical_volume_trx_share_windowed_region_include_synthetic', 'canonical_volume_monthly_series_include_synthetic');

NOTIFY pgrst, 'reload schema';
