/**
 * TimeSeries — claims-lag provisional treatment + nowcast overlay (backlog #45, PR-C)
 * ===================================================================================
 *
 * Page-level spec for the Rx-volume nowcast surface:
 *  - the nowcast fetch is gated to the Rx-volume family (off-family KPIs
 *    never fire the request — the endpoint would 422)                     (e)
 *  - with a populated arrival plane the chart splits into a solid mature
 *    segment + dashed provisional tail with hollow markers               (a)
 *  - the "Show Nowcast" toggle defaults OFF, renders the overlay + CI
 *    band when enabled, and persists the choice to localStorage          (c)
 *  - the LIVE degraded state (insufficient_maturity=true,
 *    reason='arrival_plane_not_populated') renders the mature chart
 *    untouched with an honest, disabled affordance — no overlay, no
 *    fabricated values, no error                                          (d)
 *
 * ResponsiveContainer is mocked with fixed dimensions (jsdom's
 * ResizeObserver stub never sizes it — probed before writing this spec).
 * KPICard sparklines also render recharts under this mock, so every chart
 * assertion is SCOPED to the "KPI History" card.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import * as React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import TimeSeries from './TimeSeries';

vi.mock('@/hooks/api/use-kpi', () => ({
  useKPIValue: vi.fn(),
  useKPIHistory: vi.fn(),
  useKPIHistoryCoverage: vi.fn(),
  useKPIHistoryMultiBrand: vi.fn(),
  useKPIHistoryNowcast: vi.fn(),
  useKPIMetadata: vi.fn(),
  useKPIList: vi.fn(),
  RX_VOLUME_KPI_IDS: new Set(['WS3-BI-005', 'WS3-BI-006', 'WS3-BI-007']),
}));

vi.mock('recharts', async (importOriginal) => {
  const actual = await importOriginal<typeof import('recharts')>();
  return {
    ...actual,
    ResponsiveContainer: ({ children }: { children: React.ReactElement }) => (
      <div style={{ width: 800, height: 400 }}>
        {React.cloneElement(children, { width: 800, height: 400 })}
      </div>
    ),
  };
});

import {
  useKPIValue,
  useKPIHistory,
  useKPIHistoryCoverage,
  useKPIHistoryMultiBrand,
  useKPIHistoryNowcast,
  useKPIMetadata,
  useKPIList,
} from '@/hooks/api/use-kpi';

const mockUseKPIValue = useKPIValue as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIHistory = useKPIHistory as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIHistoryCoverage = useKPIHistoryCoverage as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIHistoryMultiBrand = useKPIHistoryMultiBrand as unknown as ReturnType<
  typeof vi.fn
>;
const mockUseKPIHistoryNowcast = useKPIHistoryNowcast as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIMetadata = useKPIMetadata as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIList = useKPIList as unknown as ReturnType<typeof vi.fn>;

// The persisted-toggle contract (follows the #1303 `e2i-<page>-<what>` naming).
const SHOW_NOWCAST_STORAGE_KEY = 'e2i-timeseries-show-nowcast';

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false, gcTime: 0, staleTime: 0 },
      mutations: { retry: false },
    },
  });
  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
}

// =============================================================================
// FIXTURES
// =============================================================================

const kpiMetadata = {
  id: 'WS3-BI-010',
  name: 'Return on Investment',
  definition: 'Value generated by E2I-driven interventions vs platform cost',
  formula: 'incremental_value / platform_cost',
  calculation_type: 'derived',
  workstream: 'ws3_business',
  tables: [],
  columns: [],
  frequency: 'monthly',
  primary_causal_library: 'none',
};

const kpiList = [
  kpiMetadata,
  {
    ...kpiMetadata,
    id: 'WS3-BI-005',
    name: 'Total Prescriptions (TRx)',
    workstream: 'ws3_business',
  },
];

const coverage = [
  { kpi_id: 'WS3-BI-010', brands: [''], points: 3, first_date: '2026-04-01', last_date: '2026-06-01' },
  { kpi_id: 'WS3-BI-005', brands: [''], points: 7, first_date: '2026-01-01', last_date: '2026-07-01' },
];

// Mature /history series for TRx — INCLUDES the frontier month (2026-07-01),
// which the nowcast surface excludes server-side (anchor-cap pile-up).
const trxHistoryPoints = [
  { metric_date: '2026-01-01', value: 1200, status: 'healthy' },
  { metric_date: '2026-02-01', value: 1250, status: 'healthy' },
  { metric_date: '2026-03-01', value: 1290, status: 'healthy' },
  { metric_date: '2026-04-01', value: 1310, status: 'healthy' },
  { metric_date: '2026-05-01', value: 1322, status: 'healthy' },
  { metric_date: '2026-06-01', value: 1340, status: 'healthy' },
  { metric_date: '2026-07-01', value: 610, status: 'healthy' },
];

const roiHistoryPoints = [
  { metric_date: '2026-04-01', value: 1.83, status: 'warning' },
  { metric_date: '2026-05-01', value: 1.84, status: 'warning' },
  { metric_date: '2026-06-01', value: 1.85, status: 'warning' },
];

/** Populated arrival plane: 4 mature months + 2 provisional, frontier excluded. */
const NOWCAST_OK = {
  kpi_id: 'WS3-BI-005',
  brand: '',
  data_through: '2026-07-21',
  insufficient_maturity: false,
  reason: null,
  mature_months_used: 30,
  anchor_cap_month: '2026-07-01',
  arrival_plane_coverage: 1,
  ci_level: 0.95,
  count: 6,
  points: [
    { metric_date: '2026-01-01', mature_value: 1200, provisional_value: 1200, provisional: false, completion_factor: 1, nowcast_value: null, nowcast_ci_lower: null, nowcast_ci_upper: null },
    { metric_date: '2026-02-01', mature_value: 1250, provisional_value: 1250, provisional: false, completion_factor: 1, nowcast_value: null, nowcast_ci_lower: null, nowcast_ci_upper: null },
    { metric_date: '2026-03-01', mature_value: 1290, provisional_value: 1290, provisional: false, completion_factor: 1, nowcast_value: null, nowcast_ci_lower: null, nowcast_ci_upper: null },
    { metric_date: '2026-04-01', mature_value: 1310, provisional_value: 1310, provisional: false, completion_factor: 1, nowcast_value: null, nowcast_ci_lower: null, nowcast_ci_upper: null },
    { metric_date: '2026-05-01', mature_value: 1322, provisional_value: 1057, provisional: true, completion_factor: 0.8, nowcast_value: 1321.25, nowcast_ci_lower: 1274, nowcast_ci_upper: 1369 },
    { metric_date: '2026-06-01', mature_value: 1340, provisional_value: 744, provisional: true, completion_factor: 0.55, nowcast_value: 1352.7, nowcast_ci_lower: 1281, nowcast_ci_upper: 1420 },
  ],
};

/** The LIVE pre-reseed state: arrival plane not populated, zero points. */
const NOWCAST_DEGRADED = {
  kpi_id: 'WS3-BI-005',
  brand: '',
  data_through: null,
  insufficient_maturity: true,
  reason: 'arrival_plane_not_populated',
  mature_months_used: 0,
  anchor_cap_month: null,
  arrival_plane_coverage: 0,
  ci_level: 0.95,
  count: 0,
  points: [],
};

function queryResult(data: unknown) {
  return {
    data,
    isLoading: false,
    isError: false,
    error: null,
    refetch: vi.fn(),
    isRefetching: false,
  };
}

function mockNowcast(response: unknown) {
  mockUseKPIHistoryNowcast.mockImplementation((kpiId: string) =>
    queryResult(kpiId === 'WS3-BI-005' ? response : undefined)
  );
}

beforeEach(() => {
  vi.clearAllMocks();
  localStorage.clear();
  global.URL.createObjectURL = vi.fn(() => 'blob:mock-url');
  global.URL.revokeObjectURL = vi.fn();

  mockUseKPIValue.mockReturnValue(
    queryResult({
      kpi_id: 'WS3-BI-010',
      value: 1.85,
      status: 'warning',
      calculated_at: '2026-06-01T00:00:00Z',
      cached: false,
      metadata: {},
    })
  );
  mockUseKPIHistory.mockImplementation((kpiId: string) =>
    queryResult(
      kpiId === 'WS3-BI-005'
        ? { kpi_id: kpiId, brand: '', region: '', count: trxHistoryPoints.length, points: trxHistoryPoints }
        : { kpi_id: kpiId, brand: '', region: '', count: roiHistoryPoints.length, points: roiHistoryPoints }
    )
  );
  mockUseKPIMetadata.mockReturnValue(queryResult(kpiMetadata));
  mockUseKPIList.mockReturnValue(queryResult({ kpis: kpiList, total: kpiList.length }));
  mockUseKPIHistoryCoverage.mockReturnValue(
    queryResult({ coverage, total: coverage.length })
  );
  mockUseKPIHistoryMultiBrand.mockImplementation((_kpiId: string, brands: string[]) =>
    brands.map(() => queryResult(undefined))
  );
  // Default to the LIVE degraded state — tests opt into the populated plane.
  mockNowcast(NOWCAST_DEGRADED);
});

async function selectTRx(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole('combobox', { name: /^kpi$/i }));
  await user.click(await screen.findByRole('option', { name: /Total Prescriptions/ }));
}

/** Chart assertions are scoped to the KPI History card (KPICard sparklines
 *  also render recharts under the sized ResponsiveContainer mock). */
function chartCard(): HTMLElement {
  const card = screen.getByText('KPI History').closest('div[class*="rounded"]');
  expect(card).not.toBeNull();
  return card as HTMLElement;
}

function lineCurveCount(scope: HTMLElement): number {
  return scope.querySelectorAll('.recharts-line-curve').length;
}

/** The provisional tail renders as its own Line layer with this class hook
 *  (jsdom freezes recharts' draw-in animation at frame 0, overwriting
 *  stroke-dasharray on every curve — the class is the stable contract). */
function provisionalLayerCount(scope: HTMLElement): number {
  return scope.querySelectorAll('.metric-trend-provisional').length;
}

describe('TimeSeries nowcast (backlog #45 PR-C)', () => {
  // ===========================================================================
  // (e) off-family gating
  // ===========================================================================

  it('gates the nowcast fetch off for off-family KPIs and shows no affordance', () => {
    render(<TimeSeries />, { wrapper: createWrapper() });

    expect(mockUseKPIHistoryNowcast).toHaveBeenCalled();
    const offFamilyCalls = mockUseKPIHistoryNowcast.mock.calls.filter(
      (c: unknown[]) => c[0] === 'WS3-BI-010'
    );
    expect(offFamilyCalls.length).toBeGreaterThan(0);
    for (const call of offFamilyCalls) {
      expect((call[2] as { enabled?: boolean } | undefined)?.enabled).toBe(false);
    }
    expect(screen.queryByRole('button', { name: /show nowcast/i })).not.toBeInTheDocument();
  });

  it('enables the fetch for an Rx-volume KPI', async () => {
    const user = userEvent.setup();
    mockNowcast(NOWCAST_OK);
    render(<TimeSeries />, { wrapper: createWrapper() });
    await selectTRx(user);

    await waitFor(() => {
      const calls = mockUseKPIHistoryNowcast.mock.calls.filter(
        (c: unknown[]) => c[0] === 'WS3-BI-005'
      );
      expect(calls.length).toBeGreaterThan(0);
      expect(
        (calls[calls.length - 1][2] as { enabled?: boolean } | undefined)?.enabled
      ).toBe(true);
    });
  });

  it('with a region selected the fetch is gated off and the toggle says why (#1536)', async () => {
    const user = userEvent.setup();
    mockNowcast(NOWCAST_OK);
    // TRx grows region scopes in coverage — the region selector appears.
    mockUseKPIHistoryCoverage.mockReturnValue(
      queryResult({
        coverage: [
          coverage[0],
          {
            ...coverage[1],
            scopes: [
              {
                brand: '',
                region: '',
                points: 7,
                first_date: '2026-01-01',
                last_date: '2026-07-01',
              },
              {
                brand: '',
                region: 'northeast',
                points: 7,
                first_date: '2026-01-01',
                last_date: '2026-07-01',
              },
            ],
          },
        ],
        total: 2,
      })
    );
    render(<TimeSeries />, { wrapper: createWrapper() });
    await selectTRx(user);

    await user.click(await screen.findByRole('combobox', { name: /^region$/i }));
    await user.click(await screen.findByRole('option', { name: 'northeast' }));

    // The nowcast endpoint has no region dimension: the fetch gates off...
    await waitFor(() => {
      const calls = mockUseKPIHistoryNowcast.mock.calls.filter(
        (c: unknown[]) => c[0] === 'WS3-BI-005'
      );
      expect(
        (calls[calls.length - 1][2] as { enabled?: boolean } | undefined)?.enabled
      ).toBe(false);
    });
    // ...and the affordance stays visible but disabled with the reason —
    // never silently absent, never a mislabeled portfolio overlay.
    expect(screen.getByRole('button', { name: /show nowcast/i })).toBeDisabled();
    expect(screen.getByText(/no region dimension/i)).toBeInTheDocument();
  });

  // ===========================================================================
  // (a) provisional tail — default view
  // ===========================================================================

  it('renders the provisional tail dashed with hollow markers, overlay OFF by default', async () => {
    const user = userEvent.setup();
    mockNowcast(NOWCAST_OK);
    render(<TimeSeries />, { wrapper: createWrapper() });
    await selectTRx(user);

    const toggle = await screen.findByRole('button', { name: /show nowcast/i });
    expect(toggle).toHaveAttribute('aria-pressed', 'false');

    const card = chartCard();
    // Solid mature segment + dashed provisional tail.
    expect(lineCurveCount(card)).toBe(2);
    expect(provisionalLayerCount(card)).toBe(1);
    // Hollow markers on exactly the 2 provisional months.
    const hollowCount = [...card.querySelectorAll('.recharts-line-dots circle')].filter(
      (c) => c.getAttribute('fill') === 'var(--color-background)'
    ).length;
    expect(hollowCount).toBe(2);
    // Default view carries NO nowcast overlay — honest mature series only.
    expect(card.querySelector('.recharts-area')).not.toBeInTheDocument();

    // Footnote defines "provisional" and carries the claims frontier date.
    const footnote = screen.getByTestId('nowcast-footnote');
    expect(footnote.textContent).toMatch(/provisional/i);
    expect(footnote.textContent).toMatch(/Jul 21/);
    // The excluded frontier month is disclosed, not silently dropped.
    expect(footnote.textContent).toMatch(/frontier month/i);
  });

  // ===========================================================================
  // (c) opt-in overlay + persistence
  // ===========================================================================

  it('toggle ON renders overlay + CI band and persists; OFF hides and persists', async () => {
    const user = userEvent.setup();
    mockNowcast(NOWCAST_OK);
    render(<TimeSeries />, { wrapper: createWrapper() });
    await selectTRx(user);

    const toggle = await screen.findByRole('button', { name: /show nowcast/i });
    await user.click(toggle);

    expect(toggle).toHaveAttribute('aria-pressed', 'true');
    const card = chartCard();
    expect(card.querySelector('.recharts-area')).toBeInTheDocument();
    expect(lineCurveCount(card)).toBe(3);
    expect(localStorage.getItem(SHOW_NOWCAST_STORAGE_KEY)).toBe('true');

    await user.click(toggle);
    expect(toggle).toHaveAttribute('aria-pressed', 'false');
    expect(chartCard().querySelector('.recharts-area')).not.toBeInTheDocument();
    expect(localStorage.getItem(SHOW_NOWCAST_STORAGE_KEY)).toBe('false');
  });

  it('initializes the overlay from the persisted preference', async () => {
    const user = userEvent.setup();
    localStorage.setItem(SHOW_NOWCAST_STORAGE_KEY, 'true');
    mockNowcast(NOWCAST_OK);
    render(<TimeSeries />, { wrapper: createWrapper() });
    await selectTRx(user);

    const toggle = await screen.findByRole('button', { name: /show nowcast/i });
    expect(toggle).toHaveAttribute('aria-pressed', 'true');
    expect(chartCard().querySelector('.recharts-area')).toBeInTheDocument();
  });

  // ===========================================================================
  // (d) LIVE degraded state — arrival plane not populated
  // ===========================================================================

  it('degrades cleanly when the arrival plane is not populated', async () => {
    const user = userEvent.setup();
    // beforeEach default IS the degraded live state.
    render(<TimeSeries />, { wrapper: createWrapper() });
    await selectTRx(user);

    // The mature chart renders untouched: one solid line, no dashes, no band.
    const card = chartCard();
    await waitFor(() => expect(lineCurveCount(card)).toBe(1));
    expect(provisionalLayerCount(card)).toBe(0);
    expect(card.querySelector('.recharts-area')).not.toBeInTheDocument();

    // Honest affordance: the toggle is disabled with a truthful explanation —
    // never absent-but-broken, never a fabricated overlay.
    const toggle = screen.getByRole('button', { name: /show nowcast/i });
    expect(toggle).toBeDisabled();
    expect(screen.getByText(/nowcast unavailable/i)).toBeInTheDocument();
    expect(
      screen.getByText(/claims-arrival dates are not populated/i)
    ).toBeInTheDocument();

    // No error surface: degradation is an expected state, not a failure.
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
  });

  // ===========================================================================
  // Export honesty
  // ===========================================================================

  it('export carries the nowcast block only while the provisional view is active', async () => {
    const user = userEvent.setup();
    mockNowcast(NOWCAST_OK);
    const clickSpy = vi
      .spyOn(HTMLAnchorElement.prototype, 'click')
      .mockImplementation(() => {});
    const createObjectURL = global.URL.createObjectURL as ReturnType<typeof vi.fn>;

    render(<TimeSeries />, { wrapper: createWrapper() });

    // Off-family default KPI: no nowcast key in the export payload.
    await user.click(screen.getByRole('button', { name: /export/i }));
    const readBlob = (blob: Blob) =>
      new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = () => reject(reader.error);
        reader.readAsText(blob);
      });
    const first = JSON.parse(await readBlob(createObjectURL.mock.calls[0]?.[0] as Blob));
    expect(first).not.toHaveProperty('nowcast');

    // TRx with a populated plane: the provisional/nowcast points ride along.
    await selectTRx(user);
    await screen.findByRole('button', { name: /show nowcast/i });
    await user.click(screen.getByRole('button', { name: /export/i }));
    const second = JSON.parse(await readBlob(createObjectURL.mock.calls[1]?.[0] as Blob));
    expect(second.kpiId).toBe('WS3-BI-005');
    expect(second.nowcast).toBeDefined();
    expect(second.nowcast.data_through).toBe('2026-07-21');
    expect(Array.isArray(second.nowcast.points)).toBe(true);
    expect(second.nowcast.points.some((p: { provisional: boolean }) => p.provisional)).toBe(
      true
    );
    clickSpy.mockRestore();
  });
});
