/**
 * TimeSeries Page Tests
 * =====================
 *
 * Tests that the Time Series page is the single-mode KPI-history home:
 * wired to the live KPI hooks (issue #302 retired all `sample*` constants),
 * with an alphabetically-sorted KPI select defaulting to WS3-BI-010
 * (Return on Investment). The former "Model performance" mode moved to the
 * Model Performance page (sibling PR).
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import * as fs from 'node:fs';
import * as path from 'node:path';
import TimeSeries from './TimeSeries';

// Mock the live hooks the page should call.
vi.mock('@/hooks/api/use-kpi', () => ({
  useKPIValue: vi.fn(),
  useKPIHistory: vi.fn(),
  useKPIHistoryCoverage: vi.fn(),
  useKPIMetadata: vi.fn(),
  useKPIList: vi.fn(),
}));

import {
  useKPIValue,
  useKPIHistory,
  useKPIHistoryCoverage,
  useKPIMetadata,
  useKPIList,
} from '@/hooks/api/use-kpi';

const mockUseKPIValue = useKPIValue as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIHistory = useKPIHistory as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIHistoryCoverage = useKPIHistoryCoverage as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIMetadata = useKPIMetadata as unknown as ReturnType<typeof vi.fn>;
const mockUseKPIList = useKPIList as unknown as ReturnType<typeof vi.fn>;

const mockCreateObjectURL = vi.fn((_obj: Blob | MediaSource) => 'blob:mock-url');
const mockRevokeObjectURL = vi.fn();

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false, gcTime: 0, staleTime: 0 },
      mutations: { retry: false },
    },
  });
  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
}

const sampleKPIMetadata = {
  id: 'WS3-BI-010',
  name: 'Return on Investment',
  definition: 'Value generated by E2I-driven interventions vs platform cost',
  formula: 'incremental_value / platform_cost',
  calculation_type: 'derived',
  workstream: 'ws3_business',
  tables: [],
  columns: [],
  frequency: 'monthly',
  primary_causal_library: 'none',
};

// Deliberately unordered — the page must group by workstream + sort by KPI id.
// WS1-MP-* and CM-* entries must be filtered OUT (served on /model-performance
// / per-analysis surfaces respectively).
const sampleKPIList = [
  {
    ...sampleKPIMetadata,
    id: 'WS1-DQ-001',
    name: 'Source Coverage - Patients',
    workstream: 'ws1_data_quality',
  },
  sampleKPIMetadata,
  { ...sampleKPIMetadata, id: 'WS2-TR-005', name: 'Alert Yield', workstream: 'ws2_triggers' },
  {
    ...sampleKPIMetadata,
    id: 'WS1-DQ-002',
    name: 'Completeness - HCP Master',
    workstream: 'ws1_data_quality',
  },
  {
    ...sampleKPIMetadata,
    id: 'WS3-BI-007',
    name: 'New-to-Brand Prescriptions (NBRx)',
    workstream: 'ws3_business',
  },
  { ...sampleKPIMetadata, id: 'WS1-MP-001', name: 'ROC-AUC', workstream: 'ws1_model_performance' },
  {
    ...sampleKPIMetadata,
    id: 'CM-001',
    name: 'Average Treatment Effect (ATE)',
    workstream: 'causal_metrics',
  },
  // A workstream the page does not know: must surface under "Other", never
  // silently vanish (the failure mode a stale e2e fixture exposed in CI).
  {
    ...sampleKPIMetadata,
    id: 'WS9-XX-001',
    name: 'Future Metric',
    workstream: 'ws9_future_family',
  },
];

// Coverage: which KPIs have a real series. WS1-DQ-002 is deliberately absent
// (-> "no history yet" badge); WS3-BI-007 NBRx is per-brand ONLY (no '' scope).
const sampleCoverage = [
  { kpi_id: 'WS3-BI-010', brands: [''], points: 3, first_date: '2026-04-01', last_date: '2026-06-01' },
  { kpi_id: 'WS2-TR-005', brands: [''], points: 35, first_date: '2023-08-01', last_date: '2026-06-01' },
  { kpi_id: 'WS1-DQ-001', brands: [''], points: 1, first_date: '2026-07-08', last_date: '2026-07-08' },
  {
    kpi_id: 'WS3-BI-007',
    brands: ['Fabhalta', 'Kisqali', 'Remibrutinib'],
    points: 105,
    first_date: '2023-08-01',
    last_date: '2026-06-01',
  },
];

const sampleKPIValue = {
  kpi_id: 'WS3-BI-010',
  value: 1.85,
  status: 'warning' as const,
  calculated_at: '2026-06-01T00:00:00Z',
  cached: false,
  metadata: {},
};

beforeEach(() => {
  vi.clearAllMocks();
  global.URL.createObjectURL = mockCreateObjectURL;
  global.URL.revokeObjectURL = mockRevokeObjectURL;

  mockUseKPIValue.mockReturnValue({
    data: sampleKPIValue,
    isLoading: false,
    isError: false,
    error: null,
    refetch: vi.fn(),
    isRefetching: false,
  });
  // Default: a real monthly KPI history series from the /history endpoint.
  mockUseKPIHistory.mockReturnValue({
    data: {
      kpi_id: 'WS3-BI-010',
      brand: '',
      region: '',
      count: 3,
      points: [
        { metric_date: '2026-04-01', value: 1.83, status: 'warning' },
        { metric_date: '2026-05-01', value: 1.84, status: 'warning' },
        { metric_date: '2026-06-01', value: 1.85, status: 'warning' },
      ],
    },
    isLoading: false,
    isError: false,
    error: null,
    refetch: vi.fn(),
    isRefetching: false,
  });
  mockUseKPIMetadata.mockReturnValue({
    data: sampleKPIMetadata,
    isLoading: false,
    isError: false,
    error: null,
    refetch: vi.fn(),
    isRefetching: false,
  });
  mockUseKPIList.mockReturnValue({
    data: { kpis: sampleKPIList, total: sampleKPIList.length },
    isLoading: false,
    isError: false,
    error: null,
    refetch: vi.fn(),
    isRefetching: false,
  });
  mockUseKPIHistoryCoverage.mockReturnValue({
    data: { coverage: sampleCoverage, total: sampleCoverage.length },
    isLoading: false,
    isError: false,
    error: null,
    refetch: vi.fn(),
    isRefetching: false,
  });
});

describe('TimeSeries (KPI-history home)', () => {
  it('renders the KPI-focused header with no mode tabs', () => {
    render(<TimeSeries />, { wrapper: createWrapper() });

    expect(screen.getByText('Time Series Analysis')).toBeInTheDocument();
    expect(screen.getByText('KPI metric history over time.')).toBeInTheDocument();
    // The "Model performance" mode is gone — no tablist / tabs remain.
    expect(screen.queryAllByRole('tab')).toHaveLength(0);
    expect(screen.queryByText(/Model performance/i)).not.toBeInTheDocument();
    expect(screen.queryByText('Performance Trend')).not.toBeInTheDocument();
    expect(screen.queryByText('Model Selection')).not.toBeInTheDocument();
    // KPI content renders directly (no tab switch needed).
    expect(screen.getByText('KPI History')).toBeInTheDocument();
    expect(screen.getByText('Current KPI Status')).toBeInTheDocument();
  });

  it('defaults to WS3-BI-010 (Return on Investment) — the KPI with real history', () => {
    render(<TimeSeries />, { wrapper: createWrapper() });

    // The history + value hooks are driven by the default KPI id.
    expect(mockUseKPIHistory).toHaveBeenCalled();
    expect(mockUseKPIHistory.mock.calls[0]?.[0]).toBe('WS3-BI-010');
    expect(mockUseKPIValue).toHaveBeenCalled();
    expect(mockUseKPIValue.mock.calls[0]?.[0]).toBe('WS3-BI-010');
    // The select trigger surfaces the default KPI's display name.
    expect(screen.getByRole('combobox', { name: /^kpi$/i })).toHaveTextContent(
      'Return on Investment',
    );
  });

  it('groups the dropdown by workstream, shows KPI ids, hides MP-*/CM-*', async () => {
    const user = userEvent.setup();
    render(<TimeSeries />, { wrapper: createWrapper() });

    await user.click(screen.getByRole('combobox', { name: /^kpi$/i }));
    const options = await screen.findAllByRole('option');
    const texts = options.map((o) => o.textContent ?? '');

    // Group labels render for the workstreams present.
    expect(screen.getByText('Data Quality (WS1)')).toBeInTheDocument();
    expect(screen.getByText('Trigger Performance (WS2)')).toBeInTheDocument();
    expect(screen.getByText('Business Impact (WS3)')).toBeInTheDocument();
    // KPI ids are visible so families are identifiable.
    expect(texts.some((t) => t.includes('WS1-DQ-001'))).toBe(true);
    // Model-performance (lives on /model-performance) and causal-metrics
    // (per-analysis estimates) are NOT offered here.
    expect(texts.some((t) => t.includes('ROC-AUC') || t.includes('WS1-MP'))).toBe(false);
    expect(texts.some((t) => t.includes('CM-001') || t.includes('(ATE)'))).toBe(false);
    // Sorted by id within the group.
    const dqIdx1 = texts.findIndex((t) => t.includes('WS1-DQ-001'));
    const dqIdx2 = texts.findIndex((t) => t.includes('WS1-DQ-002'));
    expect(dqIdx1).toBeGreaterThanOrEqual(0);
    expect(dqIdx2).toBeGreaterThan(dqIdx1);
    // History-less entries are labeled honestly.
    expect(texts.find((t) => t.includes('WS1-DQ-002'))).toMatch(/no history yet/i);
    expect(texts.find((t) => t.includes('WS1-DQ-001'))).not.toMatch(/no history yet/i);
    // Unknown workstreams surface under "Other" — never silently dropped.
    expect(screen.getByText('Other')).toBeInTheDocument();
    expect(texts.some((t) => t.includes('WS9-XX-001'))).toBe(true);
  });

  it('selecting a KPI feeds the new id into the history hook', async () => {
    const user = userEvent.setup();
    render(<TimeSeries />, { wrapper: createWrapper() });

    await user.click(screen.getByRole('combobox', { name: /^kpi$/i }));
    await user.click(await screen.findByRole('option', { name: /Alert Yield/ }));

    await waitFor(() => {
      const calls = mockUseKPIHistory.mock.calls;
      expect(calls[calls.length - 1]?.[0]).toBe('WS2-TR-005');
    });
  });

  it('per-brand-only KPI: brand selector appears, snaps to a brand, feeds the hook', async () => {
    const user = userEvent.setup();
    render(<TimeSeries />, { wrapper: createWrapper() });

    // Default KPI is global-only in the sample coverage -> no brand selector.
    expect(screen.queryByRole('combobox', { name: /^brand$/i })).not.toBeInTheDocument();

    await user.click(screen.getByRole('combobox', { name: /^kpi$/i }));
    await user.click(await screen.findByRole('option', { name: /New-to-Brand/ }));

    // A global NBRx series is undefined by design — the page snaps to the
    // first real brand scope instead of showing a false empty-state.
    await waitFor(() => {
      const calls = mockUseKPIHistory.mock.calls;
      const last = calls[calls.length - 1];
      expect(last?.[0]).toBe('WS3-BI-007');
      expect(last?.[1]).toBe('Fabhalta');
    });

    const brandBox = screen.getByRole('combobox', { name: /^brand$/i });
    expect(brandBox).toHaveTextContent('Fabhalta');
    await user.click(brandBox);
    // No "All Brands" for a per-brand-only KPI.
    expect(screen.queryByRole('option', { name: /All Brands/i })).not.toBeInTheDocument();
    await user.click(await screen.findByRole('option', { name: 'Kisqali' }));
    await waitFor(() => {
      const calls = mockUseKPIHistory.mock.calls;
      expect(calls[calls.length - 1]?.[1]).toBe('Kisqali');
    });
  });

  it('time-range filter trims the KPI history series (not just UI state)', async () => {
    const user = userEvent.setup();
    // Build history that spans 2000 days so the 1825d default window (5 Years)
    // still trims the earliest ~175 points, proving the filter is applied.
    const today = new Date();
    const longHistory = Array.from({ length: 2000 }, (_, i) => {
      const d = new Date(today.getTime() - (2000 - i) * 24 * 60 * 60 * 1000);
      return { metric_date: d.toISOString().slice(0, 10), value: 0.5 + i * 0.001, status: 'warning' };
    });
    mockUseKPIHistory.mockReturnValue({
      data: { kpi_id: 'WS3-BI-010', brand: '', region: '', count: longHistory.length, points: longHistory },
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
      isRefetching: false,
    });

    const { container } = render(<TimeSeries />, { wrapper: createWrapper() });

    // The recharts container is present. The "Data Points" KPI card reflects
    // the filtered series length; default range is 1825d (5 Years) so we expect
    // a count strictly less than the full 2000-point history.
    const recharts = container.querySelector('.recharts-responsive-container');
    expect(recharts).toBeInTheDocument();

    const dataPointsLabel = screen.getByText('Data Points');
    const card = dataPointsLabel.closest('[class*="rounded"]');
    expect(card).not.toBeNull();
    const txt = (card!.textContent ?? '').replace(/,/g, '');
    const m = txt.match(/(\d+)/);
    expect(m).not.toBeNull();
    const defaultCount = Number(m![1]);
    expect(defaultCount).toBeGreaterThan(0);
    expect(defaultCount).toBeLessThan(2000);

    // Narrowing the range to 30 days shrinks the series further.
    await user.click(screen.getByRole('combobox', { name: /time range/i }));
    await user.click(await screen.findByRole('option', { name: /30 Days/i }));

    await waitFor(() => {
      const txt30 = (card!.textContent ?? '').replace(/,/g, '');
      const m30 = txt30.match(/(\d+)/);
      expect(m30).not.toBeNull();
      expect(Number(m30![1])).toBeLessThan(defaultCount);
    });
  });

  it('renders a recharts container fed by live hook history data', () => {
    const { container } = render(<TimeSeries />, { wrapper: createWrapper() });
    expect(container.querySelector('.recharts-responsive-container')).toBeInTheDocument();
  });

  it('shows QueryErrorState when the KPI history query errors', () => {
    const networkErr = new Error('Network unreachable');
    mockUseKPIHistory.mockReturnValue({
      data: undefined,
      isLoading: false,
      isError: true,
      error: networkErr,
      refetch: vi.fn(),
      isRefetching: false,
    });

    render(<TimeSeries />, { wrapper: createWrapper() });

    // QueryErrorState renders an Alert with role=alert
    const alerts = screen.getAllByRole('alert');
    expect(alerts.length).toBeGreaterThan(0);
  });

  it('shows loading indicator while the KPI history is loading', () => {
    mockUseKPIHistory.mockReturnValue({
      data: undefined,
      isLoading: true,
      isError: false,
      error: null,
      refetch: vi.fn(),
      isRefetching: false,
    });

    render(<TimeSeries />, { wrapper: createWrapper() });

    expect(screen.getByTestId('timeseries-loading')).toBeInTheDocument();
  });

  it('shows an honest empty-state when a KPI has no time series', () => {
    // A point-in-time KPI: a current value, but the /history endpoint returns
    // no points (no honest temporal source) — never a fabricated flat series.
    mockUseKPIValue.mockReturnValue({
      data: {
        kpi_id: 'WS1-DQ-001',
        value: 0.0576,
        status: 'critical' as const,
        calculated_at: '2026-06-15T00:00:00Z',
        cached: false,
        metadata: { include_synthetic: true },
      },
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
      isRefetching: false,
    });
    mockUseKPIHistory.mockReturnValue({
      data: { kpi_id: 'WS1-DQ-001', brand: '', region: '', count: 0, points: [] },
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
      isRefetching: false,
    });
    // No coverage entry for the selected KPI -> the point-in-time explanation.
    mockUseKPIHistoryCoverage.mockReturnValue({
      data: { coverage: [], total: 0 },
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
      isRefetching: false,
    });

    render(<TimeSeries />, { wrapper: createWrapper() });

    expect(screen.getByTestId('kpi-history-empty')).toBeInTheDocument();
    expect(screen.getByText(/No historical data for this KPI/i)).toBeInTheDocument();
    // Honest copy: history accrues from weekly captures; nothing is fabricated.
    expect(screen.getByText(/weekly live captures/i)).toBeInTheDocument();
    expect(screen.getByText(/no past values are fabricated/i)).toBeInTheDocument();
    // The current KPI value is still shown.
    expect(screen.getByText('Current KPI Status')).toBeInTheDocument();
  });

  it('summary cards show em-dashes (never zeros) when there is no series', () => {
    mockUseKPIHistory.mockReturnValue({
      data: { kpi_id: 'WS1-DQ-001', brand: '', region: '', count: 0, points: [] },
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
      isRefetching: false,
    });
    mockUseKPIHistoryCoverage.mockReturnValue({
      data: { coverage: [], total: 0 },
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
      isRefetching: false,
    });

    render(<TimeSeries />, { wrapper: createWrapper() });

    // Current Value / Average / Maximum / Minimum are undefined with 0 points.
    expect(screen.getAllByText('—').length).toBeGreaterThanOrEqual(4);
    // Data Points honestly reads 0.
    const dataPointsLabel = screen.getByText('Data Points');
    const card = dataPointsLabel.closest('[class*="rounded"]');
    expect(card?.textContent).toMatch(/0/);
  });

  it('export payload is KPI-only (no performance-mode fields)', async () => {
    const user = userEvent.setup();
    const clickSpy = vi
      .spyOn(HTMLAnchorElement.prototype, 'click')
      .mockImplementation(() => {});

    render(<TimeSeries />, { wrapper: createWrapper() });
    await user.click(screen.getByRole('button', { name: /export/i }));

    expect(mockCreateObjectURL).toHaveBeenCalledTimes(1);
    const blob = mockCreateObjectURL.mock.calls[0]?.[0] as Blob;
    const text = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(reader.error);
      reader.readAsText(blob);
    });
    const payload = JSON.parse(text);
    expect(payload.kpiId).toBe('WS3-BI-010');
    expect(payload.brand).toBe(''); // history scope provenance ('' = global)
    expect(payload.days).toBe(1825);
    expect(Array.isArray(payload.series)).toBe(true);
    expect(payload.series.length).toBeGreaterThan(0);
    // Performance-mode export fields must be gone.
    for (const key of ['mode', 'modelId', 'models', 'metric']) {
      expect(payload).not.toHaveProperty(key);
    }
    clickSpy.mockRestore();
  });

  it('KPICard usages never trigger the SAMPLE_SPARKLINE fallback (codex MED iter-2)', () => {
    // KPICard.tsx falls back to a `SAMPLE_SPARKLINE = [45, 52, 48, ...]` when
    // `sparklineData` is undefined. Every KPICard usage in TimeSeries.tsx
    // MUST pass `sparklineData=` explicitly (real series or [] to opt out).
    const sourcePath = path.resolve(__dirname, 'TimeSeries.tsx');
    const source = fs.readFileSync(sourcePath, 'utf-8');

    const kpiCardRegex = /<KPICard\b([^>]*?)\/>/gs;
    const matches = [...source.matchAll(kpiCardRegex)];
    expect(matches.length).toBeGreaterThan(0);

    const offenders: string[] = [];
    for (const match of matches) {
      const propsBlob = match[1];
      if (!/\bsparklineData\s*=/.test(propsBlob)) {
        offenders.push(match[0].slice(0, 120));
      }
    }

    if (offenders.length > 0) {
      throw new Error(
        `KPICard usages missing explicit \`sparklineData=\` (would trigger SAMPLE_SPARKLINE fallback):\n` +
          offenders.join('\n'),
      );
    }
  });

  it('performance mode is fully removed from the page source', () => {
    const sourcePath = path.resolve(__dirname, 'TimeSeries.tsx');
    const source = fs.readFileSync(sourcePath, 'utf-8');

    // The mode moved to the Model Performance page (sibling PR) — none of its
    // wiring may survive here.
    expect(source).not.toMatch(/usePerformanceTrend/);
    expect(source).not.toMatch(/mergeBrandSeries|meanPerDate/);
    expect(source).not.toMatch(/ts-cohort|ts-brand/);
    expect(source).not.toMatch(/GOLDSTD_BRANDS|BRAND_OPTIONS|COHORT_OPTIONS|METRIC_OPTIONS/);
    expect(source).not.toMatch(/TabsTrigger|TabsContent|TabsList/);
  });

  it('source file contains NO sample/mock data — by identifier AND by behavior', () => {
    const sourcePath = path.resolve(__dirname, 'TimeSeries.tsx');
    const source = fs.readFileSync(sourcePath, 'utf-8');

    // Strip block + line comments to avoid false positives in docstrings.
    const stripped = source
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/\/\/.*$/gm, '');

    // (a) Identifier-level — forbid the 38 enumerated constants + common
    //     bypass renames (MOCK_*, DEMO_*, FAKE_*, FIXTURE_*).
    const forbiddenIdentifiers = [
      /\bSAMPLE_[A-Z_]+\b/,
      /\bsample[A-Z]\w*\b/,
      /\bMOCK_[A-Z_]+\b/,
      /\bDEMO_[A-Z_]+\b/,
      /\bFAKE_[A-Z_]+\b/,
      /\bFIXTURE_[A-Z_]+\b/,
      /\bgenerateTimeSeriesData\b/,
      /\bgenerateForecastData\b/,
      /\bgenerateSeasonalityData\b/,
    ];
    for (const pattern of forbiddenIdentifiers) {
      const match = stripped.match(pattern);
      if (match) {
        throw new Error(
          `TimeSeries.tsx still contains forbidden mock-data identifier: ${match[0]} (pattern ${pattern})`,
        );
      }
    }

    // (b) Behavior-level — forbid large static array literals of
    //     `{date: ..., value: ...}` shape OR `{date: ..., trend: ...}` shape,
    //     which are how the original sample arrays were materialised. Caps
    //     are conservative; live test fixtures live in the .test.tsx file,
    //     not in the page source.
    const bigDateValueArray =
      /\[\s*(\{\s*[a-zA-Z_]+\s*:\s*['"`][\d-]+['"`]\s*,\s*value\s*:[^}]+\}\s*,\s*){5,}/;
    if (bigDateValueArray.test(stripped)) {
      throw new Error(
        'TimeSeries.tsx contains a large static `[{date, value}, ...]` array literal — looks like inlined sample data.',
      );
    }

    // (c) Behavior-level — forbid for-loops that synthesise time-series
    //     data inside the page (the original used `for (let i = 0; i < 90; i++)`
    //     plus `new Date(startDate)` to build mock arrays).
    const syntheticDateLoop =
      /for\s*\(\s*let\s+\w+\s*=\s*0\s*;\s*\w+\s*<\s*\d{2,}\s*;\s*\w+\+\+\s*\)\s*\{[\s\S]{0,400}new\s+Date\s*\(/;
    if (syntheticDateLoop.test(stripped)) {
      throw new Error(
        'TimeSeries.tsx contains a synthetic Date-loop — looks like client-side mock-data generation.',
      );
    }
  });
});
