#!/usr/bin/env python3
"""Generate the migration that syncs the DB tool registry rows with the live registry (#2003).

The ``tool_registry`` / ``tool_dependencies`` rows seeded by ``database/ml/013`` and
``027`` carry each tool's input/output JSON Schema and the field-level dependency
mappings. They were hand-written once and drifted from the registered tools. This script
renders them from ``create_default_tools()`` / ``DEPENDENCY_FIELD_MAPPINGS`` (which derive
from the live registry) into a migration that UPDATEs the seeded rows and fails loudly if
any seeded row is missing.

``tests/unit/test_agents/test_tool_composer/test_registry_schema_drift_2003.py`` compares
the newest ``database/ml`` migration carrying the sync marker with the live registry.
When a tool's declared inputs or output model change, that test fails; regenerate into
the NEXT migration number:

    python -m scripts.generate_tool_registry_sync_migration database/ml/NNN_tool_registry_schema_sync.sql
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

SYNC_MARKER = "tool-registry-schema-sync"
REGISTRY_TAG = "$tool_registry_sync$"
DEPENDENCIES_TAG = "$tool_dependencies_sync$"

# Live tools with no ``tool_registry`` row, and why. Adding rows is a schema decision
# (the category enum / source_agent CHECK), not a sync.
NOT_SEEDED_IN_DB: Dict[str, str] = {
    "cohort_builder": "tool_registry.source_agent CHECK does not admit cohort_constructor",
    "cohort_validator": "tool_registry.source_agent CHECK does not admit cohort_constructor",
    "cohort_statistics": "tool_registry.source_agent CHECK does not admit cohort_constructor",
    "model_inference": "never seeded (ml/013 predates it; ml/027 added only discovery/drift)",
}


def build_payloads() -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Registry rows and dependency rows for every seeded tool, from the live registry."""
    from src.agents.tool_composer.tool_registry import (
        DEPENDENCY_FIELD_MAPPINGS,
        create_default_tools,
    )

    registry_rows = [
        {
            "name": tool.name,
            "description": tool.description,
            "input_schema": tool.input_schema,
            "output_schema": tool.output_schema,
        }
        for tool in sorted(create_default_tools(), key=lambda t: t.name)
        if tool.name not in NOT_SEEDED_IN_DB
    ]
    dependency_rows = [
        {
            "consumer": consumer,
            "producer": producer,
            "output_field": output_field,
            "input_field": input_field,
        }
        for (consumer, producer), (output_field, input_field) in sorted(
            DEPENDENCY_FIELD_MAPPINGS.items()
        )
        if consumer not in NOT_SEEDED_IN_DB and producer not in NOT_SEEDED_IN_DB
    ]
    return registry_rows, dependency_rows


def _quoted(tag: str, rows: List[Dict[str, Any]]) -> str:
    body = json.dumps(rows, indent=2, ensure_ascii=False)
    if tag in body:
        raise ValueError(f"payload contains its own dollar-quote tag {tag}")
    return f"{tag}\n{body}\n{tag}"


def render_sql(
    registry_rows: List[Dict[str, Any]],
    dependency_rows: List[Dict[str, Any]],
    migration_name: str,
) -> str:
    return f"""-- ============================================================================
-- E2I Causal Analytics - Migration ml/{migration_name}
-- {SYNC_MARKER} (#2003)
-- ============================================================================
--
-- GENERATED by scripts/generate_tool_registry_sync_migration.py from the live tool
-- registry. Do not hand-edit: when a tool's declared inputs or output model change,
-- regenerate into the NEXT migration number (the drift test in
-- tests/unit/test_agents/test_tool_composer/test_registry_schema_drift_2003.py reads
-- the newest migration carrying the marker above).
--
-- The tool_registry input/output JSON Schemas and the tool_dependencies field
-- mappings seeded by ml/013 and ml/027 were written once and drifted from the
-- registered tools (e.g. sensitivity_analyzer declared causal_result/gamma_range in,
-- e_value/robustness_value out). This UPDATEs every seeded row to the registry's
-- description, input schema and output schema, and every seeded dependency to the
-- real producer output field / consumer input field. It raises if a seeded row is
-- missing, so a partial sync cannot pass silently. Idempotent: re-applying writes
-- the same values.
-- ============================================================================

DO $sync$
DECLARE
    v_expected integer;
    v_updated integer;
BEGIN
    WITH payload AS (
        SELECT *
        FROM jsonb_to_recordset({_quoted(REGISTRY_TAG, registry_rows)}::jsonb)
            AS t(name text, description text, input_schema jsonb, output_schema jsonb)
    )
    UPDATE tool_registry tr
    SET description = p.description,
        input_schema = p.input_schema,
        output_schema = p.output_schema
    FROM payload p
    WHERE tr.name = p.name;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_expected := {len(registry_rows)};
    IF v_updated <> v_expected THEN
        RAISE EXCEPTION 'tool_registry sync updated % of % seeded rows', v_updated, v_expected;
    END IF;

    WITH mapping AS (
        SELECT c.tool_id AS consumer_tool_id,
               p.tool_id AS producer_tool_id,
               m.output_field,
               m.input_field
        FROM jsonb_to_recordset({_quoted(DEPENDENCIES_TAG, dependency_rows)}::jsonb)
            AS m(consumer text, producer text, output_field text, input_field text)
        JOIN tool_registry c ON c.name = m.consumer
        JOIN tool_registry p ON p.name = m.producer
    )
    UPDATE tool_dependencies d
    SET output_field = mapping.output_field,
        input_field = mapping.input_field
    FROM mapping
    WHERE d.consumer_tool_id = mapping.consumer_tool_id
      AND d.producer_tool_id = mapping.producer_tool_id;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_expected := {len(dependency_rows)};
    IF v_updated <> v_expected THEN
        RAISE EXCEPTION 'tool_dependencies sync updated % of % seeded rows', v_updated, v_expected;
    END IF;
END $sync$;
"""


def main(argv: List[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    target = Path(argv[1])
    registry_rows, dependency_rows = build_payloads()
    target.write_text(render_sql(registry_rows, dependency_rows, target.name))
    print(f"wrote {target} ({len(registry_rows)} tools, {len(dependency_rows)} dependencies)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
