"""The per-HCP cohort column contract: what the Digital Twin plants on ``business_metrics``.

``per_hcp_rollup`` rows have two writers. The per-HCP ETL (``src/etl/business_metrics_per_hcp_etl.py``)
recomputes the trigger-derived value columns from the base tables on every upsert. The plant
(``scripts/backfill_segment_engagement.py --execute``) writes the synthetic-gold DGP the twin
estimates from: eight treatment channels (migration 099) and one outcome (migration 147). The
ETL never touches these columns (``tests/unit/test_digital_twin/effect/test_cohort_columns_single_writer.py``),
but its reconcile DELETES whole rows the recompute no longer produces -- and on 2026-09-21 a
full-window backfill deleted rows wholesale, the planted data went with them, and the twin went
dark for every brand. The ETL's preview therefore reports the obsolete rows that still carry
these columns, which means the ETL and the twin must share ONE list of them.

This module is that list. It lives here, not under ``src/digital_twin``, because importing any
module of that package runs ``src/digital_twin/__init__``, which pulls sklearn, dowhy and shap
(15.9 s and +507 MB, measured 2026-09-22) -- far too heavy for an ETL that runs on the light
worker. ``src.data`` modules are side-effect-free by charter. ``src/digital_twin/effect/provider.py``
re-exports these names, so every twin-side consumer keeps its import.
"""

from __future__ import annotations

from typing import Final

#: Canonical Digital Twin intervention -> the ``business_metrics`` column that carries its
#: planted treatment (see the DGP in ``scripts/backfill_segment_engagement.py``).
INTERVENTION_TREATMENT_MAP: Final[dict[str, str]] = {
    "email_campaign": "email_campaign_count",
    "call_frequency_increase": "call_frequency",
    "speaker_program_invitation": "speaker_program_count",
    "sample_distribution": "sample_volume",
    "peer_influence_activation": "peer_influence_score",
    "digital_engagement": "engagement_score",
    "patient_support_program": "patient_support_enrollment",
    "rep_training_quality": "rep_training_score",
}

#: The cohort OUTCOME has its own column (migration 147) so the ETL's ``conversion_rate``
#: recompute and the plant stop sharing one.
COHORT_OUTCOME_COLUMN: Final = "cohort_conversion_outcome"

#: Every column the plant writes, in a fixed order: the eight channels sorted, then the outcome.
PLANTED_COLUMNS: Final[tuple[str, ...]] = (
    *sorted(set(INTERVENTION_TREATMENT_MAP.values())),
    COHORT_OUTCOME_COLUMN,
)

# ---------------------------------------------------------------------------------------------
# Lane T1 (owner decision 2026-09-23: "approve DGP extension, we need to recover statistical,
# not structural effects"): the planted effect of each channel on ``hcp_brand_adoption.adopted``.
#
# ``adopted`` is generated by ``_compute_adoption`` (src/ml/synthetic/generators/
# hcp_adoption_artifact.py) from centrality, specialty affinity, its own ``treatment_arm`` and
# noise. Until this table existed it had NO term from the eight channels planted on
# ``business_metrics``, so the twin's estimator returned a structural null on it (0/48
# significant fits, 2026-09-23). The re-plant (``scripts/backfill_hcp_treatment_arm.py``) adds a
# deterministic per-HCP logit shift ``sum_k beta_k * (tbin_k - 0.5)`` where ``tbin_k`` is
# 1{collapsed per-(hcp, brand) exposure_k > the within-brand median} -- the estimator's own
# median contrast -- built by ``src/data/per_hcp_cohort_collapse.py``.
#
# ``ADOPTION_CHANNEL_LOGIT_BETA`` is the shift per channel on the LOGIT scale.
# ``ADOPTION_CHANNEL_PLANTED_RD`` is the REALISED risk difference (probability points, high vs
# low exposure) each beta produces on this DGP, measured on the live cohort: RD ~ 0.155 * beta,
# not the first-order 0.24 * beta, because the logit's spread (~1.5 sd incl. noise) flattens the
# average slope (explore_adoption_dgp.md section 3). It is what the recovery probe compares the
# estimator's ATE against.
#
# Why these magnitudes: they are recoverable as POINT estimates by the twin's real estimator at
# n ~ 3.4k joined HCPs per brand (96/96 CIs covering, Spearman 0.90, max |error| 0.053 in the
# read-only disproof), while moving < 10 % of labels, keeping the gold-standard AUC in its
# [0.70, 0.86] band and the treatment_arm ATE within 0.015 of its value. They are deliberately
# NOT inflated to beat the forest's conservative +-0.17 interval (``CausalForestDML.ate_interval``
# reports econml's documented upper bound, not sampling error); that is the estimator's defect
# and lane T2's scope. The ordering mirrors the business_metrics plant's tau ordering
# (engagement > speaker > peer > PSP > email > call > sample); ``rep_training_quality`` is the
# honest null so a spurious effect is detectable. Keyed by intervention name; the column is
# ``INTERVENTION_TREATMENT_MAP[intervention]``.
ADOPTION_CHANNEL_LOGIT_BETA: Final[dict[str, float]] = {
    "digital_engagement": 0.917,
    "speaker_program_invitation": 0.750,
    "peer_influence_activation": 0.625,
    "patient_support_program": 0.500,
    "email_campaign": 0.417,
    "call_frequency_increase": 0.333,
    "sample_distribution": 0.250,
    "rep_training_quality": 0.0,
}

#: Realised risk difference per channel (see above). ``rep_training_quality`` is the null.
ADOPTION_CHANNEL_PLANTED_RD: Final[dict[str, float]] = {
    "digital_engagement": 0.138,
    "speaker_program_invitation": 0.113,
    "peer_influence_activation": 0.093,
    "patient_support_program": 0.074,
    "email_campaign": 0.062,
    "call_frequency_increase": 0.050,
    "sample_distribution": 0.037,
    "rep_training_quality": 0.0,
}

#: The one channel planted with NO effect on ``adopted``: the recovery probe's null check.
ADOPTION_NULL_CHANNEL: Final = "rep_training_quality"
